### ISSUE TITLE
Hypothesis: Add share buttons

### ISSUE THREAD

**Issue by Tosin-Balogun** [nhsuk/nhsuk-service-manual#1001]
# What

If we put a button on the page that says 'share'

Then more people will click it, people won't feel intimated by the word 'contribute', it's clearer to people what they need to click

# We know this works;
- When we see users being drawn to the 'share button' quicker than previous versions. - We can do this by doing some user research - see if people have a better understanding of the word "share"
- We can monitor analytics of in-page clicks

# Task list
- [ ] Baseline the as-is situation
- [x] Prototype/Pilot
- [ ] Test/Monitor - 
- [ ] Record outcomes of change

# Related
EPIC: Improve Service Manual website contribution user experience #993

**Comment by Tosin-Balogun** [comment]
# Service manual page analytics - Feb 2021

**Note:** These stats only include the number of users who accept cookies.

### Top 5 visited pages:
1. /design-system - 2,592 (11.85%)
2. /home - 1,727 (7.90%)
3. /design-system/components - 1,364 (6.24%)
4. /design-system/styles - 879 (4.02%)
5. /service-standard - 878 (4.02%)

### Top 5 landing pages:
1. /home - 982 (18.21%)
2. /design-system - 731 (13.56%)
3. /content/inclusive-language - 352 (6.53%)
4. /service-standard - 280 (5.19%)
5. /content - 219 (4.06%)
---
[ga-service-manual-2021-feb__landing-pages.pdf](https://github.com/nhsuk/nhsuk-service-manual/files/6082412/ga-service-manual-2021-feb__landing-pages.pdf)
[ga-service-manual-2021-feb__total-page-visits.pdf](https://github.com/nhsuk/nhsuk-service-manual/files/6082413/ga-service-manual-2021-feb__total-page-visits.pdf)

**Comment by Tosin-Balogun** [comment]
# Share your findings button
## Methodology

People were asked to complete a first click test on Optimal Workshop. They were given the following task to complete:

>During some user research, you found that the breadcrumbs didn't really work well. You want to share this insight with the service manual to try to change the way breadcrumbs are presented. Where would you click to do this?

They were asked to complete this task twice, but shown different screens each time. The task order was randomised to reduce order effects.

## Results

 
<img width="1260" alt="Screenshot 2021-03-23 at 17 14 48" src="https://user-images.githubusercontent.com/71393402/112188872-4ffd8900-8bfb-11eb-9df0-09811e693a85.png">


The image on the left shows the variation 1 screen, showing a "Have you tested this pattern?" section, with a "Share your findings" button, on the left hand side, under the side navigation.

The image on the right shows the variation 2 screen, showing a "Have you tested this pattern?" section, with a "Share your findings" button, at the bottom of the main page.

### Variation 1

78% of people successfully clicked either the "Share your findings" button or the "get in touch to share your research findings" link.

- 9% clicked the "Share your findings" button
- 69% clicked the "get in touch to share your research findings" link

#### Other places people clicked included:

- 6% clicked the "Community and contribution" link in the main top navigation
- 10% clicked the "get in touch" link at the bottom of the page

People took 13.2 seconds on average to do their first click.

### Variation 2

82% of people successfully clicked either the "Share your findings" button or the "get in touch to share your research findings" link.

- 58% clicked the "Share your findings" button
- 24% clicked the "get in touch to share your research findings" link

##### Other places people clicked included:

- 6% clicked the "Community and contribution" link in the main top navigation
- 3% clicked the "Component" link in the breadcrumbs navigation
- 9% clicked the "get in touch" link at the bottom of the page

People took 12.7 seconds on average to do their first click.

## Recommendations
- Variation 2 had a higher proportion of people clicking on the "Share your findings" button.  This shows that it was probably a more obvious for people to click compared to the side button in variation 1.
100% of people who had not used the service manual before clicked the "Share your findings" button in both variations.
**Having navigation and CTAs within the page is better than having them in the side navigation.**
- The page tested was quite short, and both "Share your findings" button and "get in touch to share your research findings" link were quite close together. It would be good to see where people might click if these two sections are more separated.
**Understand where people might click if the two feedback links are separated.**
- People are still clicking the generic "get in touch" link at the bottom of the page. We should look to repurpose this link, or make a more obvious distinction between "get in touch" and contributions areas.
**Investigate how to distinguish between "get in touch" and allowing people to make contributions.**

**Comment by Tosin-Balogun** [comment]
# Hypotheses
- If we changed the contribution prompt to be a question begging an answer, people would feel invited and encouraged to enter the contribution process. We know this works if we see an increase in people starting a contribution from this prompt
- If we set expectations of GitHub being part of the contribution journey, a user would feel encouraged to continue the contribution. We know this works, if we hear people tell us it helped them make a GitHub account or we see new commenters on existing issues
- If we replace the hyperlink to contribution with an action link so it stands out more, people will see the call to action more easily. We know this works if we see an increase in people starting a contribution from this link

**Comment by Tosin-Balogun** [comment]
Testing the idea with specificity on the action link
-----
<img width="520" alt="Screenshot 2021-03-29 at 10 38 58" src="https://user-images.githubusercontent.com/71393402/112818045-02f63880-907b-11eb-8558-b097c2530207.png">

**Comment by sarawilcox** [comment]
Hi @Tosin-Balogun, does the action link draw in the name of the component automatically?

I'm finding that the partials don't really work from a content design point of view, @davidhunter08. The example in the review date pattern is rather horrible. 
![Screenshot 2021-03-29 at 11 36 49](https://user-images.githubusercontent.com/45792959/112824992-2329f580-9083-11eb-8cc5-e43a1507b9f8.png)

**Comment by Tosin-Balogun** [comment]
@sarawilcox - In the case of the specificity one i was testing above, yes. It replaces the name of the suffix with the relevant component/style/pattern.

**Comment by davidhunter08** [comment]
> Hi @Tosin-Balogun, does the action link draw in the name of the component automatically?
> 
> I'm finding that the partials don't really work from a content design point of view, @davidhunter08. The example in the review date pattern is rather horrible.
> ![Screenshot 2021-03-29 at 11 36 49](https://user-images.githubusercontent.com/45792959/112824992-2329f580-9083-11eb-8cc5-e43a1507b9f8.png)

@Tosin-Balogun are we not making the text "on Warning Callout" visually hidden?

**Comment by Tosin-Balogun** [comment]
@davidhunter08 - The current version does not have the component name within the action link. It just says 'Share your research findings'. The test was to see what it looks like if we added the suffix and if it makes sense given some component or pattern names are longer

**Comment by sarawilcox** [comment]
The link text needs to refer to the name of the page it's linking to and where it is. We can't just say "Share your research findings". If we're following our own guidance, it would say: "Share your research findings about the warning callout in GitHub".

**Comment by sarawilcox** [comment]
I've set up a separate ticket for testing and monitoring: 
- [Plan testing of hypotheses around contribution](https://github.com/nhsuk/nhsuk-service-manual/issues/1115)
- [Monitor changes to contributions](https://github.com/nhsuk/nhsuk-service-manual/issues/1116)
