### ISSUE TITLE
Hypothesis: Change nav header to 'contribution'

### ISSUE THREAD

**Issue by Tosin-Balogun** [nhsuk/nhsuk-service-manual#1003]
## What

If we change the "community" section to "contribution", then more people will know they can contribute, because the purpose of this section of the service manual will be clear from just the navigation

## We know this works;
- When we see people quickly & easily finding the path to contribution on the main header.
- We can compare the number of different people contributing on GitHub before and after a name change
- We can measure page hits before and after a change in naming
- We can do a comparative testing between the as-is and could-be scenario (A/B)

## Task list
- [x] [Baseline current performance](https://github.com/nhsuk/nhsuk-service-manual/issues/1003#issuecomment-790477177)
- [x] [Make changes to the service manual](https://github.com/nhsuk/nhsuk-service-manual/pull/1020)
- [x] Release changes

## Related
EPIC: Improve Service Manual website contribution user experience #993

## Next steps
[Review performance against baseline stats](https://github.com/nhsuk/nhsuk-service-manual/issues/1023)

**Comment by Tosin-Balogun** [comment]
@amyj2110 @henocookie @davidhunter08 - Do you know have the link to the previous research about the nav header, so i can reference it :)

**Comment by davidhunter08** [comment]
You can find it in confluence https://nhsd-confluence.digital.nhs.uk/display/SMDS/User+research+for+redesign

<img width="1018" alt="Screenshot 2021-03-03 at 12 37 12" src="https://user-images.githubusercontent.com/14331000/109807106-624c5e80-7c1d-11eb-8161-6b67c5e88095.png">

<img width="1028" alt="Screenshot 2021-03-03 at 12 37 34" src="https://user-images.githubusercontent.com/14331000/109807117-64aeb880-7c1d-11eb-883d-3a26798086ad.png">

**Comment by Tosin-Balogun** [comment]
@davidhunter08 - Made a start on the section header hypothesis ( see commit branch ☝🏿 ).
@sarawilcox  has helped in making the language much clearer. 
Only made changes to the labels, will need to look at the `/community` links later on.

**Comment by Tosin-Balogun** [comment]
# Service manual page analytics - Feb 2021
### Top 5 visited pages:
1. /design-system - 2,592 (11.85%)
2. /home - 1,727 (7.90%)
3. /design-system/components - 1,364 (6.24%)
4. /design-system/styles - 879 (4.02%)
5. /service-standard - 878 (4.02%)

### Top 5 landing pages:
1. /home - 982 (18.21%)
2. /design-system - 731 (13.56%)
3. /content/inclusive-language - 352 (6.53%)
4. /service-standard - 280 (5.19%)
5. /content - 219 (4.06%)

**Comment by Tosin-Balogun** [comment]
Updating the url links to match the labels on the pages based on the feedback the IA research


[URL standards for the NHS website (NHS.UK)
#265](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/265)

**Comment by Tosin-Balogun** [comment]
# Community VS Community and contribution

## Methodology

People were asked to complete a first click test on Optimal Workshop. They were given the following task to complete:

>Your team has created a new way to show images on the website. It recently tested well with users. You want to share this with the service manual team so it can be added to the service manual. Where would you click to do this?

They were asked to complete this task twice, but shown different screens each time. The task order was randomised to reduce order effects.

## Results

 
<img width="1269" alt="Screenshot 2021-03-23 at 15 23 12" src="https://user-images.githubusercontent.com/71393402/112171454-bda1b900-8beb-11eb-97c6-a7611f32aee9.png">


The image on the left shows the control screen, showing just the word "Community" in the main top navigation, and in the card navigation.

The image on the right shows the variation screen, showing the words "Community and contribution" in the main top navigation, and in the card navigation. 

### Control

67% of people successfully clicked either the "Community" link in the main top navigation or the "Community" card.

- 6% clicked the community link in the main top navigation
- 61% clicked the community card

#### Other places people clicked included:

- 3% clicked the "Content style guide" link in the main top navigation
- 3% clicked the "What's new" link
- 25% clicked the "get in touch" link

People took 16.8 seconds on average to do their first click.

### Variation

72% of people successfully clicked either the "Community and contribution" link in the main top navigation or the "Community and contribution" card.

- 41% clicked the "Community and contribution" link in the main top navigation
- 31% clicked the "Community and contribution" card

#### Other places people clicked included:

- 6% clicked the "Design system" card
- 19% clicked the "get in touch" link

People took 13.3 seconds on average to do their first click.

## Recommendations
- The control and variation don't have much difference in success rates. This indicates that people are probably familiar with the word "Community" and what it means. There was not much difference in success rate between people who used the service manual and people who did not. However, there were only a small number of participants who had not used the service manual before.
-- More testing could be done with people who don't regularly use the service manual. 
- On average, people were able to find the "Community and contribution" link slightly faster. This indicates it might be a little more recognisable as the right place to complete this task.
-- More testing could be done with different tasks.
- A high proportion of people are still clicking on the "get in touch" link. We should look to repurpose this link, or make a more obvious distinction between "get in touch" and contributions areas.
-- Investigate how to distinguish between "get in touch" and allowing people to make contributions.
