### ISSUE TITLE
Follow up action/publish changes after 24 March Style Council meeting

### ISSUE THREAD

**Issue by georginaplatt** [nhsuk/nhsuk-service-manual#1064]
## What

Hold meeting, communicate outcomes and take follow up actions, including publishing any changes

## Dependent on

[Hold March 2021 Content Style Council meeting #1063](https://github.com/nhsuk/nhsuk-service-manual/issues/1063)

## To do
 
- [x] Meeting notes written up and shared on NHS.UK content channel first
- [x]  Meeting notes signed off by clinicans - to do on Friday 16 April
- [ ]  Meeting notes shared by email with the mailing list - will send with next email
- [x]  Amendments made to style guide and published - GP systems entry added. We'll follow up alt text issue with [meeting with Alistair](https://github.com/nhsuk/service-manual-internal/issues/66). 
- [x]  GitHub updated
- [x]  Communicate outcomes of March Style Council meeting

**Comment by sarawilcox** [comment]
Posted notes on Slack #content channel. Waiting for any comments/concerns.

**Comment by sarawilcox** [comment]
I'm working on the entry for GP system supplier names. Have sent a few queries to Olivia Thornton.

Entry for alt text needs to go to AWG.
