### ISSUE TITLE
Follow up action/publish changes after April Style Council meeting

### ISSUE THREAD

**Issue by georginaplatt** [nhsuk/nhsuk-service-manual#1066]
## What
Hold meeting, communicate outcomes and take follow up actions, including publishing any changes

## Dependent on
[Hold April 2021 Content Style Council meeting #1065](https://github.com/nhsuk/nhsuk-service-manual/issues/1065)

## To do
 
- [ ] Meeting notes written up and shared on NHS.UK content channel first
- [ ]  Meeting notes signed off by clinicans - end of first week in May
- [ ]  Meeting notes shared by email with the mailing list
- [ ]  Amendments made to style guide and published
- [ ]  GitHub updated
- [ ]  Communicate outcomes of April Style Council meeting

**Comment by sarawilcox** [comment]
Not needed. No April meeting.
