### ISSUE TITLE
Prepare for May 2021 Content Style Council meeting

### ISSUE THREAD

**Issue by georginaplatt** [nhsuk/nhsuk-service-manual#1067]
## What

Invite people, prepare the agenda and slides for the meeting.

## To do

- [ ]  Arrange room - not needed
- [ ]  Agree meeting date
- [ ]  Arrange Teams meeting and send out invite
- [ ]  Firm up agenda
- [ ]  Get issues ready with colleagues
- [ ]  Make sure that GitHub is up to date
- [ ]  Share agenda and info about topics up for discussion - by email, on NHS.UK and NHS digital service manual Slack
- [ ]  Prepare slides
- [ ]  Olivia to chair the meeting

**Comment by chrimesdev** [comment]
May was a couple of months ago, I presume this meeting went ahead.
