### ISSUE TITLE
Follow up action/publish changes after May Style Council meeting

### ISSUE THREAD

**Issue by georginaplatt** [nhsuk/nhsuk-service-manual#1069]
## What

Hold meeting, communicate outcomes and take follow up actions, including publishing any changes

## Dependent on

[Hold May 2021 Content Style Council meeting #1068](https://github.com/nhsuk/nhsuk-service-manual/issues/1068)

## To do

- [x]  Meeting notes written up and shared on NHS.UK content channel first
- [x]  Meeting notes signed off by clinicans - end of first week in June
- [ ]  Meeting notes shared by email with the mailing list
- [x]  Amendments made to style guide and published
- [x]  GitHub updated
- [x]  Communicate outcomes of May Style Council meeting

**Comment by sarawilcox** [comment]
I've put the notes from the last meeting in the #content Slack channel for comment. Will send them to the clinicians end of play Tuesday.

**Comment by sarawilcox** [comment]
Sent meeting notes to clinicians for approval. No comments on Slack.

**Comment by sarawilcox** [comment]
Everything apart from the issue on [updating the images guidance](https://github.com/nhsuk/nhsuk-service-manual/issues/1231) is now in the review environment. 

I've chased the clinicians and asked someone in MT1 to proof the content in the review environment.

When we know that we can publish, I'll update the What's new section.

**Comment by sarawilcox** [comment]
Published
