### ISSUE TITLE
Prepare for July Content Style Council meeting

### ISSUE THREAD

**Issue by georginaplatt** [nhsuk/nhsuk-service-manual#1070]
## What

Invite people, prepare the agenda and slides for the meeting.

## To do

- [ ]  Arrange room - not needed
- [x]  Agree meeting date - thinking Tuesday 27 July
- [x]  Arrange Teams meeting and send out invite witb notes from last meeting
- [x]  Firm up agenda 
- [x]  Get issues ready with colleagues
- [x]  Make sure that GitHub is up to date
- [x]  Share agenda and info about topics up for discussion - by email, on NHS.UK and NHS digital service manual Slack
- [x]  Prepare slides 
- [x]  Sent out slides the day before

**Comment by EllenDoyle** [comment]
@sarawilcox and @georginaplatt  - if you need any help with the logistics for this please give me a shout.

**Comment by sarawilcox** [comment]
Thanks @EllenDoyle. I need to decide when to hold the next meeting - in July or August. I normally hold a meeting once a month but that feels too much at the moment, what with MVRs and other work going on in the team. Will welcome your thoughts. Maybe something for planning on Thursday?

**Comment by EllenDoyle** [comment]
Happy to discuss Thursday Sara. I will be led by your thoughts on when is the best time to hold the next one, and happy to take some of the actions to lighten the load for you.

**Comment by sarawilcox** [comment]
Done
