### ISSUE TITLE
Follow up action/publish changes after June Style Council meeting

### ISSUE THREAD

**Issue by georginaplatt** [nhsuk/nhsuk-service-manual#1072]
## What

Hold meeting, communicate outcomes and take follow up actions, including publishing any changes

## Dependent on

[Hold June Style Council meeting #1071](https://github.com/nhsuk/nhsuk-service-manual/issues/1071) 

## Done when

- [ ]  Meeting notes written up and shared on NHS.UK content channel first
- [ ]  Meeting notes signed off by clinicans - end of first week in January
- [ ]  Meeting notes shared by email with the mailing list
- [ ]  Amendments made to style guide and published
- [ ]  GitHub updated
- [ ]  Communicate outcomes of June Style Council meeting

**Comment by sarawilcox** [comment]
Not holding a meeting in June. Close.
