### ISSUE TITLE
Guidance on how the service manual team uses GitHub

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#1078]
## What

Create guidance on how the service manual team uses GitHub.

## Why

Research has show that users are not clear about how we use GitHub. Including not being sure about the purpose of each GitHub repo and how we manage our work using GitHub project boards.

## To do

- [x] Draft guidance
- [x] Content review
- [x] Publish guidance on confluence

**Comment by davidhunter08** [comment]
[Draft guidance](https://docs.google.com/document/d/1ReZil50tc3bNZjz66jawfKj1TrPDoaPdeaopLAmSR0o/edit#heading=h.sz6xr3ka00w3)

**Comment by davidhunter08** [comment]
This is ready for a content review @sarawilcox

**Comment by sarawilcox** [comment]
Hi @davidhunter08, I've had a look at this. I wonder if it's worth having a quick follow-up with @lucyh? There are a few questions about how we manage things internally. 

I think we could link to it from the Community and contribution section. 

At some point, we should test this section further. My feeling is that it drops people into the detail too quickly. It may need some sort of intro. To follow up in this epic: [EPIC: Improve Service Manual website contribution user experience](https://github.com/nhsuk/nhsuk-service-manual/issues/993)

**Comment by davidhunter08** [comment]
![image](https://user-images.githubusercontent.com/14331000/113005332-4aa8bd00-916c-11eb-8962-f01dfc931ae2.png)

**Comment by davidhunter08** [comment]
We've decided not to publish this guidance on the service manual at this moment in time and instead consider this guidance as a part of the [community (GitHub) contribution work](https://github.com/nhsuk/nhsuk-service-manual/issues/991).
