### ISSUE TITLE
Workflow for adding features to the design system

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#1080]
## What

Define a workflow for adding features to the design system.

## Why

Having a defined workflow will help the team mutually understand the scope, process and the definition of done at each step. A workflow should tighten up collaboration, speed up delivery, and predictably deliver features that meets user needs.

## To do

- [x] Draft workflow
- [x] Team review
- [x] Document
- [x] Content review

**Comment by davidhunter08** [comment]
[Draft workflow on Miro](https://miro.com/app/board/o9J_kj1NdX4=/?moveToWidget=3074457356368980974&cot=14)

**Comment by davidhunter08** [comment]
Here's the first attempt at creating a workflow:

![workflow for design system features - step by step](https://user-images.githubusercontent.com/14331000/112655464-516fc100-8e48-11eb-8379-ebbbf2a64c92.jpg)

**Comment by davidhunter08** [comment]
[Workflow documented on Google Docs](https://docs.google.com/document/d/1XP-0gDOBaKPF_PaKEfYD2ijYUtuygUTpo7y76eYnK6Y/edit?usp=sharing)

**Comment by davidhunter08** [comment]
@sarawilcox could you please review this '[Workflow: NHS design system features](https://docs.google.com/document/d/1XP-0gDOBaKPF_PaKEfYD2ijYUtuygUTpo7y76eYnK6Y/edit?usp=sharing)' ? Thank you!

**Comment by sarawilcox** [comment]
This is very good, @davidhunter08. I've left some comments, esp around the "Activities". Happy to chat further.

**Comment by davidhunter08** [comment]
This will be a living document that will get updated as learn more about our team processes.
