### ISSUE TITLE
Add Karl to the service manual team page

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#1081]
## What
Add Karl to [service manual team page](https://service-manual.nhs.uk/service-manual-team).

## Why
So our users know they have joined.

## Done when
- [x] Update page via PR
- [x] Ask for review
- [ ] Publish

**Comment by sarawilcox** [comment]
@karlgoldstraw When you do this, would you mind making sure that the dashes are all en-dashes, please? We've got a mix of dashes. 
![Screenshot 2021-04-14 at 10 16 59](https://user-images.githubusercontent.com/45792959/114686410-a8134100-9d0a-11eb-9e24-08eeb1daf032.png)

**Comment by sarawilcox** [comment]
Work done, ready for release.
