### ISSUE TITLE
Review Service Standard Pages

### ISSUE THREAD

**Issue by lucyha** [nhsuk/nhsuk-service-manual#1088]
## What

A review of the existing service standard to ensure it is still up to date, aligns with GDS and all links still active.

## Why

All parts of the service manual need to be reviewed at least annually

## Actions

- [x]  Document pages
- [x] Review Content for potential improvements
- [x] Check all links
- [x] Present findings to team
- [x] Raise bugs as issues
- [x] Raise improvements in backlog
- [x] Review https://github.com/nhsuk/nhsuk-service-manual/issues/797

**Comment by sarawilcox** [comment]
See service manual team Slack: https://nhsuk.slack.com/archives/G01FDHHLQ49/p1618316638082900

**Comment by AJSMITH1512** [comment]
Review completed and document produced high-lighting areas for improvement
[Service Standard Pages Review.docx](https://github.com/nhsuk/nhsuk-service-manual/files/6316318/Service.Standard.Pages.Review.docx)

**Comment by AJSMITH1512** [comment]
Revised Do with related issue review included. 
[Service Standard Pages Review.docx](https://github.com/nhsuk/nhsuk-service-manual/files/6316728/Service.Standard.Pages.Review.docx)
