### ISSUE TITLE
Speak to Sara about content style guide backlog prioritisation

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#1128]
## What

Speak to Sara about the recent content style guide backlog prioritisation exercise that was done with the content design community.

## Why

Learning more about how the content backlog prioritisation exercise will help shape the design system backlog prioritisation exercise.

## EPIC

https://github.com/nhsuk/nhsuk-service-manual/issues/951

## Related work

https://github.com/nhsuk/nhsuk-service-manual/issues/684

## Done when

- [x] Arrange meeting with Sara
- [x] Have meeting with Sara
- [x] Document insights on this GitHub issue

**Comment by nancyhalladay24** [comment]
Notes: 
The prioritisation exercise was conducted during a content style council meeting:
- 1 1/2 hours long
- 30ish people attended 

Agenda: 
- Familiarisation: ensure participants are familiar with the service manual backlog on GitHub 
   - Participants viewed the backlog on their own browser whilst Sara or Tosin spoke through the items
   - Opportunity for participants to mention if there was anything missing 
   - Questions
- Prioritisation: find out the how the participants would prioritise each item in the "proposed" and "to do" columns 
  - Tosin created a Qualtrics survey with all backlog items on
  - Participants were asked to complete the survey by ranking each back log item and also listing their top 5

After the meeting with the content style council Sara and Tosin plotted the highest ranking items on a matrix: 
![IMG_0802](https://user-images.githubusercontent.com/63845568/114708947-ea954780-9d23-11eb-8eb8-b088017700dd.JPG)

Readiness = how much work is already done
Impact = what participants thought had the most impact on our users

Evaluation of process: 
- they struggled to make strategic decisions ie to incorporate business needs
- participants didn't properly understand each ticket
- would work better if participants had longer to review and get familiar with the backlog
- we could have done with exploring 'impact' further in retrospect. What would have a bit impact on the community, in terms of their work and needs? What would have a big impact on our end users - the people we're creating content for?
