### ISSUE TITLE
Speak to product owners / delivery managers at NHS Digital

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#1129]
## What

Speak to product owners / delivery managers at NHS Digital about the design system backlog prioritisation exercise.

## Why

Product owners / delivery managers at NHS Digital should be able to share experiences and insights from other backlog prioritisation exercises. This will help shape the design system backlog prioritisation exercise.

## EPIC

https://github.com/nhsuk/nhsuk-service-manual/issues/951

## Done when

- [x] Identify who to speak to
- [x] [Speak to product owners / delivery managers](https://github.com/nhsuk/service-manual-internal/issues/76)
- [x] [Document and share findings](https://github.com/nhsuk/nhsuk-service-manual/issues/1134)

**Comment by davidhunter08** [comment]
https://uxdesign.cc/feature-prioritization-a089fd0af08

## Overcoming prioritisation biases

### Method 1. Annotated marks

- **Method.** Add real-life descriptions to abstract numeric marks.
- **Strengths.** Clarity in selection criteria makes for easier agreement, less subjectivity, and less time spent on discussions.
- **Limitations.** Developing a meaningful scale needs time; such a scale is contextual and might not be reused for another project.

<img width="1225" alt="Screenshot 2021-04-14 at 11 16 10" src="https://user-images.githubusercontent.com/14331000/114695210-460b0980-9d13-11eb-8abd-3f1c3bb3ad40.png">

<img width="1225" alt="Screenshot 2021-04-14 at 11 16 18" src="https://user-images.githubusercontent.com/14331000/114695217-4905fa00-9d13-11eb-8b02-2b41854de7a6.png">

<img width="1225" alt="Screenshot 2021-04-14 at 11 16 36" src="https://user-images.githubusercontent.com/14331000/114695229-4c00ea80-9d13-11eb-9be0-7d3e02f2002c.png">

**Comment by davidhunter08** [comment]
https://github.com/nhsuk/nhsuk-service-manual/issues/1134#issuecomment-819540242

**Comment by georginaplatt** [comment]
Posted a shout out in the NHS.uk product owners channel.
