### ISSUE TITLE
Research prioritisation methods and tools

### ISSUE THREAD

**Issue by nancyhalladay24** [nhsuk/nhsuk-service-manual#1134]
## What

Use this ticket to collate and discuss different tools and methods we have discovered during the prioritisation discovery.

## Why

After the discovery we can use the resources in this ticket to help us plan our next steps.

## EPIC

#951

## Related work

#684

## Done when

- [x] Prioritisation methods and tools have been documented in the comments
- [x] We have evaluated and discussed each method

**Comment by nancyhalladay24** [comment]
Details on Sara and Tosin's method for prioritising the content backlog can be found in the comments of #1128

**Comment by nancyhalladay24** [comment]
Engineers at Rolls Royce use an [AHP ranking](https://hscic365.sharepoint.com/:x:/s/InternalServiceManual/ETBUT50qP_BJiTUWEsoyFX4BhI4duckZ517WCvnAWv7sWg?e=RypzWr) (Analytic hierarchy process) combined with a [Pugh matrix](https://hscic365.sharepoint.com/:x:/s/InternalServiceManual/ETBUT50qP_BJiTUWEsoyFX4BhI4duckZ517WCvnAWv7sWg?e=RypzWr) to prioritise stages within a project. 

Positives of this method:
- you work as a team
- there is no limit to the amount of criteria/requirements you consider
- the process allows you to proportionality scale each criteria by importance

Negatives: 
- It can take a while to set up 
- We will need to consider who is involved in the process

**Comment by nancyhalladay24** [comment]
@georginaplatt shared a [measurement framework](https://hscic365.sharepoint.com/:f:/s/InternalServiceManual/EqUNH6PzjKhEjOM_mquM2ucBNIi6a1BmXSLMSDnsInVOAg?e=55p20Y) used by pm’s working on transformation products. 

Georgina is going to learn more about this method and update us :)

**Comment by nancyhalladay24** [comment]
@georginaplatt is arranging an intro meeting with Imran, the Community Manager for the GOV.UK Design System. It would be good to try and arrange a follow up meeting with him to discuss how they prioritise their community backlog.

**Comment by davidhunter08** [comment]
https://uxdesign.cc/feature-prioritization-a089fd0af08

## Overcoming prioritisation biases

### Method 1. Annotated marks

- **Method.** Add real-life descriptions to abstract numeric marks.
- **Strengths.** Clarity in selection criteria makes for easier agreement, less subjectivity, and less time spent on discussions.
- **Limitations.** Developing a meaningful scale needs time; such a scale is contextual and might not be reused for another project.

<img width="1225" alt="Screenshot 2021-04-14 at 11 16 10" src="https://user-images.githubusercontent.com/14331000/114695210-460b0980-9d13-11eb-8abd-3f1c3bb3ad40.png">

<img width="1225" alt="Screenshot 2021-04-14 at 11 16 18" src="https://user-images.githubusercontent.com/14331000/114695217-4905fa00-9d13-11eb-8b02-2b41854de7a6.png">

<img width="1225" alt="Screenshot 2021-04-14 at 11 16 36" src="https://user-images.githubusercontent.com/14331000/114695229-4c00ea80-9d13-11eb-9be0-7d3e02f2002c.png">

**Comment by cjforms** [comment]
As you're interested in prioritisation methods, I thought you might be interested in this blog post: https://www.effortmark.co.uk/five-ways-to-choose-which-form-to-fix/

I've written specifically about fixing forms because that's my area, but I thought you might want to think about adapting my five methods like this:

1. Pick the thing you happen to be working on now
2. Pick the thing that has the highest usage
3. Pick the thing that creates the biggest problem for support
4. Pick the thing with the worst conversion rate (quite probably conversion rate doesn't work for service manuals, only here for completeness)
5. Pick the thing with the biggest policy gap

If for no other reason because it's a change of perspective. I've also seen plenty of examples where an example of choice 3 - the thing that was the biggest problem for support - never made it to the top of other prioritisation methods because the support folks weren't on the radar.

**Comment by davidhunter08** [comment]
Thanks @cjforms 🙌

**Comment by georginaplatt** [comment]
> @georginaplatt is arranging an intro meeting with Imran, the Community Manager for the GOV.UK Design System. It would be good to try and arrange a follow up meeting with him to discuss how they prioritise their community backlog.

I think it would be good to go to the meeting on Tuesday with some questions to ask Imran & the design team - the prioritisation exercise would be a good one. Might even be an idea to ask them in advance of the meeting so they are prepared?

**Comment by karlgoldstraw** [comment]
Trilly C has shared insight with me about how he approaches prioritisation:

> Start with an approach that is high level and qualitative, something you can easily compare with the top level goals/mission/purpose of the team. That might then reveal more granular prioritisation needs that necessitate a more quantitative approach - but generally I look to make any ‘obvious’ calls in a qualitative way before resorting to quantitative approaches. Sometimes there won’t be ‘obvious’ calls, at which point I look for a framework that best matches the nature of the prioritisation calls we need to make
