### ISSUE TITLE
Broken Link in Service Standard page

### ISSUE THREAD

**Issue by AJSMITH1512** [nhsuk/nhsuk-service-manual#1136]
Page: Make sure everyone can use the service (5)

Broken Link – Health Literacy – needs the last / removed from title

Guidance
NHS digital service manual
Accessibility: how to make digital services in the NHS work for everyone
**Health literacy**
Inclusive language

**Comment by chrimesdev** [comment]
https://github.com/nhsuk/nhsuk-service-manual/pull/1234
