### ISSUE TITLE
About the NHS Service Standard - Proposed Changes

### ISSUE THREAD

**Issue by AJSMITH1512** [nhsuk/nhsuk-service-manual#1139]
Proposed Change 1:
 
Is the paragraph below still accurate given the actions of the NHSx Assessment Team?

A few NHS teams are assessed against the GOV.UK service standard. They have to meet all 14 points in it. Other NHS teams follow the GOV.UK service standard because it's best practice.

Is it that if assessed they are presently assessed against the GOV.UK service standard?

Proposed Change 2
What is the difference about the NHS?

•	multi-disciplinary teams are not common in the NHS - by "multi-disciplinary" we mean teams made up of product and delivery managers, designers, developers, user researchers and content designers
•	NHS delivery teams are less likely to be practising user-centred design and agile service delivery

Could this be framed more around not as experienced in working in this manner? We are seeing a general move towards this way of working, can we move from the negative to the positive?

**Comment by sarawilcox** [comment]
Related issue: [Use agile ways of working](https://github.com/nhsuk/nhsuk-service-manual/issues/1141)

**Comment by sarawilcox** [comment]
Thanks @AJSMITH1512. 

@georginaplatt I'm tempted to put the service manual tweaks into next sprint backlog. These various changes aren't a huge amount of work. It would be good to finish off the work Adrian started and, if I do them all in one go, we can then tell people (including NHSX standards and assurance) that we've made some small updates to the guidance around the standard. We can also mark the service standard guidance pages as having had their yearly review. What do you think?

**Comment by georginaplatt** [comment]
Sounds like quick wins and valuable - agree is a good idea.

**Comment by sarawilcox** [comment]
Hi @georginaplatt, I'm looking at Adrian's 1st point above.  See [this service standard page](https://service-manual.nhs.uk/service-standard/about).
It says: 

> A few NHS teams are assessed against the GOV.UK service standard. They have to meet all 14 points in it. Other NHS teams follow the GOV.UK service standard because it's best practice.

NHSX wrote this in an email a little while back:

> It very much depends on who the commission is from and what the scope of the website is. If it's an NHSE/I commission and the website is transactional (where transaction = any information exchange, which it looks like it is as it has a login and an order form), then it will need spend approval and a service assessment. NHSX assess everything under 100,000 transactions in a year - mainly clinician facing NHS services as well as specialist services from arms length bodies such as PHE. 

Note: GOV.UK assesses transactions over 100,000 a year.
The email continues:

> If it's been commissioned [locally], then this would be out of scope for assessment as it would be considered a local service. That said, we are currently working on local standards and our assurance offering - so happy to chat if you are interested in local level assurance, this sounds like an excellent case for us to learn from.

I'm thinking of changing the wording in the service standard to say: 

> Some NHS services go through a service assessment. GOV.UK assesses services which have over 100,000 transactions a year. NHSX assesses some NHS services which have less than 100,000 transactions a year. Teams which have an assessment have to meet all 14 points in the GOV.UK service standard. Other NHS teams follow the GOV.UK service standard because it's best practice.

**Comment by sarawilcox** [comment]
Re Adrian's proposed change 2, I've made the wording less negative in a branch called servicestandard. I'll publish several changes to the service standard at the same time.

**Comment by sarawilcox** [comment]
Done in servicestandard branch.
