### ISSUE TITLE
Use agile ways of working - proposed change

### ISSUE THREAD

**Issue by AJSMITH1512** [nhsuk/nhsuk-service-manual#1141]
Should **agile** have a capital are we referring to Agile the Methodology?

Otherwise, is there an alternative word to agile to avoid the confusion?

**Comment by sarawilcox** [comment]
I think we should leave it lower case to fit our content style and keep in line with GOV.UK. But people do sometimes think "Oh, we're being agile", without realising we're talking about a methodology. 

Would it help to change the standard on [this page](https://service-manual.nhs.uk/service-standard) from this:

> **Use agile ways of working**
> Make sure that the team can deliver quickly and adapt to meet users' needs.
> 
> Resource them flexibly.

To this:

> **Use agile ways of working**
> Make sure that the team can deliver quickly and adapt to meet users' needs.
> 
> Use agile principles, tools and governance and resource the team flexibly.

That would also appear at the top of this page: https://service-manual.nhs.uk/service-standard/7-use-agile-ways-of-working

I could also change this link on the guidance page: [Agile delivery](https://www.gov.uk/service-manual/agile-delivery) to say:
[Agile delivery: how to work in an agile way: principles, tools and governance](https://www.gov.uk/service-manual/agile-delivery).

**Comment by sarawilcox** [comment]
Done. In branch servicestandard. To be released soon.
