### ISSUE TITLE
Iterate and improve frequently - Proposed change

### ISSUE THREAD

**Issue by AJSMITH1512** [nhsuk/nhsuk-service-manual#1142]
May not be the team iterating but a maintenance team, if major changes do we start a new team working in the service?

**Comment by sarawilcox** [comment]
@georginaplatt, with this one, I've added a bit of info from the GOV.UK service standard point 11, which seems to address Adrian's point. 

![Screenshot 2021-06-24 at 12 31 09](https://user-images.githubusercontent.com/45792959/123255750-1bde8080-d4e8-11eb-8ec5-5ecd5f5ee011.png)

I'm also noting these changes in this presentation: https://hscic365-my.sharepoint.com/personal/sawi10_hscic_gov_uk/_layouts/15/doc.aspx?sourcedoc={78ae6458-2d81-4ccf-a550-3112b2f322e1}&action=edit

**Comment by sarawilcox** [comment]
Are you OK with this, @georginaplatt? Can I close the issue?

**Comment by sarawilcox** [comment]
Done in servicestandard branch
