### ISSUE TITLE
Respect and protect users confidentiality and privacy - proposed change

### ISSUE THREAD

**Issue by AJSMITH1512** [nhsuk/nhsuk-service-manual#1143]
Under the section: What you should do

Suggest considering adding:

Ensure you have a relevant privacy policy in place at the launch of the service. Major public facing services should also have a Data Protection Impact Assessment (DPIA) undertaken and published.

**Comment by sarawilcox** [comment]
Done. On servicestandard branch.

**Comment by sarawilcox** [comment]
Done in servicestandard branch
