### ISSUE TITLE
Talk with UCD leads about participatory methods training

### ISSUE THREAD

**Issue by amyj2110** [nhsuk/nhsuk-service-manual#1146]
## What

We need to speak to the UCD leads to assess the appetite for participatory methods training, and find out what the process would be to do this.

## Why

We need to make sure no one else is currently trying to do this, and how we can be involved.

## Done when

- [x] Booked in a chat with Dean Vipond, Eva Lake, Harriet Messenger, and Nancy Willacy
- [x] Had the chat and know next steps

**Comment by sarawilcox** [comment]
When you talk with Eva, it's worth letting her know that the content people working on the inclusive content checklist/principles are recommending that teams consider co-designing their content. I wonder if it's helpful if I share where we've got to with her before you meet?

**Comment by amyj2110** [comment]
UCD leads are keen. We will go away, find some potential training providers and resources and come back to them to get things rolling.
