### ISSUE TITLE
Talk to HR about their inclusion work

### ISSUE THREAD

**Issue by amyj2110** [nhsuk/nhsuk-service-manual#1147]
## What

Organise a meeting with HR (Sonia Bewley) to talk to them about their inclusion work.

## Why

It would be good to know about HR's initiatives and if they cross over with anything we want to do. Can we combine and help each other?

## Done when

- [x] Organise meeting with Sonia Bewley and any other HR representatives
- [x] Had meeting and documented next steps and information learned

**Comment by EllenDoyle** [comment]
Message sent to Sonia Bewley, requesting a discussion with Amy and Nancy - 21.4.21

**Comment by EllenDoyle** [comment]
Meeting booked for 29/4
