### ISSUE TITLE
Chase Becky Smith about inclusion next steps

### ISSUE THREAD

**Issue by amyj2110** [nhsuk/nhsuk-service-manual#1150]
## What

After our inclusion presentation, Becky Smith seemed to take away some actions. We need to chase on these and see if there's anything we can do or work on from this. Becky is also one of our more senior contacts we've presented to, she might be able to help us figure out how we are going to approach this work after Ian leaves.

## Why

See above.

## Done when

- [ ] Spoken to Becky and understood her next steps or actions
- [ ] Documented any next steps or actions we as a team can help with or do

**Comment by EllenDoyle** [comment]
@georginaplatt - I don't know Becky, so can you please introduce me? Also, we need to formulate questions to put to her in advance.

**Comment by georginaplatt** [comment]
Closing this - moving here: - https://github.com/nhsuk/service-manual-internal/issues/80
