### ISSUE TITLE
Write a job description for an inclusion lead at NHS Digital

### ISSUE THREAD

**Issue by nancyhalladay24** [nhsuk/nhsuk-service-manual#1151]
## What

Decide what responsibilities, skills and qualifications we would require of someone who would be hired to lead inclusion at NHS Digital.

## Why

To feedback to senior leaders the competencies we would expect from someone leading inclusion.

## Done when

 - [ ] We have met to discuss what would be required 
 - [ ] We have written the job description
 - [ ] We have discussed this with senior leaders

**Comment by amyj2110** [comment]
[Job description for Snook's "Accessibility and inclusive design lead"](a11yjobs.com/jobs/MRk0v-accessibility-and-inclusive-design-lead-snook)
[Job description for HS2 "Inclusive design lead"](https://www.evenbreak.co.uk/en/jobs/inclusive-design-lead/4170#) 
[Job description for Test & Trace "Head of Inclusive Design"](https://www.civilservicejobs.service.gov.uk/csr/index.cgi?SID=dXNlcnNlYXJjaGNvbnRleHQ9MTI1ODAyNDYzJmpvYmxpc3Rfdmlld192YWM9MTcxNjc2MiZwYWdlYWN0aW9uPXZpZXd2YWNieWpvYmxpc3Qmb3duZXJ0eXBlPWZhaXImc2VhcmNoX3NsaWNlX2N1cnJlbnQ9MSZvd25lcj01MDcwMDAwJmNzb3VyY2U9Y3Nmc2VhcmNoJnBhZ2VjbGFzcz1Kb2JzJnJlcXNpZz0xNjE5MDE0MzE3LTZhZWI5MmEyZDBiYjRmMzk0M2VhYjQ3NDY3YTYzZjA1ODYzODUxYzI=)
[Job description for Twitch "Head of Accessibility and Inclusive Design"](https://angel.co/company/twitch/jobs/1002410-head-of-accessibility-inclusive-design)
[Job description for Microsoft "Director of Inclusive Design"](https://www.a11yjobs.com/jobs/d7D0Y-director-inclusive-design-accessibility-microsoft)
[Job description for TfL "Inclusive Design Advisor"](https://www.bridgeofhope.careers/jobs/inclusive-design-adviser)

**Comment by sarawilcox** [comment]
I think this is being taken forward elsewhere, isn't it? Should we close this issue down, @georginaplatt @amyj2110 ?

**Comment by sarawilcox** [comment]
Inclusion Lead for NHSE Central UCD team has been appointed.
