### ISSUE TITLE
Plan how we want to co-create the guidance and resources

### ISSUE THREAD

**Issue by ericlamarca** [nhsuk/nhsuk-service-manual#1154]
## What

We need a plan for how we start making stuff and who do we need to involve at each point.

## Why

So we can:

- keep momentum after the analysis
- use an inclusive approach.

## Done when

- [x] Drafted a plan: decide on appropriate activities; who needs to be involved and when is best to work with them.
- [x] Shared with team
- [x] Refined plan
- [x] Organise sessions with participants

**Comment by nancyhalladay24** [comment]
We have decided that it would be good to work with user research and the inclusion collective for one of our problem statements, "Recruiting and doing user research with seldom heard groups is difficult".
POA for this group:
- Share our ideation work so far
- Get high level feedback from both groups
- Organise an ideation session to find a way to solve this problem together
