### ISSUE TITLE
Actions from missing component audit

### ISSUE THREAD

**Issue by chrimesdev** [nhsuk/nhsuk-service-manual#1157]
Proceed with any actions from the audit of components missing from the NHS digital service manual (but exist in the NHS.UK frontend)

https://github.com/nhsuk/nhsuk-service-manual/issues/711

## Missing components

The missing components from the service manual that are in the NHS.UK frontend include the:
- [Hero banner](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/150)
- [Nav A-Z](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/153)
- [List panel](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/154)

### Hero banner

https://github.com/nhsuk/nhsuk-service-manual/issues/884

[Outcomes from a design working group for the Hero banner](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/150#issuecomment-545365289):

> The Design Working Group discussed this issue on 21/10/19. Feedback as follows:
> 
> - The hero banner is used commonly, but there has been no research into potential problems with different websites looking similar
> - The intent of the hero banner should be for hub pages, not lower level pages.
> - Further research of exploring risks need to be outlined before moving to develop guidance.
> - Check with NHS Identitiy Guidelines

### Nav A-Z

[Outcomes from a design working group for the Nav A-Z](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/153):

> The Design Working Group discussed this issue on 21/10/19. Feedback as follows:
> - There is currently no evidence of the Nav A-Z being used on its own.
> - Check with the IA team in NHS.UK regarding possible plans to change this pattern on the NHS website.
> - Design working group suggested that the component is removed from the frontend library and we utilise the A to Z pattern in the service manual, not add a component

### List panel

https://github.com/nhsuk/nhsuk-service-manual/issues/885

> Guidance for the list panel already exists on the service manual as part of the [A to Z pattern](https://service-manual.nhs.uk/design-system/patterns/a-to-z-page). The NHS website always uses it with the [Nav A-Z](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/153) component so there might be no need to document it as a single component on the service manual.

> The list panel could also be a variant of a [Card](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/159).

https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/154#issuecomment-529868330

**Comment by AdamChrimes** [comment]
Hero - research, design and develop improvements to the Hero component and add to the NHS digital service manual
Nav A-Z - could this be achieved with utility classes along with typography (list) styles then removed as an individual component?
List panel - could this be achieved by the Card component?

**Comment by davidhunter08** [comment]
## To do

- [ ] Meeting to plan next steps for each component
- [ ] Create issue for each component (listing agreed next steps)

**Comment by davidhunter08** [comment]
Meeting scheduled for Monday 10th May 11:30-12:30am

**Comment by davidhunter08** [comment]
[A proposal for removing the list panel component](http://nhsuk-design-system-testing.herokuapp.com/list-panel):

![image](https://user-images.githubusercontent.com/14331000/117340264-9dc30d80-ae98-11eb-9340-1bd2fd4f268c.png)

**Comment by davidhunter08** [comment]
[Proposal for removing the Nav A-Z component](http://nhsuk-design-system-testing.herokuapp.com/nav-a-z):

![image](https://user-images.githubusercontent.com/14331000/117346720-0a8dd600-aea0-11eb-9925-3d1cf084ab5e.png)

**Comment by davidhunter08** [comment]
Myself, Nancy, Adam, Dom and Sara met today (Mon 10 May, 2021) and planned the next steps for the missing components, including:

- [Remove the Nav A-Z and List panel components from frontend](https://github.com/nhsuk/nhsuk-service-manual/issues/1186)
- [Redesign Hero banner component and add guidance to the service manual](https://github.com/nhsuk/nhsuk-service-manual/issues/1187)
