### ISSUE TITLE
Test the inclusive content principles and checklist with the content profession

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk-service-manual#1170]
We now have a [draft](https://drive.google.com/file/d/1RmWc8n_kMXcHrwnhFeWps_08k9BBDRSB/view?usp=sharing). 

We'd like to find out:
- if it will help content designers
- if they understand it and could apply it
- any other feedback

@amyj2110 and @Indu-Kaila, for information. I've marked it as awaiting triage. Something to consider pulling into an upcoming sprint.

**Comment by Indu-Kaila** [comment]
Here's the draft discussion guide for comment https://hscic365-my.sharepoint.com/:w:/r/personal/inka2_hscic_gov_uk/Documents/Service%20manual%20UR%20Draft%20docs%20for%20comment%20(Indu)/Draft%20Discussion%20Guide%20-%20Contribution_ServiceManual_260421.docx?d=w1373fda1b7eb49389b24f4cf5ebbc896&csf=1&web=1&e=rrhzvb

**Comment by sarawilcox** [comment]
Should I close this, @amyj2110, given that Eric and you have integrated it into the inclusion guidance? What are the next steps in terms of the inclusion guidance?

**Comment by sarawilcox** [comment]
@amyj2110 @nancyhalladay24, I think I can close this, can't I?
