### ISSUE TITLE
Meeting to finalise care card guidance

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#1175]
## What

Have a meeting with contributors to the guidance to discuss outstanding issues.

## Why

We need to agree on the outstanding issues before sending it to the design system working group.

## EPIC

https://github.com/nhsuk/nhsuk-service-manual/issues/880

## To do

- [x] Send meeting invites
- [x] Prep for meeting
- [x] Facilitate meeting
- [ ] Document and share meeting outcomes

## Next steps

Prepare care card guidance for the design system working group

**Comment by davidhunter08** [comment]
Meeting is scheduled for 7th May 2021 (10-10:45am)

**Comment by sarawilcox** [comment]
Shall we close this issue, @davidhunter08 ? 

I'm going to look at the care card guidance this morning.

**Comment by davidhunter08** [comment]
### Meeting actions

- Update the guidance based on the decisions made in the meeting - Sara + Dave
- Share updated guidance with the group for final thoughts - Sara
- Add guidance to service manual (staging) - Dave
