### ISSUE TITLE
Prepare care card guidance for the design system working group

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#1176]
## What

We need to prepare care card guidance for the design system working group.

## Why

So we can send the guidance to the design system working group to be reviewed.

## EPIC

https://github.com/nhsuk/nhsuk-service-manual/issues/880

## To do

- [x] Add guidance to a branch in the service manual - Dave
- [x] Content review - Sara
- [x] Host on a URL

## Next steps

Update examples after frontend release.

**Comment by davidhunter08** [comment]
https://github.com/nhsuk/nhsuk-service-manual/pull/1220

![image](https://user-images.githubusercontent.com/14331000/119359209-4a76fa80-bca1-11eb-99f3-77b515b20eca.png)

**Comment by davidhunter08** [comment]
Ready to be reviewed @sarawilcox

**Comment by sarawilcox** [comment]
Hi @davidhunter08, I'm having a look at this. Just wondering how we will help people find this (and other patterns). How will they know if it's a pattern or a component? What if they're looking for "care card" or "NHS number" or "review date" in components? 
Looks like search works for NHS number and review date. 
I wonder if this is something:
- GDS can advise on (unless you've spoken with them already)?
- we should use test?

**Comment by sarawilcox** [comment]
A couple of things I can't work out. The standalone care card examples are stretching across the full width of the screen. 
![Screenshot 2021-06-01 at 09 36 38](https://user-images.githubusercontent.com/45792959/120293276-fe3d4300-c2bc-11eb-893d-d2ab60803351.png)

**Comment by davidhunter08** [comment]
> Hi @davidhunter08, I'm having a look at this. Just wondering how we will help people find this (and other patterns). How will they know if it's a pattern or a component? What if they're looking for "care card" or "NHS number" or "review date" in components?
> Looks like search works for NHS number and review date.
> I wonder if this is something:
> 
> * GDS can advise on (unless you've spoken with them already)?
> * we should use test?

As well as users using the main menu and side navigation to find the patterns, other ways to help people users find the patterns include cross linking and search.

### Cross linking

Add a link to the pattern from other pages in the service manual. 

#### Examples

We could link to this pattern from the [card component](https://service-manual.nhs.uk/design-system/components/card) page.

We already link to NHS number pattern from the [A to Z of health writing](https://service-manual.nhs.uk/content/a-to-z-of-nhs-health-writing#NHS-number) and but we could also link to it from the [text input component](https://service-manual.nhs.uk/design-system/components/text-input#asking-for-numbers).

#### Search

Make sure the pattern appears in the search using key search terms.

#### Examples

Searching for "Care card":

<img width="1183" alt="Screenshot 2021-06-01 at 09 44 41" src="https://user-images.githubusercontent.com/14331000/120318796-2f773c80-c2d8-11eb-9f5f-55689480fd9d.png">

Searching for "NHS number":

<img width="1202" alt="Screenshot 2021-06-01 at 09 37 57" src="https://user-images.githubusercontent.com/14331000/120318919-559cdc80-c2d8-11eb-8146-99828a65b023.png">

### User research

Tree tests and usability testing will help us validate our thinking. Something we can look at with @Indu-Kaila?
