### ISSUE TITLE
Kick off inclusive content principles research

### ISSUE THREAD

**Issue by amyj2110** [nhsuk/nhsuk-service-manual#1180]
## What

We need to understand the research to be done on the inclusive content principles.

## Why

So we can:

- write the research questions
- write the hypotheses
- understand what we want to learn by doing this research

## Done when

- [x] Draft research questions
- [x] Draft hypotheses

**Comment by sarawilcox** [comment]
Would be good to invite:
- Rich Kelly
- Rhiannon Smith
- Chloe Philippou
as they've helped draft the doc.

**Comment by amyj2110** [comment]
### Research questions
- Do people understand the principles?
- Do people find the principles useful?
- Is there something missing that people would find useful?
- How do people feel about the amount of principles? Are they overwhelming?
- Are the examples provided useful? Do they make sense to people?
- How do people think they compare to the design principles?
- In what situations could people see themselves using these principles?
- How do people external to NHS Digital feel about them?
- What do people think "inclusive content" is? What does it cover and how does that work for them?

### Research plan
- Invite people, both internal and external to NHS Digital, to give feedback on the principles in a session
- Invite people to use version 0 of the principles for approx. 2 weeks and feed back to us (similar to a diary study)

### Participants
- People who are creating content in a health context (content designers, internal and external to NHS Digital)
- People who are managing teams creating this content (product and delivery managers)
- Sara, Rich, Chloe and Rhiannon to help with finding people to recruit

**Comment by sarawilcox** [comment]
Hi @amyj2110, might be worth seeing how they respond to the idea of a checklist versus principles - and/or.
