### ISSUE TITLE
Test our content on writing inclusively about skin symptoms - once it's live

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk-service-manual#1183]
We expect to publish some new guidance on writing about skin symptoms in the content style guide soon. [GitHub issue](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/181)

We would normally test new guidance before publishing it, but we aren't aware of any other NHS Digital, PHE or DHSC teams working on skin content at the moment. I suggest that, once the new guidance live, we see if we can find any NHS trusts or charities that produce skin content, and ask them for feedback or test with them.

@amyj2110 for info.

**Comment by sarawilcox** [comment]
Hi @amyj2110, Rhiannon said the following about testing the skin symptoms guidance when we publish it.

> Do you tend to put any links to surveys in the service manual? Could we ask a few questions like if it's helpful, anything confusing, etc?
> In the near future skin symptoms reviews will be going to all content designers, not just mission team 1 designers. So it could be good to do some UR sessions and get some CDs to review an MVR topic (or part of the topic) and ask them to use the guidance and observe and see what is helpful and what's confusing etc? But I'm sure URs will have some ideas about how to test it. Would a UR from the service manual team be able to do this or is this something I should talk to Michelle in mission team 1 about?

**Comment by sarawilcox** [comment]
Some questions: 
- how do people find this page? site search, browsing, via the A to Z?
- does this page contain the right amount of info about research insights? 
- does the page structure work?
- do people use the left hand nav?

**Comment by sarawilcox** [comment]
@amyj2110 It is unlikely now that NHS.UK content designers will apply the skin symptoms guidance soon, because they're too tied up in MVR work. So MT1 is likely to pick up more skin symptoms work.

Given that we won't be able to test the guidance internally in the near future, I'm wondering whether we might be able to find some external teams (charities or hospital trusts) that produce skin symptom content, that we could do a bit of UR with. 

MT1 may be able to advise on organisations to contact. Some examples might be:
- the British Association of Dermatologists (who're doing some good work in this area - we link to them from the guidance) and their Skin Support website
- the Vitiligo Society
- the Psoriasis Association
The Patient Information Forum may be able to put out a call for people to test our guidance.

**Comment by sarawilcox** [comment]
Some of our skin conditions content and last reviewer:

- Rubella - Mark R
- Measles - Steven S
- Vitiligo - Chloe
- Atopic eczema - Laura

**Comment by sarawilcox** [comment]
@Indu-Kaila, for info. I'll try and catch up with you later. This is the page in question: https://service-manual.nhs.uk/content/make-content-about-skin-symptoms-more-inclusive.

**Comment by Indu-Kaila** [comment]
Met with @sarawilcox (30/0621) about the background as to the creation of this page and re this page needs ur testing: https://service-manual.nhs.uk/content/make-content-about-skin-symptoms-more-inclusive.

**Comment by Indu-Kaila** [comment]
Meeting arranged to meet with the Mission team 1 Content designers on 06/07/21. Will be planning the user research. Please refer to issue #1269

**Comment by Indu-Kaila** [comment]
Done
[Skin Symptoms Guidance Analysis Summary Matrix_090821.docx](https://github.com/nhsuk/nhsuk-service-manual/files/6960237/Skin.Symptoms.Guidance.Analysis.Summary.Matrix_090821.docx)
