### ISSUE TITLE
Create a list of all services using the service manual

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#1185]
## What

We need to create a list of services using the service manual.

## Why

So that we can understand who is using the service manual.

## Related to

https://github.com/nhsuk/nhsuk-service-manual/issues/1162

## Done when

- [ ] We have had a meeting to plan the list
- [ ] We have created and shared a list
- [x] #1455

**Comment by sarawilcox** [comment]
Just recording one here: https://www.madetech.com/blog/connecting-loved-ones-building-the-nhs-book-a-virtual-visit-service-in-48-hours/

**Comment by davidhunter08** [comment]
I began a list of [services using the frontend](https://docs.google.com/spreadsheets/d/1U6LuHdC_SO85mIVFwAUfRBQQyPSPC9WG3yrJ1WwjwBE/edit#gid=0) last year, based on the [GitHub dependency graph](https://github.com/nhsuk/nhsuk-frontend/network/dependents) — but needs updating

**Comment by georginaplatt** [comment]
I've started this v.rough draft [Mural ](https://app.mural.co/t/nhsdigital8118/m/nhsdigital8118/1631807320126/9c367d34f2c7a0fcea186b13b703da346899e684?sender=u49cdb57d15bbca0d3e2f4640)
