### ISSUE TITLE
Implement trailing slash redirects

### ISSUE THREAD

**Issue by mikemonteith** [nhsuk/nhsuk-service-manual#119]
We need to decide if our URLs should always end in a trailing slash or never end in a trailing slash.

- Implement redirects to append or remove the slash.
- Make sure our internal links are using the correct URL format.

**Comment by AdamChrimes** [comment]
NHS.UK pages all have a trailing slash if that affects the decision to have or not to have.

**Comment by AdamChrimes** [comment]
I think this has been less of an issue since we changed around our folder structure into sections. Haven't faced it since Feburary, so going to close this issue.
