### ISSUE TITLE
Prioritise potential user research guidance with user researchers

### ISSUE THREAD

**Issue by ericlamarca** [nhsuk/nhsuk-service-manual#1207]
## What

We need to align on the ideas we brainstormed with user researchers.

## Why

So we can agree on what is already being worked on, and what makes sense to work on next.

## Done when
We have:
- [x] booked sessions with user researchers
- [x] done sessions with user researchers
- [x] agreed next steps

**Comment by karlgoldstraw** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Feature 1](https://trello.com/c/wMY5tvJL/1-feature-1)

**Comment by karlgoldstraw** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Iclusion lab](https://trello.com/c/WXDu1ECx/6-iclusion-lab)
