### ISSUE TITLE
Update 'Backlog of components and patterns' page

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#1222]
## What

We need to review and update the '[Backlog of components and patterns](https://service-manual.nhs.uk/community-and-contribution/backlog-of-components-and-patterns)' page on the service manual and [community backlog GitHub documentation](https://github.com/nhsuk/nhsuk-service-manual-community-backlog).

## Why

Because we know that:
- the current page doesn't include information on the other backlogs (content style guide and ways of working)
- the table of components and patterns isn't used and is also extra work for us to maintain
- users are not clear about how to contribute to the backlog
- some users find moving from the service manual to GitHub a bit jarring (not what they expected)
- some users do not know the benefits of using the backlog eg: sharing knowledge between teams
- some users are not sure when to contribute to the backlog

## Related to

- [Create new issue templates by contribution type #996](https://github.com/nhsuk/nhsuk-service-manual/issues/996)
- [Community contribution EPIC](https://github.com/nhsuk/nhsuk-service-manual/issues/685)

## Done when

- [x] Draft new guidance
- [x] Prototype guidance
- [ ] Content review
- [ ] Test guidance
- [ ] Publish guidance

**Comment by davidhunter08** [comment]
[Draft guidance on Google Docs](https://docs.google.com/document/d/1rSa6syKVDzmwWO7exZ0Nm4KJwDDT5f8-4TN_WfXiiGI/edit?usp=sharing)

**Comment by davidhunter08** [comment]
## Design hypotheses

**If we** clearly set expectations of the backlog living on GitHub
**Then** users won't find it a jarring experience moving from the service manual to GitHub

**If we** explain what the purpose of the backlog, along with the benefits
**Then** users will have a better understanding of why they should be using the backlog

**If we** list the ways to contribute with links to specific issue templates
**Then** users will understand how they can contribute to the backlog

**Comment by davidhunter08** [comment]
## Backlog page

### Current design

![community-backlog-old](https://user-images.githubusercontent.com/14331000/119504492-ecf7b200-bd63-11eb-926b-90e46088d99f.png)

### New design (prototype)

![community-backlog-new](https://user-images.githubusercontent.com/14331000/119504538-f6811a00-bd63-11eb-89fc-abdd4875ca36.png)

**Comment by henocookie** [comment]
I really like the look of the prototype so far, nice work 🙌🏻 

I wonder if the "Ways to contribute" section could be higher on the page, perhaps as more and more people become accustomed to using GitHub to contribute over time.

A second question would be are the "Propose a component or pattern" and "Develop a component or pattern" pages needed if the issue templates and guidance are on this proposed "Community backlog page"? I think possibly not but might be worth testing with users.

**Comment by davidhunter08** [comment]
The latest version of the contribution guidance prototype can be found on https://github.com/nhsuk/nhsuk-service-manual/pull/1230.

**Comment by davidhunter08** [comment]
Closing issue as it has been superseded by https://github.com/nhsuk/nhsuk-service-manual/issues/1248
