### ISSUE TITLE
Update image guidance after Style Council

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk-service-manual#1231]
We agreed to update the images guidance at the last Style Council meeting.
I'm going to put this through separately from other Style Council meeting updates, as I want to check it with @davidhunter08 before publishing.

**Comment by sarawilcox** [comment]
[Images issue in backlog](https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/28)

**Comment by sarawilcox** [comment]
PR: https://github.com/nhsuk/nhsuk-service-manual/pull/1243

**Comment by davidhunter08** [comment]
> PR: #1243

PR has been merged
