### ISSUE TITLE
Iterate 'share feedback' contribution section

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#1261]
## What

We need to iterate the 'feedback' section that lives on the guidance pages.

## Why

In usability testing we found that:

- Action link design and label was understood by the majority of the participants
- In every case where participants found alternative headers, the ‘new amended’ header ‘Would you like to contribute to this guidance?’ was understandable unlike the use of 'Have you tested these styles?' which was criticised ('tested' word did not make sense)
- There was some confusion by some external participants that ‘research’ findings would be expected rather than a route to add comments
- It was pointed out that there is a difference between sharing and contributing content
- The use of 'Have you tested these styles?' was criticised ('tested' word did not make sense to users)
- Confusion as to the route for giving positive feedback
- GitHub was found to not be widely used by people in non Designer roles and the current GitHub page (you are taken to when clicking on the action link) does not explain how to use GitHub sufficiently. No guidance on how to use GitHub in the action link section area(s)
- Even internal users who contribute need reminding on how to use GitHub

## More info

Tested design:

![image](https://user-images.githubusercontent.com/14331000/124443039-3da3f700-dd75-11eb-8a61-d97f99e0dcff.png)

[Design hypotheses](https://github.com/nhsuk/nhsuk-service-manual/issues/1000#issuecomment-808127439)

## Done when

- [x] Iterated the design based on the user research
- [ ] Content review
- [ ] Code review
- [ ] Published

**Comment by davidhunter08** [comment]
## Proposed design iterations

Design system:

![Screenshot 2021-07-05 at 09 45 57](https://user-images.githubusercontent.com/14331000/124443832-ece0ce00-dd75-11eb-9e85-7eb69b32625e.png)

Service standard:

![Screenshot 2021-07-05 at 09 52 35](https://user-images.githubusercontent.com/14331000/124444779-dbe48c80-dd76-11eb-8834-4909572c1c19.png)

Content style guide:

![Screenshot 2021-07-05 at 09 53 18](https://user-images.githubusercontent.com/14331000/124444823-e6068b00-dd76-11eb-9a0d-3d306257e856.png)

### Design hypotheses

**If** we change the heading and action to 'feedback or share insights'
**Then** it will be clearer to users about what we are asking them to do

**If** we keep the heading 'feedback or share insights' consistent across all pages/sections
**Then** users will become familiar with what the section is for

**If** we add a link to 'how to feedback or share insights' guidance 
**Then** users who haven't used GitHub before will gain a better understanding of how to use it

**If** we add a link to 'how to feedback or share insights' guidance 
**Then** users who need reminding how to use GitHub will have a way to remind themselves

**Comment by davidhunter08** [comment]
## Code improvements

There could also be some improvements made to the 'contact panel' code.

Current code:

```
<h2 class="nhsuk-u-padding-top-4">{% if subSection === "Styles" %}Have you tested these styles{% endif %}{% if subSection === "Components" %}Have you tested this component{% endif %}{% if subSection === "Patterns" %}Have you tested this pattern{% endif %}{% if pageSection === "Content style guide" or pageSection === "Accessibility" %}Would you like to contribute to this guidance{% endif %}{% if pageSection === "NHS service standard" %}Would you like to contribute to the NHS service standard{% endif %}?</h2>
{% if subSection === "Styles" or subSection === "Components" or subSection === "Patterns" %}

<p>If so, please share your research findings and let us know how it has worked for you. This will help us improve it for everyone.</p>
<p>Before you start, you will need a <a href="https://github.com/join?source=login">GitHub account</a>. It's an open forum where we collect feedback.</p>
{% endif %}
{% if pageSection === "Content style guide" or pageSection === "Accessibility" %}

<p>Please let us know how this has worked for you and, in particular, if you have research findings to share. This will help us improve it for everyone.</p>
<p>Before you start, you will need a <a href="https://github.com/join?source=login">GitHub account</a>. It's an open forum where we collect feedback.</p>
{% endif %}

{% if pageSection === "NHS service standard"%}
<p>Please let us know how this has worked for you and, in particular, if you have gone through a GDS or NHSX service assessment or peer review. This will help us improve it for everyone.</p>
<p>Before you start, you will need a <a href="https://github.com/join?source=login">GitHub account</a>. It's an open forum where we collect feedback.</p>
{% endif %}

<div class="nhsuk-action-link">
  <a class="nhsuk-action-link__link" href="https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/{{backlog_issue_id}}">
    <svg class="nhsuk-icon nhsuk-icon__arrow-right-circle" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" aria-hidden="true">
      <path d="M0 0h24v24H0z" fill="none"></path>
      <path d="M12 2a10 10 0 0 0-9.95 9h11.64L9.74 7.05a1 1 0 0 1 1.41-1.41l5.66 5.65a1 1 0 0 1 0 1.42l-5.66 5.65a1 1 0 0 1-1.41 0 1 1 0 0 1 0-1.41L13.69 13H2.05A10 10 0 1 0 12 2z"></path>
    </svg>
    <span class="nhsuk-action-link__text">Share your findings on GitHub</span>
  </a>
</div>
<p>If you have any questions, you can <a href="https://service-manual.nhs.uk/slack">message us on Slack</a>. You will need a Slack account if you do not have one. Or you can <a href="mailto:service-manual@nhs.net">contact us by email</a>.

</p>
```

Proposed code changes:

```
<h2 class="nhsuk-u-padding-top-4">Feedback or share insights</h2>
{% if subSection === "Styles" or subSection === "Components" or subSection === "Patterns" or pageSection === "Content style guide" or pageSection === "Accessibility" %}
<p>Please feedback or share insights to help us improve this guidance for everyone.</p>
{% endif %}

{% if pageSection === "NHS service standard"%}
<p>Please feedback or share insights, in particular, if you have gone through a GDS or NHSX service assessment or peer review. This will help us improve it for everyone.</p>
{% endif %}

<p>All you need is a <a href="https://github.com/join?source=login">public GitHub account</a> to contribute. Read more about <a href="/community-and-contribution/feedback-or-share-insights">how to feedback or share insights</a>.</p>

<div class="nhsuk-action-link nhsuk-u-margin-top-1">
  <a class="nhsuk-action-link__link" href="https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/{{backlog_issue_id}}">
    <svg class="nhsuk-icon nhsuk-icon__arrow-right-circle" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" aria-hidden="true">
      <path d="M0 0h24v24H0z" fill="none"></path>
      <path d="M12 2a10 10 0 0 0-9.95 9h11.64L9.74 7.05a1 1 0 0 1 1.41-1.41l5.66 5.65a1 1 0 0 1 0 1.42l-5.66 5.65a1 1 0 0 1-1.41 0 1 1 0 0 1 0-1.41L13.69 13H2.05A10 10 0 1 0 12 2z"></path>
    </svg>
    <span class="nhsuk-action-link__text">Feedback or share insights on GitHub</span>
  </a>
</div>

<p>If you have any questions, <a href="/get-in-touch">get in touch</a> with the service manual team.</p>
```

**Comment by anandamaryon1** [comment]
> ## Proposed design iterations
> Design system:
> 
> ![Screenshot 2021-07-05 at 09 45 57](https://user-images.githubusercontent.com/14331000/124443832-ece0ce00-dd75-11eb-9e85-7eb69b32625e.png)

@sarawilcox I wonder whether calling out that it's a free account will help? It seems that this is also how GitHub refer to these accounts now too "[GitHub free for personal accounts](https://docs.github.com/en/get-started/learning-about-github/githubs-plans#github-free-for-personal-accounts)". 

I'm sure this content has been discussed and iterated previously, but I'd be interested to know whether we can allude to the fact that you can learn more about the component/thing by reading the GitHub discussion, and use wording similar to gov.uk which says, "take part in the discussion", which is a little more open than our specific feedback or insights?

**Comment by sarawilcox** [comment]
@anandamaryon1 and @aviangel-NHS The content above is what the team that worked on community and contribution recommended based on UR but we always recognised that we might iterate it. This is what I've done for now. 

The above snippet mentions "feedback or share" 3 times. I think it is worth mentioning taking part in the discussion. 

Also I do think it's worth mentioning "free" (but not the brand GitHub Free). We say "public" to remind people it's not an NHS England private space. 

![Screenshot 2024-02-19 at 14 12 17](https://github.com/nhsuk/nhsuk-service-manual/assets/45792959/89e3649c-dea3-48ed-80f8-80dca36444e9)

Let me know if you (or anyone else) has any comments, please.

**Comment by cjforms** [comment]
It's better and here are a couple more tweaks because:
- there's a spare comma between free and public. Or maybe there's a missing comma after public
- I'm not sure whether I need to read 'how to feedback or share insights' (the 2nd link in the screenshot) before or after going to the link 'Feedback or share insights on Github'. Or are they the same thing?
- we've got the 'what' before the 'why' more or less throughout. 

How about: 
**Share insights or give feedback**

To help us improve this guidance, we welcome your insights and comments in our discussions on GitHub. 

To contribute, you need a free GitHub account. GitHub is public and your comments can be seen by everyone. 

-> Join the discussions on GitHub

**Comment by cjforms** [comment]
You might also consider mentioning that there's another route, which is to ask on the NHS Service Manual Slack

**Comment by sarawilcox** [comment]
Hi @cjforms, thanks for your comments. We had a look at them when we went through another round of iterations today. We've headlined the why now.

![Screenshot 2024-02-20 at 14 39 46](https://github.com/nhsuk/nhsuk-service-manual/assets/45792959/72a3082c-30f2-43ae-8181-60ee920f9291)

**Comment by cjforms** [comment]
I much prefer your version, thanks. 

Just two minor extra tweak to suggest. 

1. Turn the 'if' sentence around so it's got 'if' before 'then', as in:

"If your service has gone through a service assessment or peer review, then we're especially interested to hear from you."

2. Bring back the 'to' in the headline: "Help us to improve this guidance". (Realised that I was reinserting the 'to' in my head as I read it).

**Comment by sarawilcox** [comment]
Thanks Caroline. :-)
1. I'll make the "if" change now. 
2. We usually leave out "to" unless it's confusing without. (Colleagues will probably delete it.)

**Comment by cjforms** [comment]
One day my 'bring back THAT' campaign will be successful (and 'to', and all the other little words). They're hugely helpful for people who don't read very well and they don't have any disadvantages for people who do read well. But I guess today is not that day :)

**Comment by sarawilcox** [comment]
Published.
