### ISSUE TITLE
Review existing research for additional language support

### ISSUE THREAD

**Issue by amyj2110** [nhsuk/nhsuk-service-manual#1275]
## What

We need to find what work has already been done to understand additional language support.

## Why

So we can:

- Understand what findings already exist

## Done when

- [x] Investigate what work already exists around additional language support
- [x] Document any existing work
- [ ] Create a "discovery backlog" based on the desk research findings

**Comment by sarawilcox** [comment]
Of any interest? https://www.gov.uk/guidance/language-interpretation-migrant-health-guide. PHE are probably worth talking with.
Also see the issue in the content style community backlog: https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/367

**Comment by sarawilcox** [comment]
Worth checking in with:
- Laura Hajba and Ana Savic - who worked on a prototype which involved offering a letter in multiple languages 
- Sian Addicott at DHSC: Sian.Addicott@dhsc.gov.uk - Sian was working on a prototype which involve offering Bengali content
- GOV.UK Slack channel #non-English
