### ISSUE TITLE
Plan how we can user test the inclusion microsite

### ISSUE THREAD

**Issue by amyj2110** [nhsuk/nhsuk-service-manual#1276]
## What

Now that we've created the inclusion microsite, we need to run it through a round of user testing. 

## Why

So we can:

- make sure people understand the microsite
- make sure people can navigate through the microsite

## Done when

- [x] Create a plan for how we can test the inclusion microsite

**Comment by nancyhalladay24** [comment]
Plan: 
- Create a survey to send to people using the micro-site
- Conduct focus groups with networks to evaluate inclusion content
- Usability test the micro-site
