### ISSUE TITLE
Create 'How to feedback or share insights on GitHub' guidance

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#1285]
## What

We need to create guidance on how to feedback or share insights on GitHub.

## Why

Research has shown us that:
- Contributing work for those who are not regular users of GitHub is difficult
- Even internal users who contribute need reminding on how to use GitHub

## Done when

- [x] Drafted guidance
- [x] Add guidance to service manual
- [x] Content review
- [ ] Code review
- [ ] Published

**Comment by davidhunter08** [comment]
This guidance could be linked to from the [feedback or share insights section](https://github.com/nhsuk/nhsuk-service-manual/issues/1261) at the footer of guidance pages.

**Comment by davidhunter08** [comment]
Guidance could cover:
- How to find the thing in the backlog
- How to leave a comment
- How the service manual team reviews comments

**Comment by sarawilcox** [comment]
Example from prototype 2020. 
![Uploading 886c5822-8a74-42f5-bd88-37493c8df523.png…]()

**Comment by sarawilcox** [comment]
https://design-system.service.gov.uk/community/share-research-findings/

**Comment by sarawilcox** [comment]
@anandamaryon1 @aviangel-NHS (and @davidhunter08, if interested). This is how I've iterated the page that was prototyped in 2021. Please feel free to comment. 

![screencapture-3000-nhsuk-nhsukservicemanu-6l7mpyzlfy2-ws-eu108-gitpod-io-community-and-contribution-feedback-or-share-insights-2024-02-19-16_05_29](https://github.com/nhsuk/nhsuk-service-manual/assets/45792959/8cd8c4a8-a838-4060-a2ec-74c20149322a)

**Comment by sarawilcox** [comment]
Published: https://service-manual.nhs.uk/community-and-contribution/feedback-or-share-insights
