### ISSUE TITLE
Review inclusion guidance with profession huddles

### ISSUE THREAD

**Issue by amyj2110** [nhsuk/nhsuk-service-manual#1286]
## What

We need to review the inclusion guidance with a wider group of people. We can do this by going out to the different profession huddles and presenting.

## Why

It's important we slowly reveal the inclusion guidance to different groups and get their feedback.

## Done when

- [x] ~~Booked in with the design huddle (Thursday 15th July 3pm - 4pm)~~
- [x] ~~Booked in with the content style council (Tuesday 27th July 2pm - 3.30pm)~~
- [x] ~~Booked in with the user research huddle (Wednesday 21st July 3pm - 4pm)~~
- [x] Booked in with product huddles - (Wednesday 28th July)
- [ ] Booked in with development huddle
- [ ] ~~Booked in with delivery huddle~~

**Comment by amyj2110** [comment]
@EllenDoyle , @georginaplatt , @chrimesdev and @DomBaker ... do product / delivery / development have anything equivalent to a huddle that we could present at?

**Comment by DomBaker** [comment]
@amyj2110 There is the Dev huddle, I believe there is one this Thursday - don't think the spaces have been filled for speakers so may be a good shout?

**Comment by amyj2110** [comment]
@DomBaker awesome, thank you! This week might be a bit short, but definitely happy to sneak into the next one. Who'd be best to contact to get a spot?

**Comment by EllenDoyle** [comment]
How about NHS.IK Show and Tell next Tuesday  at 11am? We have DM catch-ups but never seen a presentation at one.

**Comment by sarawilcox** [comment]
I'm not sure I'll be ready by then. It's taking a bit of reworking on my part.

**Comment by EllenDoyle** [comment]
There is another NHS.UK S&T on Tuesday 27th July at 11am if you would like to book me a space on that?

**Comment by georginaplatt** [comment]
There's a product meeting every fortnight, next one is 14th July. I can ask for a slot, we've had a few guest appearances.

Can also share any prototypes/draft guidance in the #product-management & #nhs-uk-product-owners channels.

**Comment by amyj2110** [comment]
@georginaplatt product meeting on the 14th sounds great. I might not be able to make it, but confident that @nancyhalladay24 could put on a good show!

@EllenDoyle 27th of July S&T sounds great, we'll hopefully be going round the huddles too before then, so will be sharing. Could you possibly ask if we could present? I think it would take about 10 minutes to run through and explain its importance.

**Comment by nancyhalladay24** [comment]
Yep 14th and the 27th are ok with me @amyj2110 @georginaplatt @EllenDoyle

**Comment by sarawilcox** [comment]
@amyj2110 @nancyhalladay24 I'm wondering whether we could present it at the next Content Style Council and show people how the inclusive content principles have been integrated?

**Comment by nancyhalladay24** [comment]
Yeah that makes sense. What date is the style council meeting again? I can't find it in my calendar.

**Comment by sarawilcox** [comment]
@nancyhalladay24, that's because I haven't decided yet! ;-) I need to fix a date. Let me have a think. Then I'll talk with the team.

**Comment by EllenDoyle** [comment]
@amyj2110  I will get us a slot on S&T 27/7. Sent a message to Sarah Norman and Astrid Morris.

**Comment by nancyhalladay24** [comment]
Ohhhhh my bad! haha @sarawilcox fair enough! 

Thank you @EllenDoyle

**Comment by nancyhalladay24** [comment]
I will book the design huddle for next week :)

**Comment by EllenDoyle** [comment]
Style Council Meeting Tuesday 27th July 2pm - 3.30pm @nancyhalladay24

**Comment by amyj2110** [comment]
@EllenDoyle sorry, is that the slot for Show and Tell? I don't think we need to present at the content style council?

**Comment by georginaplatt** [comment]
Checking with Harriet for the 28th product meeting - will keep you posted @nancyhalladay24
