### ISSUE TITLE
Check with contributors if we can use their photos

### ISSUE THREAD

**Issue by amyj2110** [nhsuk/nhsuk-service-manual#1288]
## What

We need to get permission from our contributors to use their GitHub or Slack photos on our microsite.

## Why

We want to make sure this is okay with them and that they are comfortable with it. 

## Done when

- [x] Create a consent form for contributors to fill in
- [x] Received written or verbal consent from contributors to use their photos
- [x] Added all contributors photos to the relevant places on the microsite

**Comment by nancyhalladay24** [comment]
I have created a [spreadsheet]([https://hscic365.sharepoint.com/:x:/s/InternalServiceManual/EaHMMSAJQUpNuT-KG3gipZABU-pQgIhfBXxsX1aw4DDr0Q?e=Jvwgpc])to track contributors and their consent

**Comment by nancyhalladay24** [comment]
Update: blocked for now as Lucy Ha is on holiday and we don't know Clara Greo's contact details since she has left NHS D

**Comment by nancyhalladay24** [comment]
We have heard back from Clara and Sonia. Just waiting for Lucy Ha.
