### ISSUE TITLE
Satisfaction survey - decide on further page placement

### ISSUE THREAD

**Issue by karlgoldstraw** [nhsuk/nhsuk-service-manual#1310]
## What

After the 3 initial links #1309 are added to the service manual, we must decide whether we need to add the link in additional places on the site, including the hub pages or in-page on content pages.

## Why

If the initial links aren't performing as hoped, then we must evaluate their placement in order to encourage more feedback. 

## Resources

- [Satisfaction survey journeys Mural](https://app.mural.co/t/nhsdigital8118/m/nhsdigital8118/1626386322787/c90ff079da3e5d646594b86feac5cebb0ca2bfeb?sender=karlgoldstraw0227)

## Done when

- [x] We've evaluated the initial placement performance from #1309
- [x] Designed some screens to show placement
- [ ] Released new screens

**Comment by teodorastraianu1** [comment]
### Add on popular pages

As we are not getting as many responses as we would like, my initial thinking was linking to this from some of the most visited pages on the site as well. (will add mock-ups showing the screens)

Based on looking at this board (https://app.mural.co/t/nhsdigital8118/m/nhsdigital8118/1629882884777/ca1db32c7b055246f27f20b058dba4a4b33266ef?wid=0-1631283442043&sender=u66c5f5a4dc3e7e83cfd23273) and analytics report, I would suggest having it on:

- Design System page
- Content Style Guide page
- Styles page
- Components page
- NHS Service Standard page

**However,** lots of these pages sit within the Design System, so wondering if this means we are more likely to get feedback from designers than other professions if we go with this approach and whether it is an issue if that happens.

### Thinking about popular journeys

I have also been thinking whether it would make more sense to add them at the end of what we think are popular journeys, so people can complete the survey once they finish what they were doing. 

For example, it seems from stats that this journey is quite popular: **Home page** > **Design system** > **Styles** > **Colour**, so perhaps putting the survey on the Colour page would work.

@karlgoldstraw @sarawilcox do you have any thoughts? I'm struggling a bit with making a decision.

I would probably still suggest going with the most popular pages, as I think it gives more of a chance of lots of people seeing it (and perhaps adding it to some of the more popular Content pages so we are more likely to get feedback from content designers as well).

**Comment by sarawilcox** [comment]
Hi @teodorastraianu1, my feeling would be to start with some of the hub pages:
- design system
- content style guide
- styles
- components
The NHS service standard page is more difficult as it's not a hub page.

Perhaps we could see how much traffic this drives to the survey in the first instance, and then consider putting it at the end of some popular journeys. But I wonder whether putting it at the end of popular journeys might skew the results - would we get more satisfied customers that way than on hub pages? @amyj2110, what do you think?

What about starting with hub pages and then seeing how that affects survey responses? @amyj2110,  how many responses have we had since we published the survey, please - to give us a baseline over x weeks?

I've be interested to see mock-ups.

**Comment by teodorastraianu1** [comment]
Hi @sarawilcox, thanks for the response!

I agree with starting with the hub pages.

Below are the mock-ups for the 4 pages you mentioned.

**Design system**


<img width="1134" alt="Screenshot 2021-09-22 at 09 03 09" src="https://user-images.githubusercontent.com/73899034/134345895-c78229c3-4672-43cc-a6f0-80b5e76a7d7e.png">

**Content style guide**

<img width="1265" alt="Screenshot 2021-09-22 at 09 04 29" src="https://user-images.githubusercontent.com/73899034/134345967-de9727af-52e6-4fb7-b772-d12459be4bd3.png">

**Styles**

<img width="1234" alt="Screenshot 2021-09-22 at 09 05 14" src="https://user-images.githubusercontent.com/73899034/134345999-91b919e2-ece2-474d-94a1-6716ca2d2d3b.png">

**Components**

<img width="1189" alt="Screenshot 2021-09-22 at 09 06 22" src="https://user-images.githubusercontent.com/73899034/134346041-85ba7576-f2c4-4203-a6c6-00c8275ab21b.png">


Also agreed the NHS service standard page is more difficult as it's also a very long page so if we put the survey at the bottom I'm not sure people would scroll down enough to get to it.

**Comment by sarawilcox** [comment]
I think the design system hubs are fine, @teodorastraianu1. But on the content style hub there is more info on the page. Are you thinking that it would push this bit down?
![Screenshot 2021-09-22 at 16 45 50](https://user-images.githubusercontent.com/45792959/134377062-2efa02b6-1818-4f50-a4b6-3f64617296f0.png)

**Comment by teodorastraianu1** [comment]
@sarawilcox Yes, I was, but I am happy to change if you think the survey should go right at the bottom of the page. To me they both felt like sections that could end the page and I wanted to give as much visibility as possible to the survey, but again happy to change!

**Comment by sarawilcox** [comment]
I wonder if we could find out how many people click the link to the radio programme? Julius should be able to let you know.

**Comment by teodorastraianu1** [comment]
@sarawilcox He said it's had 53 clicks since it went live, so since the 9th of April 2021. It doesn't feel like a lot to me?

**Comment by sarawilcox** [comment]
You're right. Let's try the survey link above this.

**Comment by teodorastraianu1** [comment]
@sarawilcox Yes it's done, I'll close it now and add another issue :)
