### ISSUE TITLE
Prep for design system day session: how to grow a design system and still maintain it.

### ISSUE THREAD

**Issue by georginaplatt** [nhsuk/nhsuk-service-manual#1317]
## What
Create a mural board: how to grow a design system and still maintain it, to add ideas to before session. The session is a half-hour chat about the challenges of building and maintaining them, and the kinds of things that can go wrong.

## Why
Prep for session. Balancing delivering new stuff/growing the design system with handling BAU/supporting the community is an issue for the team and we may find that talking about it helps us deal with it better ourselves.

## Done when

- [x] Find previous conversations about BAU work - Lucy's retro summary @georginaplatt 
- [x] Create a mural & share with team to add thoughts @karlgoldstraw 
- [x] Shared on design system day @georginaplatt

**Comment by karlgoldstraw** [comment]
Added a Mural board with a basic affinity mapping format: https://app.mural.co/t/nhsdigital8118/m/nhsdigital8118/1626427644670/7fdfd449d191468703cb240096d375c73269c363?sender=karlgoldstraw0227

**Comment by georginaplatt** [comment]
Meeting scheduled with Rosie from GDS 21st July to chat through breakout session format

**Comment by georginaplatt** [comment]
[Mural](https://app.mural.co/t/nhsdigital8118/m/nhsdigital8118/1626865921662/4582a08adf5ee5ec2d91782830a27e9cea7b6f50) from the design system day.
