### ISSUE TITLE
Follow up after July Style Council meeting

### ISSUE THREAD

**Issue by EllenDoyle** [nhsuk/nhsuk-service-manual#1325]
## What
Write up of meeting notes and actions taken and shared with attendees
Content changes published in service manual

## Done when

- [x] notes taken from meeting
- [x] action points agreed and allocated
- [x] notes and actions shared on Slack content channel
- [x] notes and actions approved by clinicians

We then need to publish content changes in service manual - this is in next ticket: https://github.com/nhsuk/nhsuk-service-manual/issues/1382

**Comment by sarawilcox** [comment]
Notes shared on Slack content channel, with one query in the channel.
I'll review any comments when I get back from leave and then send the notes to the clinicians.

**Comment by sarawilcox** [comment]
Sent notes to clinicians for approval.

**Comment by sarawilcox** [comment]
Approval has come through. I can prep changes for publication next.
