### ISSUE TITLE
Prep for December Style Council meeting

### ISSUE THREAD

**Issue by EllenDoyle-zz** [nhsuk/nhsuk-service-manual#1326]
## What

Invite people, prepare the agenda and slides for the meeting.

## To do

- [ ]  Arrange room - not needed
- [x]  Agree meeting date - 1 December 2021
- [x]  Arrange Teams meeting and send out invite witb notes from last meeting
- [x]  Firm up agenda 
- [x]  Get issues ready with colleagues
- [x]  Make sure that GitHub is up to date
- [x]  Share agenda and info about topics up for discussion - by email, on NHS.UK and NHS digital service manual Slack
- [x]  Prepare slides 
- [x]  Sent out slides the day before

## Related tasks
- [ ] Review guidance on links and prepare proposals
- [ ] [Left align content](https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/297)

**Comment by sarawilcox** [comment]
Come back to image captions.

**Comment by sarawilcox** [comment]
Close this. Meeting held.
