### ISSUE TITLE
EPIC: Additional Languages (Discovery)

### ISSUE THREAD

**Issue by CatherineReader** [nhsuk/nhsuk-service-manual#1339]
## What

Currently we have no guidance on additional languages and across NHS Digital services, and the wider NHS, presenting information to users in additional languages is something that happens infrequently and without consistency.

## Why

Our Public Sector Equality Duty – particularly in respect of the protected characteristic of ‘race’, as defined by the Equality Act 2010, because of its correlation with fluency in English. This is a duty to consider (re. protected characteristics) whether our output is discriminatory in its effect and take steps that are effective in minimising disadvantages associated with such discrimination

## Must

Answer the following key research questions

- Do those who are not fluent in English use the NHS website and associated services? Does it meet their needs?•
- How are those who are not fluent in English currently getting information about health? What role is played by local services and communities? How can we better support them?•
- Is English the obstacle for the communities that we are failing? Are there wider issues with the NHS brand itself? For what percentage of users is English easy read an effective solution?
- Are there notable differences in what causes issues for different groups? How should these be prioritised?•
- Are there key content items and calls to action that are better suited to translation than others?•
- What are the clinical implications of translating content into other languages?•
- Strengths and weaknesses of different media – text, infographics, videos, animations, audio? •
- Is the priority for action here best defined by an organisational boundary or by a service or goal?

- [ ] #1470

## Outcome

-

**Comment by sarawilcox** [comment]
We're taking forward this issue as a BAU content style guide issue: [Content formats guidance](https://github.com/nhsuk/nhsuk-service-manual/issues/1672).
