### ISSUE TITLE
Review IA card sort findings with IA team 

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk-service-manual#1364]
Sarah Norman to arrange a meeting for Matt Piper to feedback

**Comment by sarawilcox** [comment]
Initial meeting 16 August.
@EllenDoyle, I wasn't clear who is going to arrange the follow-up meeting when we've had a chance to digest the findings. 

Links to research results in #ia-service-manual chat in Slack.

**Comment by EllenDoyle** [comment]
I can put a meeting in diaries later this week if Sarah doesn't. I talk to Sarah all the time so will liaise with her.
