### ISSUE TITLE
Risk Register

### ISSUE THREAD

**Issue by EllenDoyle-zz** [nhsuk/nhsuk-service-manual#1373]
# What; 
risks need to be collated into a risk log, for management and presentation to Delivery Board

  #Why; 
risks need to be managed and mitigated to avoid issues arising

  #Done when;

- [x] Risks identified
- [x] Risks agreed
- [x] Risks rated
- [x] Risks pulled together in a risk log
- [x] Risks included in presentation, ready for delivery to Delivery Board

**Comment by EllenDoyle** [comment]
Risks agreed and saved as v0.00c. Rating meeting with team to take place 25.8.21.
