### ISSUE TITLE
Feedback results of community prioritisation exercise to the design community

### ISSUE THREAD

**Issue by karlgoldstraw** [nhsuk/nhsuk-service-manual#1377]
## what

We need to provide the design community with the results of the community prioritisation exercise

## why

We need the community to feedback on the top five items, including those who voted for them so that we can make sure they are ready for moving into a forthcoming service manual sprint

## done when

- [x] A presentation is the exercise and results is created
- [x] The presentation is shared with the community

**Comment by georginaplatt** [comment]
@henocookie can we close this, I feel like this is done?
