### ISSUE TITLE
Research the use of images on NHS websites

### ISSUE THREAD

**Issue by nancyhalladay24** [nhsuk/nhsuk-service-manual#1381]
## What
I need to find out about the selection process for images on NHS websites.

## Why
So I can understand what type of images we use and why

## Done when
- [x] Talk to Dean and Ben about branding and when the last hero images were designed​
- [ ] Look at this presentation Sara sent: https://nhsuk.slack.com/archives/CUXBM6CET/p1619775694000700​
- [ ] Look at #service-manual-image-guidance channel on slack

**Comment by sarawilcox** [comment]
Might be worth talking to Pauline Richardson and Jazzy DeWaard in the multimedia team. Have you seen the draft images guidance?

**Comment by nancyhalladay24** [comment]
Hiya, before I went on A/L I saw Rich and Pauline present the illustration style work but don't think I have seen the draft images guidance. I will drop them a message. Thank you @sarawilcox :)

**Comment by nancyhalladay24** [comment]
After a meeting with Dean and Ben we decided that since the component was designed predominantly as branding for NHS.UK and not specifically with UCD principles in mind. It’s best if we don’t produce guidance and promote others to use it.
We think it would be more beneficial to produce homepage guidance, as the hero banner is a component of a homepage.

Therefore the direction and ownership of this work has changed. I'll create new cards to reflect the work that needs to be done.
