### ISSUE TITLE
Provide radio with page heading example to make following advice easier

### ISSUE THREAD

**Issue by GrilloPress** [nhsuk/nhsuk-service-manual#139]
On [the radio button page](https://beta.nhs.uk/service-manual/styles-components-patterns/radios) we tell people:

> If you are asking just 1 question per page as the GOV.UK design system recommends, you can set the contents of the `<legend>` as the page heading. This is good practice as it means that screen reader users will only hear the contents once.

But we don't include an example of this.

We should make it easier for people to follow our advice.

**Comment by theonlymojo** [comment]
I've copied this to nhsuk-service-manual-backlog, it's issue [94](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/94)
