### ISSUE TITLE
Prototype kit: map the disparities between it and the frontend library

### ISSUE THREAD

**Issue by karlgoldstraw** [nhsuk/nhsuk-service-manual#1399]
## What 

There are disparities between the prototype and the frontend library. We need to work out what these are, and how we can better align the two products.

## Why 

The prototype kit should be a sandpit of all our components and patterns that are available to the wider community and live services. 

## Done when

- [ ] A comparison is made of what exists and is missing from each product
- [ ] Tickets are elaborated with details of what to add or remove

**Comment by teodorastraianu1** [comment]
> This is the issue you're working on at the mo, aren't you, @teodorastraianu1 and @anandamaryon1 ?

Yes it's the one we're discussing tomorrow morning :)
