### ISSUE TITLE
Visual/advice not consistent, no example of a table with panel (and heading)

### ISSUE THREAD

**Issue by beseven** [nhsuk/nhsuk-service-manual#143]
On [the table page](https://beta.nhs.uk/service-manual/styles-components-patterns/table) we tell people:

> The table component tested well with users on health information pages. The white panel helped users scan the page and find information when it was surrounded by text content.

But we don't include an example of this, as the main table is the simple one, so it's confusing

Based on the conversation [here](https://github.com/nhsuk/nhsuk-frontend/issues/179) it seems there is a preference to keep the table with a panel with a heading, and the heading needs to be different than the caption so the following then needs updating:

> Use the <caption> element to describe a table in the same way you would use a heading. A caption helps users find, navigate and understand tables.

**Comment by theonlymojo** [comment]
Copied to /nhsuk-service-manual-backlog as issue [95](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/95)
