### ISSUE TITLE
Iterate draft start page pattern for the design system working group 

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk-service-manual#1434]
Follow up: https://github.com/nhsuk/nhsuk-service-manual/issues/1416.

**Comment by sarawilcox** [comment]
Done. Once the PR is merged, I'll ask Ben to review it one last time.

@chrimesdev and @karlgoldstraw, could you both check that you're happy with it, please, before it goes to DSWG.

Putting this into review column.

**Comment by sarawilcox** [comment]
I've finished what I need to do on this. 

@chrimesdev, I'll take you off the issue now. Just needs @karlgoldstraw to review it.

Otherwise the start page is ready for DSWG.

**Comment by sarawilcox** [comment]
For the record:
https://nhsuk-service-manual-pr.azurewebsites.net/design-system/patterns/start-page

Username: standards
Password: empowerthepeople

**Comment by karlgoldstraw** [comment]
The only thing that sticks out about this to me (and actually isn't unique to this pattern), is that the example has a home link on the NHS logo that loads our service manual inside the frame

And I'd suggest we disable that link, like we do with others. 
Although saying that, some links are disabled, some are real, and some are fake links which throw a 404.

**Comment by sarawilcox** [comment]
Ooh, weird. I'm not sure how to disable the link. Would you be able to do that, please, @karlgoldstraw ? (And/or tell me how best to do it, please.)

I wonder if we should have a task in the backlog to do that consistently across the design system.

**Comment by karlgoldstraw** [comment]
I'm unsure what our coding standard is for this tbh @sarawilcox 
@chrimesdev - Can you help me with this please?

**Comment by sarawilcox** [comment]
@chrimesdev, would you be able to help us disable the link on this page, please, pending bringing other examples into line?
