### ISSUE TITLE
New starters add themselves to the team page

### ISSUE THREAD

**Issue by karlgoldstraw** [nhsuk/nhsuk-service-manual#1446]
## What

We need to update the team page at: https://service-manual.nhs.uk/service-manual-team

## Why

We need to inform people who the current team are.

## Instructions

- [Clone the service manual repo](https://github.com/nhsuk/nhsuk-service-manual)
- Install dependencies
- Run it locally
- Open in code editor
- Make a branch 
- Makes changes
- Push to Github
- Make a pull request for @sarawilcox to review

## Done when
- [x] Amber is added to the team page
- [x] Henry is added to the team page
- [x] Teodora is added to the team page
- [x] Mua is added to the team page
- [x] Nancy is removed from the team page
- [x] The page date is updated 
- [x] Sara has done a content review

**Comment by sarawilcox** [comment]
Note that:

-  names are in alphabetical order
- we use an en-dash (–), not a hyphen

**Comment by henocookie** [comment]
I wonder if it would be worth including emails and/or links to people's GitHub user accounts? Not sure if this has been looked at before!

**Comment by karlgoldstraw** [comment]
> I wonder if it would be worth including emails and/or links to people's GitHub user accounts? Not sure if this has been looked at before!

I like that idea @henocookie

**Comment by sarawilcox** [comment]
Thanks @henocookie @teodorastraianu1 @MuawiyahM @ambchang. All good.

It occurs to me that we might want to think about reformatting this page at some point. We're such a bit team now, I suspect that alphabetical order isn't very helpful. What do people want from this page? A

**Comment by henocookie** [comment]
> It occurs to me that we might want to think about reformatting this page at some point. We're such a bit team now, I suspect that alphabetical order isn't very helpful. What do people want from this page? A

Agreed. Perhaps having headings for different professions could help break up the long list. For example using the following H2s: "Content Design", "Development", "Interaction Design", "Product and Delivery Management" and "User research"?

**Comment by henocookie** [comment]
Some ideas of how the page could be broken up as the list is getting quite long:

1. Use headings alone to break up the list into profession groups

![Service-manual-team-NHS-digital-service-manual](https://user-images.githubusercontent.com/52792328/133996847-42454cb2-0721-4d5b-8bc0-0a1a76ec2f7e.png)

2. Use headings, grids and photos to break up the list into profession groups

![Service-manual-team-NHS-digital-service-manual-grid-with-photos](https://user-images.githubusercontent.com/52792328/133996857-032c6df7-4fde-4ee4-bd44-476c36a170ff.png)

**Comment by ambchang** [comment]
I like the idea of a more grid-like option as it seems a more sustainable should/when the service manual team grows even bigger in the future (whereas the pure headings one would still result in a very long page). 

Also, I know in the inclusion micro-site there's little circle icons for authors, perhaps we could keep that circular shape? (not sure where this design stemmed from and/or if other teams have used that before)
<img width="728" alt="Screenshot 2021-09-20 at 12 53 45" src="https://user-images.githubusercontent.com/71649751/133997953-0d6dc518-8758-48f1-9ef9-403c0cd3b561.png">

**Comment by karlgoldstraw** [comment]
Id say just pick a design and run with it. Would be a nice page for someone to scratch up on their css. 

I liked the idea of linking to GitHub bios, then we're not loading images and we're allowing the person to control what they want to share.

**Comment by henocookie** [comment]
Latest thinking: use pictures of each team member for the bullet lists

![Service-manual-team-NHS-digital-service-manual](https://user-images.githubusercontent.com/52792328/134159706-ceff463d-06c5-410b-ae9a-49716b27b35f.png)

**Comment by sarawilcox** [comment]
Hi @henocookie, if you could lower case the word "design" in "Content design" and "Interaction design" and the words "delivery management" in "Product and delivery management", this is all fine from a content point of view.

What do other people think? 

Is this something we'd want to publish in tomorrow's release?

**Comment by henocookie** [comment]
Thanks for the content review @sarawilcox. Made those changes on the [updated-team-page-design branch](https://github.com/nhsuk/nhsuk-service-manual/tree/updated-team-page-design ) if we do want to include it in tomorrow's release @chrimesdev. 

![Service-manual-team-NHS-digital-service-manual](https://user-images.githubusercontent.com/52792328/134168593-0e5bcd07-b8aa-4cea-b8da-b60641a68a39.png)

@PeteKowalczykNHS  @chrimesdev @DomBaker @magicaljellybeans @ambchang @danjohnstonUX @karlgoldstraw @teodorastraianu1 @CatherineReader @EllenDoyle @georginaplatt @mohjam @amyj2110 @MuawiyahM tagging you all to check how people feel about these proposed changes and also what pictures people would want using for themselves? I've used NHS.UK Slack profile pictures for now.

**Comment by georginaplatt** [comment]
Looks fab that everyone! Like the profession headers and images. I'm fine with my image, use it for everything work-related @henocookie .

**Comment by Eldo2** [comment]
Looks good to me for publishing tomorrow @henocookie

**Comment by teodorastraianu1** [comment]
Looks good to me too @henocookie!

**Comment by henocookie** [comment]
[Team page](https://service-manual.nhs.uk/service-manual-team) updated in the [September 2021 release](https://github.com/nhsuk/nhsuk-service-manual/blob/master/CHANGELOG.md#520---22-september-2021) with new team members added 🙌🏻 and old team members removed 😿

Creating a new issue for the updated page design with profession-based headings and team member pictures.

**Comment by henocookie** [comment]
[Team page](https://service-manual.nhs.uk/service-manual-team) updated in the [September 2021 release](https://github.com/nhsuk/nhsuk-service-manual/blob/master/CHANGELOG.md#520---22-september-2021) with new team members added 🙌🏻 and old team members removed 😿

Created a new issue for the updated page design with profession-based headings and team member pictures: Update team page to accommodate the larger team #1479
