### ISSUE TITLE
Arrange a meeting with Karina at NHSX 

### ISSUE THREAD

**Issue by georginaplatt** [nhsuk/nhsuk-service-manual#1455]
## What
Arrange a meeting with Karina at NHSx to see how the assurance team can support the service manual & design system team by supplying data on who is using the design system.

## Why
So we understand the broad range of users of our products, how satisfied they are and whether they are feeding back or have an understanding about community contributions.
For example, if they've tweaked something to fit their purpose or used a component in a different way. NHSx assurance team have suggested that they share this, but they aren't always sure the best way to do it.

## Done When
- [x] Meeting arranged 23rd Sept
- [x] Agreed on how they can supply data on users of our products
- [x] Next steps agreed

**Comment by sarawilcox** [comment]
@georginaplatt, you know we've got a meeting with Karina on Thursday?

**Comment by georginaplatt** [comment]
I found this task in the ticker #1185 & thought we don't have a ticket for thursday.

**Comment by georginaplatt** [comment]
NHSx standards and assurance team have agreed to supply a list of all services they are aware of that use the service manual & design system. They can provide this from the tracker for assessments. The can't provide data on services using the 3 new health NHS-service standards or content style guide (they rely on teams telling them this).

**Comment by sarawilcox** [comment]
We've finished this, haven't we, @georginaplatt?
