### ISSUE TITLE
Skin symptoms: Rename inclusive language section

### ISSUE THREAD

**Issue by georginaplatt** [nhsuk/nhsuk-service-manual#1459]
## What
Rename Inclusive language section “Inclusive content” (as it covers imagery too) and to add skin symptoms to it.  

## Why
User insights suggested some usability issues with the placement of the skin symptons guidance (left hand menu) 

## Done When

- [x] Section renamed “Inclusive content”
- [x] Skin symptons added

## Next steps
 - #1653
-  #1651
 - #1652

**Comment by sarawilcox** [comment]
Done.
