### ISSUE TITLE
Skin symptoms: Add more explicit content - 'reflect various skin tones'

### ISSUE THREAD

**Issue by georginaplatt** [nhsuk/nhsuk-service-manual#1460]
## What
Make it clear that we want the NHS website to reflect various skin tones.
  

## Why
User insights suggestion to make the content more explicit, e.g. change terminology such as: “Images on the NHS website mostly show skin symptoms on white skin”, by stating that this is what we are trying to move away from. 

## Done When

- [ ] Change the content to be more explicit to reflect various skin tones
- [ ] Reviewed
- [ ] Published

**Comment by sarawilcox** [comment]
Content updated on branch iterateskinsymptoms.

We'll review and publish with other changes.
