### ISSUE TITLE
Skin symptoms: Add DermNetNZ to medical sources section

### ISSUE THREAD

**Issue by georginaplatt** [nhsuk/nhsuk-service-manual#1461]
## What
Add DermNetNZ to medical sources section/useful sources. Change H2 to make it clearer this is about medical sources for symptoms on black or brown skin.

## Why
User insights - suggestion to add DermNetNZ to medical sources section/useful sources.

## Done When
- [ ] Added DermNetNZ to medical sources section
- [ ] Reviewed
- [ ] Published

**Comment by sarawilcox** [comment]
Added to branch iterateskinsymptoms. Waiting for feedback from MT1.

**Comment by sarawilcox** [comment]
Agreed with MT1 and added to iterateskinsymptoms branch.
