### ISSUE TITLE
Skin symptoms: Highlight describing skin-tone section using inset text

### ISSUE THREAD

**Issue by georginaplatt** [nhsuk/nhsuk-service-manual#1462]
## What
Highlight the bit about describing skin tone as white, brown and black using inset text. 

## Why
 User insights suggest certain important parts/sections of the skin symptons guidance should be more prominent. However, it wasn’t clear from research how we might restructure the page. 
 
 ## Done When
 - [ ] Re-structure content by highlighting describing skin tone as white, brown and black using inset text. 
 - [ ] Reviewed
 - [ ] Published

**Comment by sarawilcox** [comment]
Done in branch iterateskinsymptoms. Release this change with the rest of skin symptoms content changes.
