### ISSUE TITLE
Skin symptoms: Remove Next steps section

### ISSUE THREAD

**Issue by georginaplatt** [nhsuk/nhsuk-service-manual#1464]
## What
Remove Next steps section.

## Why
User insights suggested a Next Steps/timetable regarding the skin symptoms guidance would be useful. 

## Done When
- [ ] Removed Next steps section
- [ ] Reviewed
- [ ] Published

**Comment by sarawilcox** [comment]
Done in branch iterateskinsymptoms.
Close ticket.
