### ISSUE TITLE
Skin symptoms: Consider renaming 'Research insights' section header

### ISSUE THREAD

**Issue by georginaplatt** [nhsuk/nhsuk-service-manual#1465]
## What
Consider if we could rename section header, if so remove and rename. 

## Why 
User insights suggest - section header terminology could be improved upon to make it easier for site users to understand for those who are not user researchers or content designers would be useful. 

## Done When
- [ ] Removed research insights section
- [ ] Renamed research insights section
- [ ] Reviewed
- [ ] Published

**Comment by sarawilcox** [comment]
Done. Changes made in branch iterateskinsymptoms.
