### ISSUE TITLE
Skin symptoms: Follow up MT1 actions

### ISSUE THREAD

**Issue by georginaplatt** [nhsuk/nhsuk-service-manual#1467]
## What
Follow-up on MT1 actions from the [meeting on the 08/09/21](https://nhsd-confluence.digital.nhs.uk/display/SMDS/Skin+Symptoms+Guidance+User+Research) to discuss recommendations from skin symptons guidance user research.

- long descriptions
- missing content
- research insights section

## Why
So we are collaborating and sharing responsibilities with the community for this work.
 
## Done When 
- [x] MT1 to provide more info about the value and purpose of long descriptions compared to alt-text, with examples, and an image if possible. 
- [x] MT1 to draft a para about the best way to label skin tone in alt text, based on unmoderated card sort. 
- [ ] MT1 to provide: 
- more detail about survey findings (500 people and how many self-identified as brown or black) 
- Info about card sort (approx 50 people) for Sara to add.

**Comment by sarawilcox** [comment]
Done. Iterated prototype in iterateskinsymptoms branch.
