### ISSUE TITLE
Arrange payments for Inclusive UR Consultancy and Participants

### ISSUE THREAD

**Issue by georginaplatt** [nhsuk/nhsuk-service-manual#1470]
## What
Arrange payments for Inclusive UR Consultancy and Participants.

## Why
So we can go ahead with user research for the additional languages discovery.

## Done When
- [x] Learn for life paid
- [x] Signly paid (PSG-219)
- [ ] In Sign Language paid (PSG-221)
- [x] Living Well consortium paid (PSG-215) - PO has gone out
- [ ] Smartlyte paid (PSG-223)
- [x] IFB paid

**Comment by Eldo2** [comment]
How odd - I can add a comment but cannot edit the story!

**Comment by georginaplatt** [comment]
@Eldo2 is this your new username? You need to be added to NHS.UK organization & then the service manual team on GitHub

**Comment by Eldo2** [comment]
I set up a new account using my private email address, but would ideally like to use my NHS account

**Comment by henocookie** [comment]
@amyj2110 to check what needs doing still for this work and liaise with @georginaplatt if any help needed

**Comment by EllenDoyle** [comment]
SmartLyte estimate PSG-223 shared with Hussein and general catch-up.

**Comment by EllenDoyle** [comment]
Awaiting response from Hussein Visram on Smartlyte and IFB Gaming.

**Comment by EllenDoyle** [comment]
All POs in progress. Meeting with Hussein Visram to clarify where they all are in the process 20/1. Will include in Handover document to Mo.

**Comment by georginaplatt** [comment]
Spoke to Ellen is chasing up with Hussein for update on these POs

Signly (PSG-219)
In Sign Language (PSG-221)
Smartlyte (PSG-223)

**Comment by georginaplatt** [comment]
Chased up with Hussein - all are at the invoice stage PSG - 215, 221 & 223.
