### ISSUE TITLE
Team to consider "content types" project

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk-service-manual#1477]
- [x] Sara to play back conversation with Mark Robinson to the team
- [x] Pete and Sara to get a better handle on "content types"

**Comment by sarawilcox** [comment]
- [ ] @PeteKowalczykNHS to write up our initial thoughts about Mark's prototype and the content model to play back to Mark and Kim 
- [ ] Sara and Pete to talk with Mark and Kim to get a clearer idea of the value of the NHS.UK content model to content designers outside NHS.UK
- [ ] I'll playback our initial thoughts to Georgina and Catherine, to help with deciding next steps/prioritisation

**Comment by EllenDoyle** [comment]
Following our discussion at sprint review 4/11 are we pushing back on this @sarawilcox ? Should Mark raise it as a suggested contribution, or have we already agreed it is not something we wish to pursue?

**Comment by sarawilcox** [comment]
@PeteKowalczykNHS @georginaplatt We're going to close this ticket.

Georgina's going to talk with Leigh as this appears to be linked to the IA guidance too.

And we will aim to do some user research around the needs of users outside of NHSD for various kinds of content, including guidance on content types.
