### ISSUE TITLE
Iterate care card pattern after DSWG

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk-service-manual#1500]
Sara to iterate the care card pattern after DSWG. 

- [x] Pick up these suggestions from Teodora: https://github.com/nhsuk/nhsuk-service-manual/issues/1488
- - [x] link to card component and vice versa
- - [x] include "care card" in title of page
- [x] Review comments from DSWG
- [x] Write up comments and actions on GitHub issue for care card pattern.

DSWG - 10 approve, 1 reject

### DSWG comments
- Need to look at recommendation not to use more than one of each care card type on a page - this has been necessary in some cases, and tested with users (e.g. sepsis) (Approve)
- Think using it as a pattern and advertising that it is a way to get users to the right care may lead people to put more content in them. Plus, service finders are also there to help users get the right care - so I feel the pattern is too broad for it to fit in to. All other patterns are incredibly specific, this feels too loose. If the component isn't being used correctly, then maybe the guidance needs to be more rigid. (Reject)
- How are we managing the process where people use it in unintended ways? It also says there’s a need not being met in the base components of people need something to call out things (Approve)
- Would like to see more guidance around the use of care cards for mental health occurrences rather than purely medical. (Approve)

**Comment by sarawilcox** [comment]
Amended pages:
- action link
- card
- care card component
- warning callout
- inset text
- colour
- expander
- A to Z of NHS health writing
- Formatting and punctuation

**Comment by henocookie** [comment]
@sarawilcox has written up [comments and actions on the care cards GitHub backlog issue](https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/8#issuecomment-961834721)
