### ISSUE TITLE
Broken link on 'Ask users for their NHS number' pattern page of the design system.

### ISSUE THREAD

**Issue by chrimesdev** [nhsuk/nhsuk-service-manual#1510]
Broken link in the 'Ask users for their NHS number' pattern page of the design system. Within the 'How to build the NHS number pattern' guidance the following links to a 404: 'modulus 11 algorithm (NHS Data Model and Dictionary)' https://www.datadictionary.nhs.uk/data_dictionary/attributes/n/nhs/nhs_number_de.asp?shownav=1

Raised on Slack

**Comment by sarawilcox** [comment]
Corrected link in branch review/1-subtitles. To go live at next release.
