### ISSUE TITLE
Explore ZenHub as a potential solution

### ISSUE THREAD

**Issue by georginaplatt** [nhsuk/nhsuk-service-manual#1532]
## What
Explore ZenHub as a potential solution to issues faced by the team using the current GitHub project boards.

## Why
There were many issues raised at the last retro around the usefulness of GitHub projects as a tool for managing the sprint, backlog and epics on a seperate roadmap board. Exploring alternative solutions such as ZenHub may be a good solution worth exploring.
![image](https://user-images.githubusercontent.com/79994928/137760327-22fc4faf-1fab-4406-a895-5b65db846073.png)

## Done When
- [x] Review features of value to the team
- [x] Watch [ZenHub YouTube tutorials](https://www.youtube.com/channel/UCyrIYNEXdQXhwF6a1pVsJiQ)
- [x] Gather feedback
- [x] Set out a clear way of working
- [ ] Synchronised Zenhub with Github

**Comment by EllenDoyle** [comment]
@DomBaker do you know if Adam synchronised Github and Zenhub before he left?

**Comment by DomBaker** [comment]
I don't think he has @EllenDoyle

**Comment by EllenDoyle** [comment]
In that case @DomBaker can I leave this with you?

**Comment by georginaplatt** [comment]
@DomBaker isn't ZenHub synchronised to GitHub now? , it's just not synchronised to the GitHub sprint and roadmap boards. So if we choose to go with ZenHub for managing sprints/epics/roadmaps the GitHub project board will no longer be needed and will pull directly from the GitHub repos? All the tickets are still in the open.

**Comment by DomBaker** [comment]
@georginaplatt Yeah that is correct, we no longer require the GitHub board we can manage everything from ZenHub.

**Comment by sarawilcox** [comment]
Is it possible for them to keep each other up to date? I find the GitHub board easy to read but only if we don't have to manage 2 separate boards.

**Comment by henocookie** [comment]
Key question to investigate: is ZenHub public like the GitHub project board and if not, is this an issue?

**Comment by DomBaker** [comment]
@henocookie This isn't possible, we can't gather analytics off Github.

**Comment by georginaplatt** [comment]
Closing this for now. This can always be revisited but as the size of the team reduced and therefore sprint board is more manageable & with regular backlog refinement, we can keep on top of the sprint board on Github.
