### ISSUE TITLE
Plan and deliver Roles and Responsibilities Workshop

### ISSUE THREAD

**Issue by EllenDoyle** [nhsuk/nhsuk-service-manual#1560]
##Why; Action came out of last retro that roles and responsibilities on the team are not clearly understood

##When; No fixed date, but following upcoming changes to the team

##Done when; 

- [ ] Most appropriate method understood
- [ ] Mural Board prepared
- [ ] Workshop delivered
- [ ] Agreed R&R discussed and agreed with the team

**Comment by henocookie** [comment]
@ambchang ran a roles and responsibilities workshop in 2021
