### ISSUE TITLE
Remove checked status from radio code example 

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#158]
The `checked` status from the radios example needs to be removed (on both HTML and Nunjucks examples).

https://beta.nhs.uk/service-manual/styles-components-patterns/radios

**Comment by ericlamarca** [comment]
Thanks @davidhunter08 - fixing this here: https://github.com/nhsuk/nhsuk-service-manual/pull/167

**Comment by AdamChrimes** [comment]
Looks like this is fixed, closing this.
