### ISSUE TITLE
Create findings document for our work

### ISSUE THREAD

**Issue by CatherineReader** [nhsuk/nhsuk-service-manual#1580]
## What
We will present a document to detail our findings, to audiences including internal stakeholders, internal teams and external teams 

## Why
We want our findings to provide a solid foundation for additional languages work both at NHS Digital and across healthcare

## User needs
- As an NHS Digital employee/ external person I want to know the scope of the discovery so that I have the right expectations of what the findings cover
- As an NHS Digital employee/ external person I want to understand the context that led the team to this discovery so I can understand how the work fits in to other services I am aware of/working on
- As someone working on future additional languages work I want to know what work has been completed so that I can understand what work needs to be carried out next
- As an NHS Digital employee/ external person I want to understand user needs so that I can address additional language user needs in my own team
- As an NHS Digital employee/ external person I want to understand how the discovery took place so that I can trust the information and gain understanding of how to carry out work of this nature myself
- As an NHS Digital employee/ external person I want to understand what will come from this work so I can keep up to date with it
- As an NHS Digital employee/ external person I want to understand current work that is in this area so that I can get inspiration 
- As an NHS Digital employee/ external person I want to understand the problems people encounter in providing additional language support so that I can consider how to provide additional language support that avoids these problems or support those already providing support

## Must
- [x] create a document
- [x] Document our process in order to make people trust our research
- [x] Document our evaluation of our process to help teams form processes from our learnings
- [ ] Document user research findings from experts
- [x] Document user research findings from users

**Comment by amyj2110** [comment]
Link to the findings document: https://docs.google.com/document/d/1F-zaUmG2yg-IV8lfCHPzLYx0LYuLi-h81aXn8gM6_yQ/edit?usp=sharing
