### ISSUE TITLE
Do comms for care card pattern and tweak to service standard 11

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk-service-manual#1620]
When the care card pattern goes live:
- [ ] NHS.UK and service manual public Slack channel posts - needs some explanation about why we've changed it from a component to a pattern
- [ ] Twitter - not doing Twitter this time
- [ ] @georgina to let Jenna know about service standard tweak?

**Comment by georginaplatt** [comment]
I'll wait to hear from Dom that this is released before I contact Jenna

**Comment by sarawilcox** [comment]
@georginaplatt, I think we can close this if/when you've contacted Jenna.
