### ISSUE TITLE
Compare and shift content between colour page in design system and colour guidance in accessibility

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk-service-manual#1627]
Linked to Review draft guidance on subtitles and colour and iterate #1308

On our colour page in the design system, under the heading "Colour contrast", we say: "Read more about accessibility and colour on this page" but actually link further down the same page to the accessibility section where we have some info about designing with colour. But we don't mention the specific colour ratio.

That's in our accessibility guidance on colour which we don't link to from the colour page. 

Discussed with designers in the team - we recommend keeping top level info in accessibility guidance and numbers/contrast ratio in the design system.

**Comment by henocookie** [comment]
Happy to be involved in any further discussions about placement of the guidance between the design system and accessibility sections of the service manual website

**Comment by sarawilcox** [comment]
Comment from @mcheung-nhs: On the last screenshot there is a link to WCAG concerning colour contrast. Could this link to the WCAG 2.1 rather than the 2.0 version. The newer version is https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html

**Comment by sarawilcox** [comment]
Approved by Leigh and Michael.
@danjohnstonUX, would you mind casting your eye over this on review/1-subtitles please? Just to make sure all looks OK from a design point of view. If you're happy with it, it's ready to release.

**Comment by sarawilcox** [comment]
Ready for release.
