### ISSUE TITLE
Formatting and punctuation page - small amend

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk-service-manual#1628]
Under capitalisation, change first mention of "lower case" to "sentence case" in: "We always use lower case, including page titles. The exceptions to this are proper nouns and examples in the GOV.UK style guide capitalisation list."

Lower case should not have a hyphen. Check page.

**Comment by sarawilcox** [comment]
Included in branch update-team-page. I'll let you know when it's ready for review.

**Comment by henocookie** [comment]
Included in the [v5.7.1 release](https://github.com/nhsuk/nhsuk-service-manual/releases/tag/v5.7.1)
