### ISSUE TITLE
Change wording re checkboxes none option

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk-service-manual#1642]
Comment from Michael Cheung:
One bit of advice I did like from gov.uk was in the "How to create the 'none' answer" section about not using 'none of the above' text:
"Avoid giving directions like ‘none of the above’, as this implies a visual reference that may not be relevant for users of screen-reading software. Instead, use ‘none of these’ or similar."
Maybe we could also add this advice?

**Comment by henocookie** [comment]
Current guidance for [radios](https://service-manual.nhs.uk/design-system/components/radios) in the NHS digital service manual:

> Users can't go back to having no option selected once they have selected an option, without refreshing their browser window. So you should include "None of these" or "I do not know" if they are valid options.

Current guidance for [checkboxes](https://service-manual.nhs.uk/design-system/components/checkboxes) in the NHS digital service manual:

> ### Adding an option for "none"
> You can give users the option to say none of the other options apply to them.
> 
> This option means users need to actively select "none" rather than leave all the boxes unchecked, which makes sure they do not skip the question by accident.
> 
> Remember to start by asking 1 question per page. You might be able to remove the need for a "none" option by asking the user a better question or by using filter questions to filter users out beforehand.
> 
> Show the "none" option last. Separate it from the other options using a divider, normally the word "or".
> 
> Write a label that repeats the key part of the question. For example, for the question "Do you have any of these symptoms?", say "No, I do not have any of these symptoms".
> 
> To enable some JavaScript that unchecks all other checkboxes when the user clicks "none", add the data-checkbox-exclusive behaviour to the "none" checkbox.

<hr>

@mcheung-nhs are you suggesting the guidance to be more explicit in saying what not to say, for example, "Avoid giving directions like ‘none of the above’, as this implies a visual reference that may not be relevant for users of screen-reading software. Instead, use..."?

**Comment by sarawilcox** [comment]
I've included some content about this in the "none" option section of the checkboxes page. In branch review/1-subtitles. To be released this week.

**Comment by sarawilcox** [comment]
Ready for release.
