### ISSUE TITLE
Remove beta banner from service standard

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk-service-manual#1659]
We're confident in the service standard. It's based closely on GOV which has been well tested and services have been using the NHS service standard without us seeing any major issues.

### 2 final things to do
- [x] Request the Qualtrics response data.
- [x] Check whether we've had any feedback about it via the satisfaction survey 
- [x] @georginaplatt - Contact the assurance team at NHSX to ask if they've seen anyone having any problems with it - tell them that we're proposing to move from beta to live
- [x] @sarawilcox to remove banner next time we do a release - perhaps with #1652

**Comment by georginaplatt** [comment]
Amy will look at the satisfaction survey feedback this sprint.

**Comment by georginaplatt** [comment]
Contacted Lizzy/Karina about feedback from team using the NHS service standard.

**Comment by georginaplatt** [comment]
Only received feedback from one org. Added to community backlog: - https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/343

**Comment by henocookie** [comment]
Removed the beta banner from the [NHS service standard](https://nhsuk-service-manual-usertesting-wa-dev-uks.azurewebsites.net/standards-and-technical-specifications/service-standard) and [About the NHS service standard](https://nhsuk-service-manual-usertesting-wa-dev-uks.azurewebsites.net/standards-and-technical-specifications/about-the-service-standard) pages in the **usertesting environment** alongside the work-in-progress tech specifications work

**Comment by sarawilcox** [comment]
I'm doing this in branch update-team-page. I'll send a PR when ready to check.

**Comment by henocookie** [comment]
Included in the [v5.7.1 release](https://github.com/nhsuk/nhsuk-service-manual/releases/tag/v5.7.1)
