### ISSUE TITLE
Link to involving people and communities for NHSX

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk-service-manual#1678]
We've agreed with NHSX that we'll link to this document about involving people: 
https://www.nhsx.nhs.uk/key-tools-and-info/involving-people-and-communities-in-digital-services/

Previous suggestions for placement:

- [x] It goes beyond point 1 in the service standard, which is "Understand users and their needs in the context of health and care". But I think it is relevant enough for us to link out to it from our guidance around that point. We could link to it in the resources section at the bottom of the guidance for point 1: https://service-manual.nhs.uk/service-standard/1-understand-users-and-their-needs-context-health-and-care.
- [x] I think we could also link to it from the guidance around point 5 in the service standard: "Make sure everyone can use the service": https://service-manual.nhs.uk/service-standard/5-make-sure-everyone-can-use-the-service. We could even add a bullet point to what teams should do: "involve people and communities at all stages, from strategy through design and implementation". Then link out to this document further down the page

**Comment by sarawilcox** [comment]
Link from the inclusive content principles for now, pending further work on the inclusion prototype?

**Comment by sarawilcox** [comment]
Hi @georginaplatt, I'm linking to this NHSX doc from standards 1 and 5 in the NHS service standard. Pages to be released this week.

Would someone (Snook?) be able to link to the doc from the inclusive content principles? (I might be able to if no one else can.)

**Comment by sarawilcox** [comment]
Ready for release.

**Comment by georginaplatt** [comment]
> Hi @georginaplatt, I'm linking to this NHSX doc from standards 1 and 5 in the NHS service standard. Pages to be released this week.
> 
> Would someone (Snook?) be able to link to the doc from the inclusive content principles? (I might be able to if no one else can.)

I've had no update on the Snook SOW working on the inclusive services guidance yet but will chase up @sarawilcox

**Comment by sarawilcox** [comment]
- @sarawilcox to link to it from the inclusive content principles.
- @georginaplatt to let Ellie know when we've published the links from the service standard.
