### ISSUE TITLE
Prep for GDS Services Week - Standards & Guidance Show & Tell 

### ISSUE THREAD

**Issue by georginaplatt** [nhsuk/nhsuk-service-manual#1735]
## What
The team have been asked to contribute to the Standards & Guidance Show & Tell on the 10th March.
Several teams in central government departments, local government, public sector organisations and devolved administrations are working on service and digital standards and related guidance. 

## Why
To share best practice. To share what we are doing, how we are doing it, and how our work impacts public services.

## Done when
- [x] Decided on topics to cover
- [x] Speak to Mission Team 1
- [x] Set up chat with MT1
- [x] Created slide deck
- [x] Run through
- [x] Present at Show & Tell

**Comment by georginaplatt** [comment]
Rough agenda 2hrs for 7 presenters (15 mins, 5 mins q's)

Overview of service manual & community contribution
Vision, principles & goals (2.5)

Focus on inclusive skin symptoms guidance (10 mins)

Service standard update - standards & technology, sustainability - standards & design principles 
Update on future of the service manual vision & strategy (2.5)

**Comment by sarawilcox** [comment]
If @richkelly is happy for me to do so, I might mention some of the inclusion work in our backlog - anatomical illustrations and icons for BSL and CC - depending on where they have got to.

**Comment by richkelly13** [comment]
Absolutely :) Here's the latest with BSL icons, I'm presenting to Design Huddle tomorrow
[NHS.UK Multimedia Team - BSL-Icon-Design.pptx](https://github.com/nhsuk/nhsuk-service-manual/files/8125551/NHS.UK.Multimedia.Team.-.BSL-Icon-Design.pptx)
.

**Comment by georginaplatt** [comment]
Perfect :)

I was going to lead into the focus on inclusive skin symptoms guidance by setting the scene with the goal: -

_Provide guidance on how to make NHS products and services inclusive and accessible for the diverse populations we serve_

& then show the other epics completed i.e. additional languages discovery or other teams working on i.e. inclusive services guidance, as well as other guidance in the pipeline.
