### ISSUE TITLE
Create GitHub issues for taxonomy and navigation of GP websites

### ISSUE THREAD

**Issue by georginaplatt** [nhsuk/nhsuk-service-manual#1739]
## What
Based on the meeting with NHSEI Digital First Team it would be useful to share findings on various primary care topics on GitHub.

## Why
Enable us to ask other teams to share their insights and comments with the NHSEI Digital First Team & share their research.

## Done when

- [x] Themes agreed with NHSEI
- [x] GitHub tickets created
- [x] Share links to GitHub issues with NHSEI
- [ ] Share links on NHS.UK Slack channels
- [ ] Share links on service manual public Slack channels

**GitHub tickets created for**
- [x] Helping users understand how to interact with their GP surgery
- [x] Top tasks for GP websites
- [x] Explaining "GP online services" - we could rename and use this existing issue for that: https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/234
- [x] Explaining "online consultations" (appointments)
- [x] Triage

**Comment by georginaplatt** [comment]
We already have these, which I've added NHSEI's updates & research findings to: -
[Explaining "GP online services" #234](https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/234) - I just changed the title
[Emergency alert #149](https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/149)

**Comment by sarawilcox** [comment]
You did this, didn't you, @georginaplatt? Shall we close the issue?
