### ISSUE TITLE
Add a link to NHSEI Platforms transformation blog post and Dean Vipond's Medium post from service manual blog posts pages

### ISSUE THREAD

**Issue by georginaplatt** [nhsuk/nhsuk-service-manual#1754]
## What
Add a link to blog [reusing-the-right-tools-for-the-job](https://digital.nhs.uk/blog/transformation-blog/2022/reusing-the-right-tools-for-the-job) from the service manual blog post pages.

## Why
To promote the release of Standards and technology content, promote the blog and highlight the collaboration.

Also add Dean's post(s): https://medium.com/@deanvipond/a-short-ish-history-of-the-nhs-design-system-part-1-2016-a-website-a-brand-and-a-handful-of-9fdb172e77bb

Plus Conor Rohan's recent post on NHS and GOV.UK design systems. 

## Done when
- [ ] Design input required to add image
- [x] Add link to blog from the service manual blog post pages
- [ ] Include in next release

**Comment by sarawilcox** [comment]
I'll do this when we release Content Style Council changes. I'm prioritising the standard for creating health content first.

**Comment by sarawilcox** [comment]
Drafted. In a branch for release in July. Waiting for Tosin to add 2 images.
