### ISSUE TITLE
Kick off work on a proposed design principles for sustainability

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk-service-manual#1776]
Attended an initial meeting with Maddy Whitty and Michael Norrington who are leading work on this within the NHS.UK design community.

Discussed 2 potential areas of work.

### 1 Add a new principle to the design principles
This is a relatively straightforward piece of work - defining a brief principle with the community and assuring community buy-in. In the absence of the design system working group, we need to agree what sort of governance process this would go through. Maddy and Michael to explore further with working group and to propose a principle.

### 2 Explore the possibility of adding a new sustainability standard to the NHS service standard
This could potentially be a new standard to add to the extra points for health and social care. Any extra points for health and care will need be developed with and approved by the community, in consultation with the standards and assurance team. The advantage of a service standard over a design principle is that we can then set more specific requirements with guidance for teams. We already have [an issue in the backlog for a sustainability point for the NHS service standard](https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/407). 

Longer-term, it is possible that the GOV.UK service standard will include a standard on sustainability, in which case we would update the NHS service standard to align closely to the GOV.UK service standard. 

### Next steps
- [x] Sara to talk with service manual team
- [x] Sara to set up a GitHub issue for the design principles to document the process, gather and share insight and engage with teams: https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/442
- [x] Maddy and Michael to explore a potential principle with the working group with Sara advising on content design
- [ ] Community engagement

**Comment by maddyow** [comment]
### Working group notes 22/06/22

- Revisited problems statements that derived from first working group and NHS design away day workshop
- How do we give designers the knowledge to have conversations to help their teams make educated decisions?
- What is in the designers control?
- This work should feed into the design, engineering and product maturity models (including the Tech Code of Practice)
- The principle will generate need for more detailed guidance

**Comment by sarawilcox** [comment]
Close this ticket. Being followed up in #1797.
