### ISSUE TITLE
EPIC: Tabs guidance

### ISSUE THREAD

**Issue by georginaplatt** [nhsuk/nhsuk-service-manual#1790]
## What
We've identified a need for tabs guidance for NHS websites/services, like in GOV.UK https://design-system.service.gov.uk/components/tabs/ . Cervical screening, SCRa and the 111-online team have done some work on this. 

## Why
 Tabs can be a helpful way of letting users quickly switch between related information if:

- your content can be usefully separated into clearly labelled sections
- the first section is more relevant than the others for most users
- users will not need to view all the sections at once

Tabs can work well for people who use a service regularly, for example, users of a caseworking system. Their need to perform tasks quickly may be greater than their need for simplicity of first-time use.

## Related tickets/ FE version

- [Example of the current V7 Alpha tabs (opens in CodeSandbox)](https://x45xtc.csb.app/#tab-three)
- https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/279
- FE v7 Alpha - https://github.com/nhsuk/nhsuk-frontend/discussions/827

## Must do

- [ ]  Review draft guidance and discuss with team how and when we plan this work in

**Comment by georginaplatt** [comment]
MT1 will be supporting the service manual by:
speaking to Dan Johnston to see who he has already spoken to
reaching out to teams using Tabs to gather user research evidence
creating draft guidance in google docs
designing/prototyping how this might look in the design system.

**Comment by wa-rren-dev** [comment]
Just wanted to highlight a conversation that's taking / has taken place around [tab background colours over on the Alpha 7 PR](https://github.com/nhsuk/nhsuk-frontend/pull/831#issuecomment-1212073312)

**Comment by sarawilcox** [comment]
We are looking at including tabs in v7 of the frontend with basic guidance, marked experimental, in the design system, based on GOV design system.

**Comment by anandamaryon1** [comment]
Released some time ago. Issue for discussion: https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/279
