### ISSUE TITLE
Remove page about Heroku from prototype kit

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk-service-manual#1798]
There’s a post on the design channel about Heroku now removing their free hosting https://blog.heroku.com/next-chapter - this impacts a lot of designers who use the prototype kit
We have specific heroku guidance on the prototype kit in the how to guides https://nhsuk-prototype-kit.azurewebsites.net/docs/how-tos/heroku
Wondered it it was possible to delete it? I’ve suggested a group of designers form a working group to find a viable replacement

**Comment by sarawilcox** [comment]
@wa-rren-dev, can you help, please? See Slack thread. https://nhsuk.slack.com/archives/G01FDHHLQ49/p1661520634443599?thread_ts=1661519210.154039&cid=G01FDHHLQ49

**Comment by wa-rren-dev** [comment]
Yep I've put it on my list 👍

**Comment by sarawilcox** [comment]
@wa-rren-dev, can we close this? 

I've put a ticket in the backlog to consider if we need to give people an alternative to Heroku. But I don't think that's a quick thing to agree. We've still go the page about Heroku, haven't we, if we wanted to republish an alternative version? https://github.com/nhsuk/nhsuk-service-manual/issues/1805
