### ISSUE TITLE
Fix bulleted list on expander page

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk-service-manual#1807]
https://service-manual.nhs.uk/design-system/components/expander

The bulleted list in When not to use an expander doesn't read right. Needs tweaking.

**Comment by wa-rren-dev** [comment]
@sarawilcox Would you be happy with the attached?

![image](https://user-images.githubusercontent.com/6341474/195603385-47e8c497-4208-4cd3-a6e9-f1e693a2e612.png)

**Comment by wa-rren-dev** [comment]
PR is here if you are! https://github.com/nhsuk/nhsuk-service-manual/pull/1811/files

**Comment by sarawilcox** [comment]
Nice, thanks.
