### ISSUE TITLE
Note change of phone no in next release (to coincide with v6 update)

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk-service-manual#1815]
On this page: https://service-manual.nhs.uk/content/a-to-z-of-nhs-health-writing#phone-and-phone-numbers
We have the phone number: 07771 900 900

Turns out it’s an actual real phone number.  07700 900 866 is usable from Ofcom’s TV and Drama range for things like this and have tested it.

If we can release this change ASAP, I'll note it in the What's new next time we do a major release.

**Comment by wa-rren-dev** [comment]
@sarawilcox I'll get this out ASAP!

**Comment by sarawilcox** [comment]
Update to What's new added into branch feature/back-link-button. Awaiting release.

**Comment by sarawilcox** [comment]
Published.
