### ISSUE TITLE
Update prototype kit with replacement for Heroku

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk-service-manual#1824]
Now that the free version of Heroku has come to an end, teams are asking what to use instead. NHS.UK has a working group looking at this.

**Comment by DBarker3** [comment]
This is on holding, pending a decision on the internal working group with the benefits of each service.

**Comment by sarawilcox** [comment]
New ticket for VS alongside Atom: https://github.com/nhsuk/nhsuk-service-manual/issues/1838

**Comment by sarawilcox** [comment]
Draft, based on working group recommendations, sent for review.

**Comment by sarawilcox** [comment]
PR: https://github.com/nhsuk/nhsuk-prototype-kit/pull/244 - awaiting approval and deployment. Recommending Heroku (paid for version) and Railway for publishing prototypes and recommending VS Code rather than Atom for HTML text editor.
