### ISSUE TITLE
Create a partial view for the 'Get in touch' section

### ISSUE THREAD

**Issue by AdamChrimes** [nhsuk/nhsuk-service-manual#183]
The 'Get in touch' section on component pages is duplicated across each of the components pages, rather than having the code duplicated multiple times, we could have a single partial view included on each of the pages.

This would save us time having to update each of the component pages if the get in touch details ever changed.

**Comment by sarawilcox** [comment]
It's on many other pages of the site too.

**Comment by AdamChrimes** [comment]
This is going to be picked up as part of the service manual redesign.
