### ISSUE TITLE
Review findings of service manual discovery and consider roadmap

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk-service-manual#1882]

**Comment by Moll-Lee** [comment]
This work has been completed and has highlighted some key priorities for a service manual team to start work on. I have included the problem statements of the two main priorities below based on the user needs identified in the snook work. 

**Improving guidance on user research** 
Users need more guidance in providing research and research methods in a health care context. Currently there is information for user researchers on the NHS service manual. However, there isn’t a key place for user researchers to look to make sure they are undertaking their work in an assured way. Undertaking user research in a healthcare setting needs to consider practices and standards that are specific to healthcare. We need to understand how we can better meet our user research community's needs.
Some of this information is already available on the service manual so it may require some collation and IA work.

**Enhancing clinical and professional facing services.**
Currently a lot of the components within the design system have been developed for public and patient facing services. 
Clinical or admin facing services sometimes have different needs, for example clinician facing services may need to have more information on a screen than we would recommend for public facing services. 
There is a risk that, by not providing components for clinical and admin facing services, creators and providers of these services will not work in a way that allows for transformation at scale. 

We will separately also be looking at a number of other pieces of work including 'ensuring the service manual and design system is fully WCAG.2.2 compliant. 
the next steps for this work are to work with the inclusive design team to scope out resource and budget required and work to agree a finalised roadmap for the upcoming service manual and design system work.
