### ISSUE TITLE
Fix NHSD API broken link

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk-service-manual#1951]
https://service-manual.nhs.uk/standards-and-technology/service-standard-points/17-make-your-service-interoperable

This link is broken: https://developer.nhs.uk/apis. Should it link to https://www.api.gov.uk/nd/#nhs-digital or is there an NHSE space?

**Comment by frankieroberto** [comment]
@sarawilcox seems to no longer be broken but redirects to https://digital.nhs.uk/developer/api-catalogue - I’ve updated the link in #1987.
