### ISSUE TITLE
Update default page template examples so default shows a heading inside a grid column

### ISSUE THREAD

**Issue by edwardhorsford** [nhsuk/nhsuk-service-manual#1969]
The [default page template example](https://service-manual.nhs.uk/design-system/styles/page-template) does not include a grid row or column, and just has a heading inside of `main`.

I don't think services should **ever** do this. Pretty much all content should be within a 2/3 column - or at least one of the other grid columns. They should never have a heading inside main like that.

My suggestion would be to:
* Update the default page template example to include a grid row and 2/3 column, with size `l` heading inside of it.
* Update the customised page template example to include a more complex grid column arrangement.

Note the NHS example is pretty similar to the [GOV.UK example](https://design-system.service.gov.uk/styles/page-template/#default). I've suggested on cross gov slack that it would be good for the default to change there too.

**Comment by anandamaryon1** [comment]
Released as part of v7.0.0: https://github.com/nhsuk/nhsuk-service-manual/pull/2040
