### ISSUE TITLE
Fix alphabetisation of components listing

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk-service-manual#1971]
I've just realised that character count and checkboxes are back to front in the alphabetical list of components in the side nav.

I wonder if someone would be able to fix it, please? https://service-manual.nhs.uk/design-system/components
(@roshaanbajwa, would you have time?)

![Screenshot 2024-05-20 at 14 51 02](https://github.com/nhsuk/nhsuk-service-manual/assets/45792959/bf705d30-21ee-451f-bcfa-ac8143ff6e25)

**Comment by frankieroberto** [comment]
@sarawilcox doh, well spotted! Fix here: #1972.
