### ISSUE TITLE
Design example 'Open in new window' link

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#548]
### What
On the design examples, the link 'Open in new window' gives no context of what you are opening in a new window. 

<img width="682" alt="Screenshot 2020-02-06 at 11 06 45" src="https://user-images.githubusercontent.com/14331000/73932285-ed034280-48d1-11ea-8957-423ca882361b.png">

### Why
It's an accessibility issue, especially when there is more than one design example on the page.

### Fix
Add visually hidden text to the the link. 

For example: 'Open this [style, component or pattern name] example in a new window'.

**Comment by AdamChrimes** [comment]
This was released in v3.0.4
