### ISSUE TITLE
Small suggestion for coronavirus entry

### ISSUE THREAD

**Issue by cjforms** [nhsuk/nhsuk-service-manual#598]
Thank you for publishing this entry so quickly. 

Currently, you have: "Coronavirus is the virus that causes the illness COVID-19. Coronavirus is lower case." The problem is that the second sentence has Coronavirus in upper case as the word happens to be at the start of a sentence.

My suggestion is to change this so that the second 'coronavirus' doesn't start the sentence, such as:
"Coronavirus is the virus that causes the illness COVID-19. Write coronavirus in lower case."

**Comment by sarawilcox** [comment]
Thanks @cjforms. Good suggestion. I'll try and get that done over the next day or two.

**Comment by sarawilcox** [comment]
Thanks for making the change @iahmed5. If you can make open a pull request against our repo, we'll action it.

**Comment by sarawilcox** [comment]
Connected to issue #228

**Comment by cjforms** [comment]
Thanks everyone
