### ISSUE TITLE
Warning callout - aria-label="Important"

### ISSUE THREAD

**Issue by mgifford** [nhsuk/nhsuk-service-manual#635]
I'm not sure that this is a best practice. If it is, I'm not sure why it isn't in the HTML example provided https://service-manual.nhs.uk/design-system/components/warning-callout

I'm pretty sure that the aria-label would sound much like:
`<h3 class="nhsuk-warning-callout__label">Important: School, nursery or work</h3>`

and not provide any additional semantic meaning for screen reader users. Just looking at the definitions & examples here:
  https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-label_attribute

As you probably know, there's lots of discussion about labels here https://github.com/alphagov/govuk-design-system-backlog/issues/71

**Comment by davidhunter08** [comment]
Thanks @mgifford.

We're currently looking into this with the NHS.UK frontend https://github.com/nhsuk/nhsuk-frontend/pull/630

Once we're happy with the solution, we'll release the code and update the guidance on the service manual.

**Comment by davidhunter08** [comment]
Closed issue because of [issue 664](https://github.com/nhsuk/nhsuk-service-manual/issues/664)
