### ISSUE TITLE
Draft card component guidance

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#661]
## What

Add guidance for the card component to the design system.

## Why

The card component is being released in NHS.UK frontend v4.0.0.

## Further details

The guidance is to include:
- basic card
- clickable card
- card with an image
- group of cards
- accessibility
-- how to change heading level
-- how to change heading size

## Done when

- [x] add code examples
- [x] draft guidance
- [x] add to the navigation and search index
- [x] content review - @sarawilcox 
- [x] peer review

**Comment by davidhunter08** [comment]
@sarawilcox - [examples for the card component](http://nhsuk-design-system-testing.herokuapp.com/draft-guidance/card)

**Comment by sarawilcox** [comment]
Content reviewed. We still need to make a decision about full stops in cards as practice varies. We can publish in the meantime though.

**Comment by davidhunter08** [comment]
The code examples will get added and reviewed as a part of this [issue 734](https://github.com/nhsuk/nhsuk-service-manual/issues/734)
