### ISSUE TITLE
Draft tag component guidance

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#662]
## What

Add guidance for the tag component to the design system.

## Why

The tag component is being released in NHS.UK frontend v4.0.0.

## Done when

- [x] add code examples
- [x] draft guidance
- [x] add to the navigation and search index
- [x] content review - @sarawilcox 
- [x] peer review

**Comment by davidhunter08** [comment]
@sarawilcox - [examples for the tag component](http://nhsuk-design-system-testing.herokuapp.com/draft-guidance/tag)

**Comment by sarawilcox** [comment]
Content reviewed. This looks good!

**Comment by davidhunter08** [comment]
The code examples will get added and reviewed as a part of this [issue 734](https://github.com/nhsuk/nhsuk-service-manual/issues/734)
