### ISSUE TITLE
Draft responsive table guidance

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#663]
## What

Add guidance for the responsive table component to the design system.

## Why

The responsive table component is being released in NHS.UK frontend v4.0.0.

## Done when

- [x] speak to @Fenwick17 regarding draft content
- [x] add code example
- [x] draft guidance
- [x] need to consider guidance for the research section
- [x] content review - @sarawilcox 
- [x] peer review

**Comment by davidhunter08** [comment]
@sarawilcox - [example of the responsive table component](https://nhs-responsive-tables.herokuapp.com/tables/medications)

**user:** nhsuk
**pass:** tables

**Comment by sarawilcox** [comment]
Content reviewed. A few changes made.

**Comment by davidhunter08** [comment]
The code examples will get added and reviewed as a part of this [issue 734](https://github.com/nhsuk/nhsuk-service-manual/issues/734)
