### ISSUE TITLE
Update warning callout guidance with 'custom heading' variant

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#664]
## What

The warning callout has been updated so that custom headings get prefixed with `<span class="nhsuk-u-visually-hidden">Important:</span>` to convey the importance of the message to screen reader users. 

## Related issue

[Issue 635](https://github.com/nhsuk/nhsuk-service-manual/issues/635)

## Related pull request

[Frontend PR 630](https://github.com/nhsuk/nhsuk-frontend/pull/630)

## Done when

- [x] add code example
- [x] draft guidance
- [x] content review - @sarawilcox 
- [x] peer review

**Comment by sarawilcox** [comment]
Reviewed content and suggested changes. Note, I've consulted Kim and Mark. Let's see what they say.
