### ISSUE TITLE
EPIC: Alignment of Service Manual Development with NHSx Planned Work

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#677]
## What

This covers the work that NHS X are planning to do, relating to the NHS digital service manual.

## Why

This is to ensure the priorities of the work the service manual team are delivering align with the vision from NHS X.

## Outcome

Plan of action agreed for the next twelve months (21/22) with overview of the issues needed to be supported to align work with complimentary work being planned/undertaken by NHS X teams.

**Comment by lucyha** [comment]
For our ongoing work with NHS X, please see EPIC: Implement service manual engagement strategy #878
