### ISSUE TITLE
EPIC: Identify form design patterns we need

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#681]
## What

Review the need for and, if appropriate, publish more form design patterns in the design system. 

## Why

We published [guidance on how to write good questions for forms](https://service-manual.nhs.uk/content/how-to-write-good-questions-for-forms) in 2019 but we recognised at the time that there was also a need for more form design patterns to help interaction designers build forms that are easy to use. Our forms guidance currently focuses on content design.

## Must
- meet to review our need for different form patterns, for example, check your answers, confirmation page, and stop users to tell them important information pattern
- consider how these patterns help users understand where in the process they are and give them a greater sense of control (see Caroline's forms topic map document)
- prioritise the patterns we identify
- put tickets in the backlog for future RICE scoring

**Comment by lucyha** [comment]
These will be identified in the community backlog
