### ISSUE TITLE
Improve the design code snippet feature

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#701]
## What

Improve the design example code snippet feature used for design styles, components and patterns.

- [ ] Add the ability to show Nunjucks macro table (Currently found in the README for each component)
- [ ] Add a file to the frontend library for the Nunjucks arguments to be read by the service manual eg. https://github.com/alphagov/govuk-frontend/blob/master/src/govuk/components/accordion/accordion.yaml
- [x] Change nunjucks documentation to use `[]` for array, not `{}` https://github.com/nhsuk/nhsuk-frontend/issues/604
- [x]  Fix close bug
- [x] Fix the HTML errors reported on the service manual because of code snippets
- [ ] Refactor code examples logic to be cleaner
- [ ] Review the use of Highlight.js (currently outdated - they've dropped support for IE11)
- [ ] Refactor the styles for the single line and code block highlighting (`.rich-text code`)

## Why

There is a small bug with not being able to close the code snippet when selecting the tab links.

There is also no information for Nunjucks macro options so users are unsure of what the options are for each macro.

**Comment by AdamChrimes** [comment]
Add the ability to show Nunjucks macro table (Currently found in the README for each component)
Fix the HTML errors reported on the service manual because of code snippets

**Comment by chrimesdev** [comment]
There are a few inconsistencies with the wording in the Nunjucks arguments table, try to enforce some consistency.
