### ISSUE TITLE
Community contribution project kick-off workshop

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#706]
## What

Run a project kick-off workshop for community contributions.

## Why

To create a shared understanding of the problem and assumptions we have for community contributions.

## Further details

**Invitees:** Service manual team
**Duration:** 2 hours
**Location:** Online - with this [Miro board](https://miro.com/welcomeonboard/YaZHab4xqrGNEze0AU9Bw1hSk42PAdsvAWCs4VdsZRFBzWwnuxFN713zUrA9Ao0m)
**Date/Time:** Tuesday 13th October, 10:30am - 12:30pm

## Done when

- [x] schedule workshop
- [x] prep workshop
- [x] run workshop
- [x] write-up outcomes and next steps

**Comment by Tosin-Balogun** [comment]
# Workshop Outcomes | 13-Oct-2020

The team held a workshop to find out what needs to be done to progress the work on community contributions to the service manual.

The team made some adjustments to the problem statement but felt more research was needed.

The top ideas to **measure success were;**
1. Monitoring GitHub activity
2. Getting user satisfaction feedback
3. Issue ownership, types of contributions, user insights and the expansion of the community beyond the core.

After collecting some assumptions, the team identified a need for more **research to validate;**
- [ ] 1. Why users don’t know how to contribute
- [ ] 2. Why users have problems using GitHub
- [ ] 3. What motivate users to contribute
- [ ] 4. Why there is lack of leadership support for contributions

and that we needed to think about;
- [ ] How to solve users not having enough time to contribute
- [ ] How to support users with low confidence
- [ ] How to communicate the purpose of the service manual
- [ ] How to encourage contributions from the user research community

These will be tackled by a series of interviews, surveys and hotjar polls by @amyj2110 & @henocookie , along with audits from different data sources.
