### ISSUE TITLE
Plan user research activities based on outcomes of the project kick-off workshop

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#708]
## What

Plan user research activities based on outcomes of the project kick-off workshop

## Why

We need to validate our assumptions for community contribution with user research.

## Depends on

[Community contribution project kick-off workshop #706](https://github.com/nhsuk/nhsuk-service-manual/issues/706)

**Comment by henocookie** [comment]
We have planned to conduct a survey, interviews and usability testing to validate and invalidate the team's assumptions for the theme of community contribution
