### ISSUE TITLE
Complete desk research into online communities, collaboration and contributions

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#709]
## What

Conduct desk research into online communities, collaboration and contributions.

## Why

Looking at what others have done will help shape our thinking.

## Relates to
EPIC: Community contribution #685

## Done when

- [x] [compiled research](https://github.com/nhsuk/nhsuk-service-manual/wiki/Community-contributions)
- [x] Research summarised in a presentable format to share with the team

**Comment by cjforms** [comment]
Please consider joining the new co-design slack. It's open to everyone who is interested in co-design and I consider that includes the collaborative design of design systems and service manuals. 

There's a brief introduction in this blog post: https://www.effortmark.co.uk/hello-co-design-community/

It's open to

**Comment by amyj2110** [comment]
Up-to-date desk research findings can be found in our Wiki.

[Community, collaboration and contribution desk reserarch](https://github.com/nhsuk/nhsuk-service-manual/wiki/Community-contributions)

**Comment by henocookie** [comment]
Attended an interesting discussion at GovCamp North about "how open is enough?" that fits some themes around the community and how open things should be. Notes from the session: https://docs.google.com/document/d/1a9cyNyPLEx_GEdZbWAnoVTgrCybsCkPtzwLCJe_pv4A/edit
