### ISSUE TITLE
Plan the dates and activities for style council for remainder of 2020

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#712]
## What
Plan monthly Style Council meetings between now and December 2020, including one meeting to prioritise GitHub content issues

## Why
To get the content community together again and into the swing of:
- raising style issues 
- prioritising them
- sharing user insight
- discussing them and making decisions

So that we can update the style guide

## Done when

- [x] update mailing list
- [x] arrange Teams meeting for first meeting 
- [x] sent out meeting invites
- [x] set agendas

**Comment by sarawilcox** [comment]
Some live and pressing issues:
- Hyphens: https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/206
- Contractions: https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/266

**Comment by sarawilcox** [comment]
Note also that Test and Trace may propose testing content style changes for urgent approval.

**Comment by sarawilcox** [comment]
**Style Council meeting dates:**
1st meeting - Wednesday 4 November, 2 to 3.30pm - Lucy's sending out an invitation today
2nd meeting - I'm proposing that we do the GitHub content issue prioritisation exercise on Tuesday 24 November, 2 to 3.30pm. That works for Dave, Tosin and me.
3rd meeting - Wednesday 9 December, same time of day - a fortnight after the prioritisation exercise - with a focus on contribution and creating a core content style team

**Comment by sarawilcox** [comment]
See also ticket: https://github.com/nhsuk/nhsuk-service-manual/issues/747 Prep for 4 Nov Style Council meeting.

**Comment by sarawilcox** [comment]
Also https://github.com/nhsuk/nhsuk-service-manual/issues/748 Rationalise GitHub content issue backlog
