### ISSUE TITLE
Agree on support for Sara with Style Council meetings

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#713]
## What

Agree on support for Sara with the style council meetings.

## Why

The current process is solely reliant on Sara and she could do with some support.

## Further details
Team meeting Wednesday 21 October, 10am.

## Done when

- [ ] review current process
- [ ] brainstorm ideas

**Comment by sarawilcox** [comment]
See Jira for post-it exercise: https://jira.service.nhs.uk/browse/STAN-1628

**Comment by sarawilcox** [comment]
Arranged meeting for Wednesday 21 October.

**Comment by sarawilcox** [comment]
Discussed:
- help with updating mailing list and arranging meetings - Lucy
- help with GitHub prioritisation exercise - Dave and Tosin
- sorting out GitHub content issue backlog - Henry

We'll talk further with the content profession about support with content style processes and Style Council meetings at December Style Council meeting.
