### ISSUE TITLE
Speak to the GOV.UK Design System team about their approach for measuring the value

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#715]
## What

Speak to the GOV.UK Design System team about their approach for measuring the value

## Why

The GOV.UK Design System team recently did an exercise on measuring the value of their design system and we could potentially learn a lot from them.

## Further detail

Tim Paul's talk: [Measuring the value of the GOV.UK Design System](https://www.youtube.com/watch?v=eSkVtSEAe98&t=4s)

**Comment by henocookie** [comment]
Received some interesting feedback from some of the GOV.UK Design System team members regarding measuring value.

They recommend some techniques could be replicated for the NHS digital service manual, such as finding out how much time was spent in the research, design and development of a style, component or pattern, and then multiplying this by the number of teams using it for a simple time metric of how a Design System offers value.

However, they also provided useful feedback that some parts of a Service Manual and Design System are much harder to analyse and "show" value for, such as the community and interactivity between users that a Service Manual and Design System can provide.

**Comment by henocookie** [comment]
### Next steps 

- [ ] Feedback the GOV Design System catchup session findings to the whole Service Manual team
- [ ] Ask the GOV Design System team if they continue to work on any of their work to show the value of the GOV Service Manual and Design system
- [ ] Agree as a team what (if any) ways of working we want to try and replicate for this topic following the feedback provided by the GOV Design System team

**Comment by henocookie** [comment]
> Ask the GOV Design System team if they continue to work on any of their work to show the value of the GOV Service Manual and Design system

Tim Paul advised that the "measuring value" work that GDS previously completed was "more of a one-off" and that "some of the data [we] used would currently be very hard to sample regularly".

Tim recommended the "best, easy-to-measure data point we have for growth is Downloads of GOV.UK Frontend from NPM". I believe @AdamChrimes has done something similar with the NHS.UK frontend previously. However, this is "by no means perfect - it doesn't really give us a sense of absolute usage"
