### ISSUE TITLE
Community contribution user research

### ISSUE THREAD

**Issue by amyj2110** [nhsuk/nhsuk-service-manual#716]
## What
User research activities for community contribution. 
## Why
To better understand why people contribute, why they don't contribute, understanding of the contribution process and how we can encourage contribution to the service manual.
## Relates to
https://github.com/nhsuk/nhsuk-service-manual/issues/685
## Depends on
https://github.com/nhsuk/nhsuk-service-manual/issues/709
https://github.com/nhsuk/nhsuk-service-manual/issues/718
https://github.com/nhsuk/nhsuk-service-manual/issues/717
https://github.com/nhsuk/nhsuk-service-manual/issues/719
## Who needs to know about this
User researchers @henocookie @amyj2110 , service manual team
## Done when
Tasks we need to do:
- [ ] [Survey](https://github.com/nhsuk/nhsuk-service-manual/issues/718)
- [ ] [User interviews](https://github.com/nhsuk/nhsuk-service-manual/issues/717)
- [ ] Usability test of current contribution process

**Comment by henocookie** [comment]
Related tasks to this issue have been re-organised and link to the community contribution EPIC: https://github.com/nhsuk/nhsuk-service-manual/issues/685
