### ISSUE TITLE
Plan and distribute community contribution survey

### ISSUE THREAD

**Issue by amyj2110** [nhsuk/nhsuk-service-manual#718]
## What
Plan a survey to gather responses to help us understand:

- who has contributed to the service manual
- what do people understand by a "contribution"
- motivations to contribute or not contribute
- expectations of service manual team involvement

Survey link: https://nhsdigital.eu.qualtrics.com/jfe/form/SV_5szVfoxZIW7Kr1b

## Why
To prepare a survey to gather feedback to create a better contribution experience.

## Relates to
EPIC: Community contribution #685

## Depends on
- Henry to get started using Qualtrics

## Who needs to know about this
Users - for recruitment purposes.
Team - for designing purposes.

## Done when
Tasks we need to do:
- [x] Write the survey
- [x] Distribute

**Comment by henocookie** [comment]
Survey content checked with @sarawilcox 

Shared on the NHS.UK, NHS digital service manual and UK Government Digital Slack spaces
