### ISSUE TITLE
STYLES: Page templates

### ISSUE THREAD

**Issue by lucyha** [nhsuk/nhsuk-service-manual#721]
## What
Add page templates to the styles section of the service manual. 

## More info
Similar to https://design-system.service.gov.uk/styles/page-template/

Two page templates:

- Default content: https://nhsuk-prototype-kit.azurewebsites.net/templates/start-page
- Transactional: https://nhsuk-prototype-kit.azurewebsites.net/templates/blank-transactional

Note about:
- reduced spacing on the main element - link to this new page from the layout guidance where we include this
- smaller heading level sizes (general rule of thumb is 1 down) - do we need documentation about this on typography?
- back link - link to the back link component

**Comment by lucyha** [comment]
Page templates could also include meta data such as open graph https://confluence.service.nhs.uk/pages/viewpage.action?spaceKey=CIT&title=Minimum+metadata+standards+for+search+engine+optimisation+and+social+sharing+-+DRAFT

**Comment by davidhunter08** [comment]
https://github.com/nhsuk/nhsuk-service-manual/pull/817

**Comment by davidhunter08** [comment]
Review complete https://github.com/nhsuk/nhsuk-service-manual/pull/817#pullrequestreview-548489006

**Comment by davidhunter08** [comment]
@sarawilcox Do you want to review this before we get together and discuss it?

**Comment by sarawilcox** [comment]
Sorry @AdamChrimes @davidhunter08 Could you spend 5 mins, maybe after a standup, taking me through this, please?

**Comment by davidhunter08** [comment]
Next steps:
- [ ] Update page template in the the prototype kit
- [ ] Add 'Changing template content' to guidance

**Comment by davidhunter08** [comment]
## To do 

On the ‘Page template’ page:

- [ ] Code syntax highlighter 
- [ ] Hide code tabs on ‘exploded view’ example
- [ ] Header JavaScript not working on ‘Content page template’ example

Could you look at these please @AdamChrimes

**Comment by davidhunter08** [comment]
- [ ] app container width

cc @AdamChrimes

**Comment by davidhunter08** [comment]
PR ready for a content review @sarawilcox 

https://nhsuk-service-manual-pr.azurewebsites.net/design-system/styles/page-template

![page-template-guidance](https://user-images.githubusercontent.com/14331000/108361507-7f7b3900-71ea-11eb-8a35-6c5a8f74c5ca.png)

**Comment by sarawilcox** [comment]
Comments sent via Slack.
