### ISSUE TITLE
Tie up guidance on list under Typography and in content style guide

### ISSUE THREAD

**Issue by lucyha** [nhsuk/nhsuk-service-manual#724]
## What

The Typography section doesn't mention the full sentence bullet lists. Link the 2 sections:

- https://service-manual.nhs.uk/design-system/styles/typography#lists
- https://service-manual.nhs.uk/content/formatting-and-punctuation#lists

**Comment by lucyha** [comment]
Hi David Hunter, I've put in a PR for a bit of text to bring the Typography section into line with the content style guide and to link to it.

But I notice that the example under numbered lists is the quick brown fox one. Would it be possible to change it to the example in the content style guide so that it shows people a real example?

**How to gargle with salt water:**

1. - Dissolve half a teaspoon of salt in a glass of warm water.
2. - Gargle with the solution then spit it out – don't swallow it.
3. - Repeat as often as you like.

I wonder if we could also include a real example of a bulleted list (rather than apples and oranges), like this: 

Symptoms can include:

- tiredness and lack of energy
- shortness of breath
- noticeable heartbeats (heart palpitations)
- pale skin

**Comment by davidhunter08** [comment]
Ready for review @sarawilcox https://github.com/nhsuk/nhsuk-service-manual/pull/859
