### ISSUE TITLE
Update image guidance page

### ISSUE THREAD

**Issue by lucyha** [nhsuk/nhsuk-service-manual#727]
## What

This page: https://service-manual.nhs.uk/design-system/components/images says this: We are working on more guidance about when to use images. We expect to publish it in spring 2019.

Also link to accessibility guidance on images.

**Comment by lucyha** [comment]
Change made - PR https://github.com/nhsuk/nhsuk-service-manual/pull/634

Still to do changelog, what's new and update page date when I've checked it in staging.

**Comment by davidhunter08** [comment]
Hi @sarawilcox, it looks like the work has already been done. Is that right?

See merged pull request: https://github.com/nhsuk/nhsuk-service-manual/pull/634

**Comment by sarawilcox** [comment]
PR: https://github.com/nhsuk/nhsuk-service-manual/pull/868
