### ISSUE TITLE
Put out a call for content designers to support contribution and content Style Council

### ISSUE THREAD

**Issue by lucyha** [nhsuk/nhsuk-service-manual#746]
## What
Set up a team of content designers to support content style guide contributions, facilitate Style Council meetings and help publish style guide updates.

## Why
Current processes for facilitating content contributions and managing Style Council processes are very reliant on Sara. By setting up a core content style team, we hope to:
- make the process more open, engaging and collaborative
- continue to develop the style guide at pace 
- provide some cover and support for Sara
- provide development opportunities for staff who are interested

## Done when
- [ ] Have a list of interested people

## Next steps
-  [Hold meeting with core content style team to agree roles and responsibilities/rota](https://github.com/nhsuk/nhsuk-service-manual/issues/796)

**Comment by sarawilcox** [comment]
Part of [EPIC: Reboot Content Style Council #687](https://github.com/nhsuk/nhsuk-service-manual/issues/687)
