### ISSUE TITLE
Establish if there's a need for guidance on metadata in the service manual

### ISSUE THREAD

**Issue by lucyha** [nhsuk/nhsuk-service-manual#762]
## What
Include some content in the service manual about metadata.

## Further details
There is a page in Confluence for internal use but it's equally valid for external use too and very relevant to SEO. https://confluence.service.nhs.uk/display/CIT/Minimum+metadata+standards+for+search+engine+optimisation+and+social+sharing+-+DRAFT

## Tasks

**Comment by sarawilcox** [comment]
This hasn't come up as an issue since the issue was opened. I'm proposing that we close it.
