### ISSUE TITLE
Research & review contribution guidance from other design systems

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#775]
## What

Research & review contribution guidance from other design systems.

## Why

Looking at other design systems contribution guidance might give us ideas for how to improve our own guidance.

## Further information

Possible design systems to look at include:
- GOV.UK Design System
- Australian GOV Design System
- Carbon Design System

## To do

- [x] Map out examples
- [x] Summarise findings
- [x] Share with the team

**Comment by Tosin-Balogun** [comment]
This work is completed? @davidhunter08

**Comment by davidhunter08** [comment]
## GOV.UK Design System
[https://design-system.service.gov.uk/](https://design-system.service.gov.uk/)

### Navigation (links)

- Contribution guidance lives in ‘[Community](https://design-system.service.gov.uk/community/)’
- Links to “share your research or feedback on GitHub” and “propose a change” appear at the bottom of each [component and pattern page](https://design-system.service.gov.uk/components/accordion/)

### Community page

- “The GOV.UK Design System is for everyone” … “strong cross-government community behind it”
- Includes a set of ‘[Community principles](https://design-system.service.gov.uk/community/)’ (co-created with the community) that covers:
  - Ways of working
  - “Start with what exists”
  - “Contribute back to help others”
  - “Think beyond your service”
  - “Reach out to the community to ask questions”
  - “Encourage others to contribute”
  - “Promote awareness of existing work whenever possible”
- What to share
  - “contribute evidenced-based changes”
  - “research findings and examples”
  - “Be honest about the amount and nature of your research and findings”
  - “what works and what does not”
- When to share
  - “Share work in progress as early as possible”
- Reasons for sharing
  - “Prioritise sharing components and patterns in the GOV.UK Design System and community backlog. This makes them easier to find and reduces duplication of effort.”
  - “see what colleagues in other departments have done before”
  - “learn from others’ mistakes”
- How to behave
  - “Be kind”
  - “Encourage others”

## Guidance covers

- The [design system working group](https://design-system.service.gov.uk/community/design-system-working-group/), including “why it exists” and “how to join”
- [Propose a component or pattern](https://design-system.service.gov.uk/community/propose-a-component-or-pattern/)
- [Develop a component or pattern](https://design-system.service.gov.uk/community/develop-a-component-or-pattern/)
- [Propose a content change using GitHub](https://design-system.service.gov.uk/community/propose-a-content-change-using-github/)
- [Contribution criteria](https://design-system.service.gov.uk/community/contribution-criteria/)

## Notes 

- GitHub only mentioned in the “Propose a content change using GitHub” guidance
- No mention of fixing / reporting bugs or the prototype kit
- All guidance is for a design system (obviously) so doesn’t cover for contributing to a content style guide or other guidance (eg: accessibility guidance)

**Comment by davidhunter08** [comment]
## Australian Government Design System

[https://designsystem.gov.au/](https://designsystem.gov.au/)

## Navigation (links)

- Contribution guidance lives within '[Community](https://designsystem.gov.au/community/)'

### Community page

- "Together we‘ll be able to build products and services better, faster and easier."
- Encourages you to "Join in the community today"
- Tells people that joining the community "is a great chance to":
  - "collaborate" 
  - "share" 
  - "get help"
- Has link to Slack - "Talk to us on Slack"
- Shares the design system's "Vision"
- Explains how it all works
  - Open source
  - Maintained
  - Transparent
  - Collaborative
- Groups the links to "How you can contribute"
  - Help with design
    - Suggest a component
    - Suggest a template
  - Help with planning
    - Community support
    - Roadmap discussions
  - Help with code
    - Code contribution guide
    - Report an issue
  - Help with usability
    - Component discussions
    - Provide research findings

**Comment by sarawilcox** [comment]
Interesting the "help with planning" section - a bit like our prioritisation exercises but going further into roadmap discussions.

**Comment by davidhunter08** [comment]
## Carbon Design System (IBM)

[https://www.carbondesignsystem.com/](https://www.carbondesignsystem.com/)

### Navigation (links)

- Contribution guidance lives within '[Contributing](https://www.carbondesignsystem.com/contributing/overview)'

## Contributing page

- "Interested in contributing to Carbon? This design system is the result of community contributions, large and small—of code, design, ideas, and guidance. Here’s how you can contribute too."
- "Contributions are not limited to code. We also encourage feedback, documentation, new designs, and tools."
- Has a section on "Working in the open"
- Mentions "Carbon lives on GitHub" and that "you’ll need a public GitHub account to contribute"
- Talks about when to contribute - "we encourage you to open an issue as early as possible in the process"
- Offers support with GitHub, linking to external video tutorials - "If working with GitHub sounds like a lot, check out this free video series. It’s one of our favorite resources."
- Outline the structure of the community
  - Users
    - Users are members of the community who use Carbon guidelines, assets, and tooling. Anyone can be a user, and we encourage users to participate in the community as much as possible.
  - Contributors
    - Contributors are members of the community who contribute to Carbon in a material way. Anyone can be a contributor.
  - Maintainers
    - Maintainers are members of the community who are committed to the success of individual Carbon projects. 
- "Project workflow" - links to external guidance on "[forking projects](https://guides.github.com/activities/forking/)"

## Guidance covers

- Bugs and requests
  - Checking for known issues
  - Creating an issue
  - Requests for comment
  - Need more help?
- Documentation
  - Editing pages
  - Making regular content updates
  - Content and style guidelines
- Components
  - First steps to contributing
  - Documentation templates
  - Parts of a component contribution

**Comment by davidhunter08** [comment]
> Interesting the "help with planning" section - a bit like our prioritisation exercises but going further into roadmap discussions.

Really interesting. It's a forum type section (essentially a GitHub issue surfaced in the user interface) in the design system where they encourage members the community to propose and discuss the direction of the Design System. https://community.digital.gov.au/t/roadmap-discussion/68/6
