### ISSUE TITLE
Complete desk research into the size and structures of other design working groups

### ISSUE THREAD

**Issue by henocookie** [nhsuk/nhsuk-service-manual#781]
## What
Find out how other design working groups at other organisations run.

## Why
So we know what to aim for when creating a design working group for the NHS digital service manual.

## Relates to
EPIC: Create a design system working group #666 

## Depends on
- Other design working groups existing
- Other groups working in open ways for us to be able to observe

## Who needs to know about this
User researchers @henocookie  @amyj2110 , service manual team

## Done when
Tasks we need to do:
- [x] Compile research
- [x] Document findings in a presentable format

**Comment by davidhunter08** [comment]
[GOV.UK Design System working group - Principles and ways of working](https://docs.google.com/document/d/1ewdYdNUnCd9gYAbMRKhtThtWN0WAWsWyAwt-kwDRR7g/edit#heading=h.z130ivfggw68)

**Comment by davidhunter08** [comment]
[MOJ (Ministry of Justice) Design system working group](https://moj-design-system.herokuapp.com/community/design-system-working-group)

**Comment by davidhunter08** [comment]
**Notes:** Red-gate design working group
Meeting held on 18-Nov-20

**Design system name:** Honeycomb

**Working group:** organically formed

**Group size:** 8 [4 designers/ 4 developers]

**Group make up:** Broad design set [brand, product, interaction], developers [front-end, full stack]

**Schedule:** 2hrs every Friday morning + high level planning on Thursday with head of product and head of engineering

**Format:** standup [roundtable, catch-up, problems, collaboration, prioritisation]

**Facilitation:** One lead facilitator

**Decisions:** Group consensus, disagreement gets resolved by head of product and head of engineering

**Motivation:** developers join to boost skills, tries to match role with those looking for development opportunity. Gives VIP treatment to contributors [faster responses]

**Communications:** share progress on slack

**Advocacy:** relies on members to act as trojan to reach other developers. Uses same with head of product and head of engineering as backing

**Comment by davidhunter08** [comment]
See also https://github.com/nhsuk/nhsuk-service-manual/issues/812
