### ISSUE TITLE
Prepare for March 2021 Content Style Council meeting

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk-service-manual#793]
## What

Invite people, prepare the agenda and slides for the meeting.

## Done when

- [ ]  Arrange room - not needed
- [x]  Agree meeting date - Sara, Olivia, Karin
- [x]  Arrange Teams meeting and send out invite - Lucy
- [x]  Firm up agenda with Olivia and Anna 
- [x] Get issues ready with colleagues
- [x]  Make sure that GitHub is up to date
- [x]  Share agenda and info about topics up for discussion - by email, on NHS.UK and NHS digital service manual Slack
- [x]  Prepare slides with Olivia
- [x] Sent out slides the day before
- [x] Olivia to chair the meeting - with Sara

**Comment by sarawilcox** [comment]
Potential issues for this meeting: 
- [Components and headings](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/301)

**Comment by sarawilcox** [comment]
### Draft agenda 

 Discussed with @OliviaThornton, @annasutton2, @sarahallen57 and @teodorastraianu1

**Welcome and introduction** - Olivia

**Updates from January meeting** - Sara
- hyphens and spaces - or dashes - published some more guidance and examples but there are some outstanding issues​ on GitHub issue 
- readability tool and link to SMOG calculator​ - removed from style guide
- reading age - Sara to feedback about plans for user research​
- jab or vaccine - on agenda for this meeting​
- PDFs - updated guidance published but it's now going to Accessibility Working Group for info – also we may need to clarify our guidance on open document formats (ODFs)

**Other updates** - Sara
- Accessibility testing some content scenarios : components and headings, inset text, hint text
- Reviewing care card guidance, do and don't list and review dates - to be republished as patterns

**Call out to contribute research findings** - Olivia

**Issues for discussion and approval** - Olivia
- covid jab/vaccine - Gerard, Laura or Jean (Sara to let them know)
- alt tag change - Anna, Teodora and Sarah
- skin symptoms guidance - Anna, Teodora and Sarah - may be just an update or maybe some content for discussion - we'll probably consult further/hold over approval till April meeting - but let's see what people think about where it should go in the style guide
- long descriptions - Anna, Teodora and Sarah - probably only an update at this stage
- GP systems suppliers - Olivia
- <strong> or <b> for bold - Sara
- phlegm, mucus, sputum - Olivia - maybe discussion but not approval

AOB, thank you and close meeting - Olivia

**Comment by sarawilcox** [comment]
Draft slides: https://hscic365.sharepoint.com/:p:/r/sites/servicemanual/_layouts/15/Doc.aspx?sourcedoc=%7B010E760D-8558-4574-B7AE-CD01FFD199FF%7D&file=Style%20Council%20meeting%20-%20March%202021.pptx&action=edit&mobileredirect=true

**Comment by sarawilcox** [comment]
Waiting for Anna and Olivia to add their slides. I'll pick this up next Monday.

**Comment by annasutton2** [comment]
I'll add slides for the long descriptions update on Wednesday.

**Comment by sarawilcox** [comment]
All done. Close this ticket.
