### ISSUE TITLE
Workshop to define a contribution

### ISSUE THREAD

**Issue by amyj2110** [nhsuk/nhsuk-service-manual#800]
# What
Hold a workshop in order to come up with a working definition of a community contribution.

# Why
So the team and users of the service manual can understand exactly what a contribution is and how it works.

# Relates to
EPIC: Community contribution #685  

# Depends on

# Done when
Tasks we need to do:
- [x] Schedule workshop to define contribution
- [x] Complete workshop
- [x] Share finalised contribution definition with the rest of the team

**Comment by amyj2110** [comment]
First working draft of a contribution definition:

> A contribution is when you add or change something in the service manual. Anyone using the service manual can provide a contribution. A contribution should be based on evidence or research insights and be available to be shared with the wider service manual community. By contributing to the service manual, you can help improve it for others in the future and make sure we are doing things right.
> 
> There are lots of different ways you can contribute to the service manual. Some of the ways you can contribute include [from smallest to largest?]:
> 
> - Joining in with discussion by adding a comment to an issue
> - Documenting discussions about issues in GitHub
> - Correcting spelling mistakes or small errors on service manual pages
> - Submitting a bug report when something isn't working
> - Changing the code on a service manual page
> - Submitting research or evidence for existing components, patterns or style guide entries
> - Suggesting changes to existing components, patterns or style guide entries
> - Proposing a new component, pattern or style guide entry

**Comment by Tosin-Balogun** [comment]
I think this captures the combination of all the things we got from the research. Will read it again tomorrow because it probably needs refinement or perhaps, we play this back to the community and see what they think?

>There are lots of different ways you can contribute to the service manual. Some of the ways you can contribute include [from smallest to largest?]:

Perhaps it could say big or small? @amyj2110

**Comment by henocookie** [comment]
I really like the first paragraph @amyj2110, I think it covers everything from the contribution definition workshop well!

In the examples of how people can contribute, would "Correcting spelling mistakes or small errors on service manual pages" and "Submitting a bug report when something isn't working" completely cover "Changing the code on a service manual page", or are there other instances people would change service manual page code @davidhunter08 @sarawilcox?

Also, do we want to add another bullet to the list of examples that covers "Develop a component or pattern that has been approved by the design working group" to include the development for new parts of the design system?

**Comment by amyj2110** [comment]
> I think this captures the combination of all the things we got from the research. Will read it again tomorrow because it probably needs refinement or perhaps, we play this back to the community and see what they think?
> 
> > There are lots of different ways you can contribute to the service manual. Some of the ways you can contribute include [from smallest to largest?]:
> 
> Perhaps it could say big or small? @amyj2110

Ah sorry, I put the [from smallest to largest] in there as a suggestion for us, like should we list them from smallest to largest so we're not leading with the biggest and most complicated one.
Or did you mean say big or small somewhere in the sentence?

**Comment by amyj2110** [comment]
> Also, do we want to add another bullet to the list of examples that covers "Develop a component or pattern that has been approved by the design working group" to include the development for new parts of the design system?

Yep, that's a good one. Could say something like that and also include:
- "Develop a content style guide entry that has been approved by the content style council"?

**Comment by davidhunter08** [comment]
Nice work @amyj2110 

You got me thinking about contribution types last night and came up with this:

### Contribution types for…

All repos (frontend, service manual, prototype kit):
- Commenting (sharing research, discussing, asking a question) on a backlog issue
- Reporting a bug (Create GitHub issue)
- Fixing a bug / improving code or documentation (Create GitHub PR)

Content style guide:
- Proposing a new addition to the content style guide (Create GitHub issue)
- Developing a new addition to the content style guide (Create GitHub PR)

Design system:
- Proposing a new component or pattern (Create GitHub issue)
- Developing a new component or pattern (Create GitHub PR)

Prototype kit:
- Proposing a new prototype kit feature (Create GitHub issue)
- Developing a new prototype kit feature (Create GitHub PR)

**Comment by amyj2110** [comment]
@davidhunter08 that's great! Do you think it's worth mentioning that in the definition (about different repos) or will that confuse people further? 😄 
Could be something we could use to direct people to the right place depending on what they want to do?

**Comment by sarawilcox** [comment]
It's looking good. You say: "A contribution is when you add or change something in the service manual" but that would exclude some of the examples, like making a comment or sharing research. Is it that "A contribution is when you do something to help add or change something in the service manual"?

I can suggest some changes to wording but perhaps I should do that when we're closer to finalising things?

**Comment by Tosin-Balogun** [comment]
>Ah sorry, I put the [from smallest to largest] in there as a suggestion for us, like should we list them from smallest to largest so we're not leading with the biggest and most complicated one.
Or did you mean say big or small somewhere in the sentence?

Now that you mention, i think it's a good idea to introduce the smallest contribution first. I was thinking about adding that within the sentence but it's not important.

>that's great! Do you think it's worth mentioning that in the definition (about different repos) or will that confuse people further? 

I think there is an idea for user type pathways on the Miro board as well as templates to quick-start their contribution type. I would not worry much about mentioning it as it could intimidate some users i feel. @amyj2110 
Big fish can correct me @davidhunter08

**Comment by cjforms** [comment]
Great to see this going on there.

In the first paragraph, you've got:
"A contribution should be based on evidence or research insights and be available to be shared with the wider service manual community. "

I'm always on the look out for 'should' because of my oft-quoted motto "seek and destroy 'should'"

In this case, I think that 'must' is too sweeping, as I don't need any evidence or research insights in order to point out a typo, or comment on something such as (ahem) the use of the word 'should'. 

In fact, I think that this needs to be nuanced according to the type of contribution. 

As you've also probably heard me say many times, I'm a great believer in keeping design systems as small as possible for many reasons, so I'd make the evidence requirements for new components really strict: 

'If you plan to propose a new component, please try to design with our existing components first. Any proposal for a new component must be supported by evidence that a design with our existing components does not work well for users, as well as evidence that the new component clearly works better".

But I'd make the evidence requirements for small comments minimal to none. 

In between, we have things like adding a new word to the content style guide where I believe that you want some evidence but it doesn't need to be quite as stringent as for a new component. 

By the way: I do have evidence for these comments!

**Comment by davidhunter08** [comment]
@amyj2110 Yeah I wouldn't mention the different repos in the definition, or else 🤯

It was the "right place" I had in mind. I've been told on a few occasions by designers that they are unsure of what goes where when it comes to creating issues, as we multiple repos (that all look the same). 

My hypothesis would be something like:

**If** we group the types of contribution by the product (or even profession)
**Then** people will be clearer about what type of contribution goes where

**Comment by davidhunter08** [comment]
Sorry I went a bit off topic from discussing the 'definition' @amyj2110

**Comment by sarawilcox** [comment]
@amyj2110 I'm not sure that content designers will understand "develop" in "Develop a content style guide entry that has been approved by the content style council". (They might think develop is what devs do.) But they'd probably understand "Add or amend and publish a content style guide entry that has been approved by the Content Style Council".

**Comment by amyj2110** [comment]
@sarawilcox yes, perhaps you and I can thrash it out a bit more next week. And I take your point about the "Develop", I think what you've written there is a better way of framing it.

@davidhunter08 I get where you're coming from about the repos. Would it be beneficial to have different definitions within each repo?

@Tosin-Balogun agreed, it's nice to start with the smallest thing people could do! We'll try to keep this as simple and understandable as possible!

@cjforms thank you for contributing to the contribution definition! 😄 I am loathe to add "should" too, but like you say, not absolutely everything in that list requires "evidence" per se. I like your idea to nuance the amount and type of evidence depending on the level of contribution. I think that's something we could probably weave into the definition easily enough. I am of the mind that we want to make it as easy and simple for as many people as possible to contribute. If we can remove some perceived hurdles like this, then it will make it better. (I nearly typed should then and caught myself! 😅 )

**Comment by amyj2110** [comment]
![image](https://user-images.githubusercontent.com/60343363/98927304-45eeaf80-24d0-11eb-9d4f-7809145de9c2.png)

The outputs from our workshop created these themes for the definition:

- **Mention the process (broadly)** - what might the contribution process be, in simple terms
- **Should be based on evidence or research insights** - contributions based on experience, evidence, insights or research
- **Sharing and documented discussion** - discussion that is captured or documented in some way, and sharing could be a motivation for some
- **Where can you contribute?** - understanding what forums people can contribute in, be it Slack, GitHub, backlogs or community forums
- **Motivations to contribute** - feedback and improving the service manual, supporting others, helping the service manual and the NHS as a whole
- **Practical examples of what a contribution is** - helping people understand the different ways to contribute through practical examples they can relate to
- **Who can contribute?** - reiterating that anyone can contribute in some way

**Comment by amyj2110** [comment]
A word cloud to show the top 15 words used by participant to define a contribution to the service manual in their own words.

<img width="1007" alt="Screenshot 2020-11-16 at 13 38 41" src="https://user-images.githubusercontent.com/60343363/99258908-24affb00-2811-11eb-8aff-89b72e644067.png">

**Comment by amyj2110** [comment]
Version 2 of the contribution definition is here! Please read below, all comments welcome:

> A contribution is when you do something to grow or improve the service manual. Anyone who uses the service manual can make a contribution.
>
> Contributions should be based on evidence or research insights, where possible, and shared openly with the wider service manual community. By contributing to the service manual, you can help keep it relevant and up-to-date and make sure everything in it is high quality and meeting user needs.
>
> There are lots of different ways you can contribute to the service manual, small or big. For example, you can:
> - join the discussion by commenting on an issue
> - document discussions about issues in GitHub
> - correct spelling mistakes or small HTML errors or fix other code on service manual pages
> - report a bug when something isn't working
> - share research or evidence for existing components, patterns or content style guide entries
> - suggest changes to existing components, patterns or style guide entries
> - make approved changes to the service manual after a Style Council or Design Working Group meeting
> - propose or create a new component, pattern or style guide entry

**Comment by cjforms** [comment]
This is really coming along nicely. 

I'm happy with everything apart from the sentence "Contributions should be based on evidence or research insights, were possible, and shared openly with the wider service manual community'.

1. I think it's in the wrong place. If you move it to AFTER the bullet list, then it will make more sense.
2. It's got two topics in one sentence. If you split it into two, it will be easier for us to work on it to get it right.
3. I don't know what "shared openly with the wider service manual community" means and I don't know why I have to share everything with everyone. For example, I recently spotted that someone had shared a document with the frequent typo "pubic" for "public". For obvious reasons, I preferred to mention that typo in private.
4. I don't agree with the 'should' and 'if possible' construct. It's confusing. My suggestion for that sentence is to make it more definite and more explicit, like this: "We prefer it when you mention any evidence or research insights that support your contribution. We need research before we create a new component, pattern or style guide entry and your research can help us to speed up the process".

**Comment by sarawilcox** [comment]
Thanks @cjforms. I think you're right that we're addressing 2 things in 1 sentence. And yes, we could put it underneath the bulleted list because it's additional info. I'll have a go at rewording this.

**Comment by sarawilcox** [comment]
How about these 2 sentences underneath the bulleted list?

We base new components, patterns and style guide entries on user research and insight. By including evidence in your contributions, you will help speed up the process.

We work in the open in GitHub so that as many people as possible can contribute and review the community's work.

**Comment by cjforms** [comment]
@sarawilcox Your version is much, much better than mine. Thanks.

**Comment by henocookie** [comment]
Closed this issue as we will start to test the working contribution definition with people using the service manual. This is tracked in https://github.com/nhsuk/nhsuk-service-manual/issues/826 #826
