### ISSUE TITLE
In-depth survey analysis

### ISSUE THREAD

**Issue by amyj2110** [nhsuk/nhsuk-service-manual#802]
# What
Carry out some more in-depth analysis on the contribution survey. This will involve cross-sectioning the data to look at responses based on:
- Role
- Company
- Whether or not someone has contributed

# Why
So we can see if there are any differences based on someone's role, company or whether or not they have previously contributed.

# Relates to
EPIC: Community contribution #685  
Plan and distribute community contribution survey #718 

# Depends on

# Done when
Tasks we need to do:
- [x] Complete in-depth analysis based on roles
- [x] Complete in-depth analysis based on company
- [x] Complete in-depth analysis based on whether or not someone has contributed
- [x] Share any findings with the wider team

**Comment by henocookie** [comment]
Will work with @AdamChrimes on Monday to create a `service-manual.nhs.net/nice-survey-link` type of URL.

I will then post and pin an issue on the [nhsuk-frontend](https://github.com/nhsuk/nhsuk-frontend) repo to try and get more developer feedback about contributing to the service manual.

**Comment by amyj2110** [comment]
### I feel confident in contributing
- Delivery managers and product owners feel less confident to contribute
- A higher proportion of content designers feel more confident to contribute
- User researchers are split in levels of confidence
- People who have not contributed before are likely to have less confidence in contributing
- People working outside of NHS Digital feel less confident to contribute

### I do not feel confident showing my work to people I don't know
- Interaction designers mainly feeling more confident, but some less so
- Content designers and user researchers split in levels of confidence
- People who have previously contributed are more likely to feel more confident to show their work
- People working outside of NHS Digital feel confident to share their work

### I know what I need to do if I wanted to make a contribution
- Content designers more likely to know what they need to do
- Product owners less likely to know what they need to do
- Interaction designers and user researchers generally split
- People who have not contributed or are not sure if they have contributed are less likely to know what they need to do
- People who have previously contributed are more likely to know what they need to do
- People working outside of NHS Digital are less likely to know what they need to do
- NHS Digital employees are generally split

### If I contribute, I know what will happen next
- Content designers more likely to know what will happen next
- Interaction designers, user researchers and product owners less likely to know what will happen next
- People who have not contributed are less likely to know what will happen next
- People who have previously contributed are mostly likely to know what will happen next, but a small proportion do not
- People working outside of NHS Digital are not likely to know what happens next

### I feel confident using GitHub to make a contribution
- Content designers and interaction designers are more confident in GitHub
- Developers are very confident in GitHub
- User researchers feel less confident in GitHub
- People who have not contributed are less confident with GitHub
- People who have previously contributed are split in confidence levels
- People working outside of NHS Digital are not likely to be confident using GitHub

### I feel supported by my team to contribute
- Content designers and interaction designers are more likely to feel supported
- User researchers are split in feeling supported
- People who have previously contributed are more likely to feel supported by their team
- People working outside of NHS Digital are split in feeling supported
- NHS Digital employees mostly feel supported by their team

### I have enough time to contribute
- Content designers, interaction designers and user researchers are split, slightly more interaction designers feel like they have time to contribute
- Product owners feel like they have time to contribute
- Regardless of contributing before, people are split
- Regardless of organisation, people are split

### I see it as part of my role to contribute
- Content designers and interaction designers feel like it's part of their role to contribute
- User researchers are split
- People who have previously contributed strongly feel like it's part of their role to contribute
- People who have not contributed also feel like it's part of their role to contribute
- NHS Digital employees mostly feel like it's part of their role to contribute
- Some people outside of NHS Digital feel like it's part of their role to contribute, but a small proportion strongly feel that it isn't their role to contribute

### Other bits
- More interaction designers expect a thank you after they contributed
- More people who haven't contributed before want process guidance, emails telling them the next steps and for the service manual team to check whether there is an existing issue similar to the one they want to contribute
- Slightly more content designers see themselves as part of a community and feel encouraged to contribute
- Less people working outside of NHS Digital are expecting to receive GitHub training
- People working outside of NHS Digital are more likely to have commented or discussed something as part of a contribution
