### ISSUE TITLE
Collect statistics from comms team on social media analytics

### ISSUE THREAD

**Issue by lucyha** [nhsuk/nhsuk-service-manual#803]
## What

Liaise with comms team to access social media analytics.

## Why

To include these analytics in our analytics reporting.

## Done when

- [x] Email sent to comms team for an update on access

**Comment by AJSMITH1512** [comment]
Meeting held with Comms Team (Bernie Keavey) to explore availability of feedback information from social media. Next steps to run through the data independently and determine if we need additional reporting set up. The data available will enable us to see the impact of releases and communication materials - the impact of the UCD Blogs is a clear in the charts available.
