### ISSUE TITLE
GitHub statistics automations / dashboard

### ISSUE THREAD

**Issue by AdamChrimes** [nhsuk/nhsuk-service-manual#805]
## What

Following on from #779 look at automating some of the GitHub statistics and potentially present them in a dashboard.

## Why 

So that we can continuously monitor some of the contribution figures that we pulled out in the baseline statistics.

## Further information

Use the GitHub API to pull out some of the statistics, similar to what we have done for the NHS.UK frontend library release data. Example: https://chrimes.dev/releases

- NHS.UK frontend library
- NHS.UK prototype kit (?)
- NHS digital service manual
- NHS digital service manual backlog

Number of contributions (code and issue comments)
Organisation of the contributor
Job role of the contributor

**Comment by Tosin-Balogun** [comment]
## What
From our [EPIC: Help users understand how to use GitHub for contributing
#991](https://github.com/nhsuk/nhsuk-service-manual/issues/991), we need some baseline statistics on how people use GitHub, these are

## Statistics

- We need to know the number of people using GitHub
- We need to know the percentage of new users joining our GitHub space
- We need to know the number of people commenting to work in progress.
- We need to know the number of people raising new issues per repository
- We need to know where people come from into our GitHub repos [our website pages or other]
