### ISSUE TITLE
Speak to the GOV.UK Design System team regarding their working group

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#812]
## What

Speak to the GOV.UK Design System team to find out more their working group structure and processes.

## Why

The GOV.UK Design System working group is well established and so speaking to the team that runs the group will help us when forming our own design system working group.

## Relates to

[EPIC #666](https://github.com/nhsuk/nhsuk-service-manual/issues/666)

## Done when

- [x] Spoken to the GOV.UK Design System team
- [x] Compiled and shared notes with the service manual team

**Comment by davidhunter08** [comment]
See https://github.com/nhsuk/nhsuk-service-manual/issues/666#issuecomment-726618979

**Comment by Tosin-Balogun** [comment]
Tim P. from GOVUK has responded to my request. A schedule is looking possible for Friday 20th November 2020 at 11:00AM 🏃🏿‍♂️ ⏲️ 🥅

**Comment by davidhunter08** [comment]
## GOV Design System working group

Notes from our meeting with Rosie (UR) and Trang (Product) from the GOV.UK Design System team.

### Group composition

Multi-disciplinary
- FE dev
- Interaction designers
- Content designers
- User researchers (but not many)

Different departments
- Try to get representatives for each department
- Expected that representatives would engage with other people from their department in regards to feeding back on contributions

Number of members
- Max 12
- Currently has 11
- Like to have an uneven number to help come to decisions
- Having a max of 12 people keeps the group relatively small but also allows for people not providing feedback

Rotation
- Change every 3-6 months
- 6 months is the optimum (enough time for consistency but also keeps it fresh)
- Keeps it diverse

Experience
- Tends to be “experienced” people (and also people that the team knows)
- Assumption that “experts” can be intimidating 
- But sees no reason why a “more junior” person can join in - it depends on the person - are they comfortable providing feedback?

Recruitment
- Initially recruited members through heads of departments
- Existing members recommend people to join
- Also tends to be people who the team already know
- Occasionally get volunteers
- Currently a waiting list for new members

### Group processes

Team responsibility
- Each month the full process is facilitated by a different member of the team
    - Organise
    - Facilitate
    - Feedback

Reviewing contributions
- Gathers responses on a spreadsheet
- Spreadsheet sent out 2 weeks prior to decision - gives plenty of time
- Some fill in straight away, some wait until the end of the 2 weeks
- Used to collect responses using Google forms but that wasn’t working - too much work for the team
- A spreadsheet helps others providing their feedback - knowing they are doing it right and reconsidering their thinking
- Look at settling disputes by looking at the research - all decisions should be evidence based
- Capacity to review 1-2 things per month - could be more but depends on the size of the thing (component, pattern, guidance)
- The group has a list of what they should and shouldn’t be reviewing, for example: 
   - Should = All new components and patterns 
  - Shouldn’t = Modifications to existing components with minor design changes

Backlog prioritisation
- The backlog isn’t prioritised as well as it could be
- Plans to improve the process - this could include prioritising items against a new criteria (similar to RICE framework)

Retros
- Tend to have retros with the group every 3-6 months
- Also done surveys to gather group feedback

**Comment by Tosin-Balogun** [comment]
Updated the notes above ☝🏿 😄 🕺🏿 @davidhunter08
