### ISSUE TITLE
Issue with JavaScript in Design System examples

### ISSUE THREAD

**Issue by 36degrees** [nhsuk/nhsuk-service-manual#814]
Hey folks 👋🏻 

Just noticed that the examples in the NHS Design System aren't working correctly at the minute – it looks like your content security policy is preventing the inline JS that adds the `js-enabled` class from running.

> Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-+6WnXIl4mbFTCARd8N3COQmT3bJJmo32N8q8ZSQAIcU='), or a nonce ('nonce-...') is required to enable inline execution.

For examples, the [radios component is falling back to showing all of the conditionally revealed content](https://service-manual.nhs.uk/design-system/components/radios#conditionally-revealing-content):

![Screenshot 2020-11-11 at 09 35 54](https://user-images.githubusercontent.com/121939/98794844-70256c00-2401-11eb-9e97-611aea6bbe60.png)

**Comment by AdamChrimes** [comment]
Hey @36degrees thanks for raising this. This was me trying to be clever with http headers, it should be sorted now.
