### ISSUE TITLE
Run community contribution usability tests

### ISSUE THREAD

**Issue by henocookie** [nhsuk/nhsuk-service-manual#821]
## What
Test how well users can contribute to the service manual with the current processes and guidance.

## Why
To speak with people that use the NHS digital service manual to understand how easy or difficult they find contributing, using the current process and guidance.

## Relates to
EPIC: Community contribution #685 

## Depends on
#717 

## Who needs to know about this
User researchers @henocookie  @amyj2110, service manual team

## Done when
- [x] Tested process with users
- [x] Session notes saved
- [x] Session recordings added to confluence

**Comment by henocookie** [comment]
Tested with 11 participants on Friday 13th November and Monday 16th November. 1 more session on Tuesday 17th November planned.

**Comment by AdamChrimes** [comment]
Test comment

**Comment by henocookie** [comment]
Session notes recorded on Trello and recordings on the Service manual team OneDrive space
