### ISSUE TITLE
Prioritise all the HMW by effort/impact

### ISSUE THREAD

**Issue by Tosin-Balogun** [nhsuk/nhsuk-service-manual#842]
## What
We need to prioritise which how might we questions we focus our attention on based on where we think we can make the biggest impact

## Why
While we need to do everything for this project to be successful, we cannot realistically do all of it at once. This allows us to focus on where needs our attention the most

## To do

- [x] Plan and prep prioritisation session
- [x] Run prioritisation session
- [x] Write-up and share session summary

**Comment by Tosin-Balogun** [comment]
Schedule set for Tuesday 2nd February to complete this task ⏲️ 👀

**Comment by Tosin-Balogun** [comment]
# HMW Matrix Prioritisation Workshop Outcomes

On Tuesday 02-Feb-2020, the team completed a prioritisation matrix workshop for the series of 'how might we' statements derived from our user problems. We derived the following;

<img width="1052" alt="Screenshot 2021-02-02 at 15 19 36" src="https://user-images.githubusercontent.com/71393402/106621460-80fdfd80-656a-11eb-82ad-8a932fbc02ce.png">
<img width="1035" alt="Screenshot 2021-02-02 at 15 20 01" src="https://user-images.githubusercontent.com/71393402/106621474-83f8ee00-656a-11eb-9041-0e3291472ecf.png">
<img width="988" alt="Screenshot 2021-02-02 at 15 20 16" src="https://user-images.githubusercontent.com/71393402/106621483-852a1b00-656a-11eb-8f8d-bb0247aac5b5.png">

## Considerations
As part of the session, the team had rich discussions where we identified that;
- There is a need to understand what is expected in giving users support whilst contributing
- Finding connecting dependencies between items in the 'Do it now' and the 'Do it next' bucket

## What next
We plan to take our top priority items into an #843 ideation session where we hope to generate potential solutions to solving them

**Comment by sarawilcox** [comment]
A note about the second bullet point above: we identified that focusing on the "Do it now" bucket might increase demands on the team's time. It may be worth focusing on the "Do it next" bucket first to put in place processes that will help us manage any increase in contributions generated through "Do it now" work.
