### ISSUE TITLE
Draft brief for open working project

### ISSUE THREAD

**Issue by lucyha** [nhsuk/nhsuk-service-manual#865]
## What

Draft a brief for the team on the goal of the discovery for the open working project.

## Why

To ensure the work has a focus and scope is understood.

## Done when

- [x] Document drafted
- [x] Document shared for reveiw

**Comment by AJSMITH1512** [comment]
Meeting being held with Amy James 21/12/20202
Meeting being held with Matt Edgar 21/12/2020
Draft of Brief in progress - highlights to include the Objectives, proposed outcomes and complementary work
