### ISSUE TITLE
EPIC: Add hero component to the service manual

### ISSUE THREAD

**Issue by chrimesdev** [nhsuk/nhsuk-service-manual#884]
## What

Following code and design improvements to the Hero component in the NHS.UK frontend library, add this to the NHS digital service manual.

## Why

The Hero component is commonly used but whilst it exists in the NHS.UK frontend, it doesn't exist on the NHS digital service manual. It also needs a few design and code improvements.

**Comment by AdamChrimes** [comment]
I think this is something we need to look at in the near future, discuss at this weeks planning
