### ISSUE TITLE
Write outcomes for inclusion discovery

### ISSUE THREAD

**Issue by amyj2110** [nhsuk/nhsuk-service-manual#888]
## What

Using the plan and conversations with stakeholders and teams, we need to write outcomes for our inclusion discovery.

## Why

We need some outcomes to focus our thinking for the inclusion discovery.

## Must do
- [x] Write outcomes
- [x] Check outcomes with the rest of the team - Stand up 22/01/2021
- [x] Review and adjust statements after reviewing with the rest of the team
- [x] Check outcomes (version 2) with the rest of the team - Sprint review 28/01/2021
- [x] Review and adjust statements after reviewing version 2 with the rest of the team

**Comment by henocookie** [comment]
Showed the initial outcomes/goals with the whole service manual team this morning. We will now review these and adjust after receiving feedback and ideas

**Comment by henocookie** [comment]
Shared the changes with the service manual team at the sprint planning session today and these were well received. A couple of extra bits of feedback to incorporate to the outcomes.

**Comment by henocookie** [comment]
Closed this issue for now as we will likely change outcomes once the discussions with stakeholders, NHS teams and external experts, as well as charities, groups and organisations that represent end-users, have completed
