### ISSUE TITLE
Organise meetings with stakeholders, NHS teams and external experts

### ISSUE THREAD

**Issue by amyj2110** [nhsuk/nhsuk-service-manual#889]
## What

Put meetings in the diary with key stakeholders for this project, NHS Digital teams, and external inclusion experts.
List is [here](https://nhsd-confluence.digital.nhs.uk/x/0-a6CQ).

## Why

We need to make contact with other people conducting inclusion work within NHS Digital to align our thinking and make sure work is not being duplicated.
We need to speak to teams within NHS Digital to discover what their barriers to being inclusive are.
We need to speak to external experts to find out what has worked for them and if there's anything else we are missing.

## Must do
- [x] Calendar invites sent for most of the list

**Comment by henocookie** [comment]
@amyj2110 and @ericlamarca, let us review the list of key stakeholders for this project, NHS Digital teams, and external inclusion experts we are still yet to speak with and agree if:
- there are more meetings we want to schedule,
or
- we are happy with the findings and evidence gathered so far.

**Comment by henocookie** [comment]
Happy with the number of conversations we have had at this point, at this stage of the work.

We appreciate conversations will continue, but I'm closing this ticket now that this initial phase will be complete at the end of today, after 2 more meetings with stakeholders, NHS teams and external experts.
