### ISSUE TITLE
Complete desk research for inclusion discovery

### ISSUE THREAD

**Issue by amyj2110** [nhsuk/nhsuk-service-manual#890]
## What

Finish off the desk research around inclusion, diversity and accessibility.
Findings as [here](https://nhsd-confluence.digital.nhs.uk/x/9KXuCQ).

## Why

Desk research will provide us with some potential contacts and themes we can start to work on or prioritise according to the work we already have planned.

## Must do
- [x] Complete desk research
- [x] Collect outcomes or [themes](https://nhsd-confluence.digital.nhs.uk/display/SMDS/Initial+desk+research+-+themes) to focus on

**Comment by ericlamarca** [comment]
Our initial desk research is done, on Confluence: https://nhsd-confluence.digital.nhs.uk/display/SMDS/Desk+research

We've drafted themes here: https://nhsd-confluence.digital.nhs.uk/display/SMDS/Themes+from+the+desk+research+-+for+internal+organisation

We'll be sharing these with the team next week.
