### ISSUE TITLE
Meet with the IA team to discuss modified components

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#892]
## What

Meet with the IA team to discuss the design system components that have been modified for the NHS website and discuss the next steps for having these changes reviewed by the Design System Working Group.

## Why

If the modified components (Eg: breadcrumb) are rolled out across the NHS website before being reviewed by the Design System Working Group, there is a risk that services across the NHS will become confused about what version of the component they should use and how they should use it.

## To do

- [x] Arrange meeting with the IA team
- [x] Have the meeting and take notes
- [x] Publish meeting notes including decisions and next steps

**Comment by davidhunter08** [comment]
Meeting planned for Friday 22nd January. Invites sent to Ben Cullimore, Dean Vipond and Eric Lamarca.

**Comment by davidhunter08** [comment]
## Meeting notes

Eric and I met with Ben (Senior designer, IA team) and Dean (Lead designer).

Spoke about the service manual roadmap, priority of EPICs, current work (contribution and design system working group) and future work (including adding IA components/guidance to the service manual).

We discussed a few specific changes made by the IA team and agreed on some next steps to take:

### Breadcrumb and main container spacing

The service manual team are to:

- Investigate the changes on other types of services/pages and create visual mock-ups to illustrate and measure the impact
- Explore having the changes tested by 2 other services (with a representative range of users, including those with disabilities, in a prototype or live service) in order to gather further evidence

### Header component

The IA team are to:

- Continue exploring iterations to the header eg: exposing the nav and search on smaller screens
- Consider the impact of changes to the header on other types of services eg: what happens if there are more or less items in the navigation

### Support / contribution process

- The service manual team are to support the IA team in preparing any contributions for the design system working group to review

## Questions

- Is the relationship between the service manual and NHS website different to any other service? If yes, what is the relationship?
- What’s the impact of the NHS website and service manual being out of sync with core components (eg: header, breadcrumb)?
- Should all NHS website teams be considering the wider impact of their design and code changes? If yes, how do they do that?

**Comment by Tosin-Balogun** [comment]
>Continue exploring iterations to the header eg: exposing the nav and search on smaller screens

This sounds like something that involves prototyping?

>The service manual team are to support the IA team in preparing any contributions for the design system working group to review

That working group cannot come fast enough
