### ISSUE TITLE
Left align content guidance

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#896]
## What

Add guidance for aligning content.

## Why

Request from the community backlog https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/297

**Comment by sarawilcox** [comment]
@davidhunter08 Is this also a layout issue? Layout label?

**Comment by sarawilcox** [comment]
Close this issue. It's covered by [Text-alignment](https://github.com/nhsuk/nhsuk-service-manual-community-backlog/issues/297).
