### ISSUE TITLE
Plan the satisfaction survey (questions and time frame)

### ISSUE THREAD

**Issue by lucyha** [nhsuk/nhsuk-service-manual#904]
## What

Plan what questions to ask as part of the satisfaction survey and what pages to add it to.

## Why

To ensure we are asking the right questions to understand how satisfied our users are with the service manual.

## Done when

- [x] Questions agreed
- [x] Pages agreed

**Comment by amyj2110** [comment]
Questions I set up last year for a "Service Manual Monitoring" survey. I think @davidhunter08 @AdamChrimes and I put it on a couple of pages in early 2020.

[Link to survey questions](https://docs.google.com/document/d/1RB-oDq-3wC1OEr6sPZxchIxInUP9tKua6rWjAOKlAb0/edit?usp=sharing)
