### ISSUE TITLE
Set-up satisfaction survey on website

### ISSUE THREAD

**Issue by lucyha** [nhsuk/nhsuk-service-manual#905]
## What

Add the satisfaction survey to the agreed pages on the website.

## Why

To start to capture data on how satisfied our users are with the service manual.

## Done when

- [ ] Survey live on the service manual

**Comment by AdamChrimes** [comment]
User feedback form: https://github.com/nhsuk/user-feedback-form

**Comment by DomBaker** [comment]
In the process of raising a PR for the feedback form so that we can configure it as we require.
