### ISSUE TITLE
Complete desk research around service users inclusion

### ISSUE THREAD

**Issue by amyj2110** [nhsuk/nhsuk-service-manual#909]
## What

We have done some desk research into inclusion internally, within the organisation. But we can focus our attention on doing some desk research on barriers to inclusion for our service users.

## Why

This may allow us to get some information about groups who could prove difficult to reach in the time we have for discovery.

## Done when

- [ ] Desk research complete
- [ ] Themes and outcomes shared with the team

**Comment by ericlamarca** [comment]
Our initial desk research is done, on Confluence: https://nhsd-confluence.digital.nhs.uk/display/SMDS/Desk+research

We've drafted themes here: https://nhsd-confluence.digital.nhs.uk/display/SMDS/Themes+from+the+desk+research+-+for+internal+organisation

We'll be sharing these team next week.

**Comment by henocookie** [comment]
Agreed desk research will continue in the background between meetings and other work, but as there is nothing major to share with the wider team yet, this will remain in the backlog for now.
