### ISSUE TITLE
Get access to Pulsar

### ISSUE THREAD

**Issue by ericlamarca** [nhsuk/nhsuk-service-manual#922]
## What

The comms team mentioned we may be able to use Pulsar to learn from what people share on social media.

## Why

To inform the inclusion discovery.

## Tasks
- [x] Email comms team to get @amyj2110 and @ericlamarca access to Pulsar
- [ ] Get access and a demo of the platform

**Comment by henocookie** [comment]
Sent the NHS Digital comms team an email asking for accounts to be set up for @amyj2110 and @ericlamarca

**Comment by henocookie** [comment]
@henocookie to reply to Ammar from the comms team to thank them for setting up accounts. We have parked this for now, but may pick it up again later.

**Comment by henocookie** [comment]
I have replied to Ammar from the comms team to thank them for setting up Pulsar accounts for myself, @amyj2110 and @ericlamarca. We have parked this for now but may pick it up again later when we have hypotheses to test.
