### ISSUE TITLE
Blog: Stakeholder map presentation

### ISSUE THREAD

**Issue by Tosin-Balogun** [nhsuk/nhsuk-service-manual#927]
# What
After presenting the process of creating the stakeholder map #918  at the design huddle, the plan is to write all that was derived from it into a blog

# Why
This would create a reference point to look back on in the future in terms of how we arrived at this point as well as the lessons derived from it

**Comment by davidhunter08** [comment]
Thanks for the sharing a draft @Tosin-Balogun. I've read it and added a few comments. It's looking great!
