### ISSUE TITLE
Present stakeholder map to product delivery

### ISSUE THREAD

**Issue by Tosin-Balogun** [nhsuk/nhsuk-service-manual#930]
What
----
The service manual needed to understand the landscape of its relationship with different stakeholders. We have been able to plot the map in terms of who our understanding of our relationships but it is important to involve our stakeholders in validating what we have

Why
----
It is important to present this to our different stakeholders and community to have more visibility of it. This should allow for a more organic shared understanding of our relationships, spot gaps and opportunities to grow said relationships

Checklist
----
- [ ] Prepare presentation slides
- [ ] Do mock run
- [ ] Present

**Comment by davidhunter08** [comment]
Has this been done @Tosin-Balogun ?
