### ISSUE TITLE
Create presentation of findings

### ISSUE THREAD

**Issue by amyj2110** [nhsuk/nhsuk-service-manual#933]
## What

Create a digestible format presentation of our inclusion work findings so far.

## Why

- To be able to present back to people wider than our immediate team.
- To make a quicker and easier to understand format of our findings.

## Must do
- [x] Decide on a format
- [x] Create presentation

**Comment by henocookie** [comment]
Started to draft the presentation. Will review with @amyj2110 and @ericlamarca once they return from training and caring duties.

**Comment by henocookie** [comment]
First complete draft completed. Shared with @amyj2110 and @ericlamarca to review before closing this issue.
