### ISSUE TITLE
Book in feedback meeting with stakeholders

### ISSUE THREAD

**Issue by amyj2110** [nhsuk/nhsuk-service-manual#934]
## What

Start the conversation to book in a meeting with stakeholders to feed back our work up to now.

## Why

- To update our stakeholders on the work done so far
- To agree scope of work going forward

## Must do
- [x] Agree date range between ourselves
- [x] Approach stakeholders with a date

**Comment by lucyha** [comment]
Meeting booked for Thursday 11th March, 3pm - 4pm
