### ISSUE TITLE
Inclusion workshop stage 1 - Planning & booking

### ISSUE THREAD

**Issue by amyj2110** [nhsuk/nhsuk-service-manual#937]
## What

Plan, organise and book a workshop with the wider service manual team to feedback findings and explore hypotheses.

## Why

- To ensure the rest of the team knows what has happened.
- To gather feedback about findings so far.
- To gain insight into new areas to explore.

## Must do
- [x] Agree a date for the workshop with the wider team (23rd / 25th Feb pm)
- [x] Send invitation to workshop
- [x] Create workshop structure
- [x] Collect inspiration for workshop
- [x] Pilot workshop structure with ourselves

**Comment by henocookie** [comment]
@ericlamarca has created the workshop structure plan https://docs.google.com/document/d/1M8y8hzsJYTSsDL5y3iGwE96D83aAn0Q3LUulhR8khrk/edit#

**Comment by henocookie** [comment]
Inspiration frame is on Miro with some examples of what's out there: https://miro.com/app/board/o9J_lZ4wKoE=/?moveToWidget=3074457354394139196&cot=14

**Comment by henocookie** [comment]
Tested Microsoft Teams breakout rooms with @ericlamarca ahead of the workshop sessions.
