### ISSUE TITLE
Plan to present findings and hypotheses on a wider scale (show and tell / blog post)

### ISSUE THREAD

**Issue by henocookie** [nhsuk/nhsuk-service-manual#941]
## What

Start planning how to feed-back our findings and hypotheses for the inclusion discovery so far on a wider scale within NHS Digital. This could be at a show and tell, a blog post or something else.

## Why

To update people in the wider organisation on the high-level findings and hypotheses that we think may improve the ability to create inclusive NHS services

## Must do
- [ ] Agree who we want to share findings and hypotheses with more widely
- [ ] Decide the best way to reach as many of the people that we want to share with
- [ ] Prepare presentation/blog post or another way we will share

**Comment by lucyha** [comment]
Closed dues to duplicated issue
