### ISSUE TITLE
Start discussions with people working on the inclusive content checklist

### ISSUE THREAD

**Issue by henocookie** [nhsuk/nhsuk-service-manual#943]
## What

Book in and start a conversation with people working to create and implement an inclusive content checklist for content designers. This includes Rich Kelly and Rhiannon Smith.

## Why

To understand what work they are doing and if the service manual could be a place for any of their ideas to be located in.

## Must do
- [ ] Book in a chat with Rich, Rhiannon and others working on this
- [ ] Agree on questions we want to ask to scope out how much the service manual can help with this work

**Comment by henocookie** [comment]
Rhiannon shared a draft of the inclusive content checklist on the NHS.UK Slack space: https://nhsuk.slack.com/archives/C01C5FECHHR/p1613051444002600

**Comment by sarawilcox** [comment]
Hi @ericlamarca, @amyj2110 Should I close this ticket down now?
