### ISSUE TITLE
Care card - Review guidance

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#948]
## What

Review current guidance and usage of the care card component and propose what the pattern should cover.

## Why

Before we begin drafting the guidance, we need to understand the impact of re-writing the component as a pattern.

## EPIC

https://github.com/nhsuk/nhsuk-service-manual/issues/880

## To do

- [x] Review current guidance
- [x] Collect examples of care cards being used in NHS services
- [x] Review usage of care cards in other services

**Comment by davidhunter08** [comment]
Started collecting [examples of care cards in other NHS services](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/8#issuecomment-782018332).

Also started to [draft care card pattern guidance](https://docs.google.com/document/d/1hvMFfFBS8kzgbZM207P0OzhtF19yAmFr1wIjGnFXCfA/edit?usp=sharing).

**Comment by sarawilcox** [comment]
I've made some comments but would like to find out more from the content profession.
