### ISSUE TITLE
Prepare for April 2021 design system meet-up

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#956]
## What

Invite people, prepare the agenda and slides for the meeting.

## To do

- [ ]  Agree meeting date
- [ ]  Firm up agenda
- [ ]  Make sure that GitHub is up to date
- [ ]  Share agenda and info about topics up for discussion - on NHS.UK Slack
- [ ]  Prepare slides

**Comment by chrimesdev** [comment]
April was a long time ago
