### ISSUE TITLE
Plan design system backlog prioritisation exercise (April 2021)

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#957]
## What

Plan design system backlog prioritisation exercise.

## Why

We need the community to know when and what is happening.

## To do

- [ ] Arrange a date
- [ ] Set agenda
- [ ] Send invites with the agenda

**Comment by davidhunter08** [comment]
Possible criteria for prioritising:

Impact “How many designers/teams need this thing?”
v
Effort “How ready is this thing?”

**Comment by sarawilcox** [comment]
Done. Closing this issue.
