### ISSUE TITLE
Prepare presentation of findings

### ISSUE THREAD

**Issue by ericlamarca** [nhsuk/nhsuk-service-manual#971]
## What
We need to prepare a presentation of what we've found.

## Why
So we can present it to stakeholders.

## Must do
- [x] Review initial slides done by Henry
- [x] Decide next actions
- [x] Finish the presentation

**Comment by henocookie** [comment]
As agreed on 01/03/2021, @henocookie will refine the findings to an even more concise format. @ericlamarca will create some slides from the workshop ideation sessions. @amyj2110 will have a look at the other elements of the presentation such as the "work others are doing" and "what we're doing well"
