### ISSUE TITLE
Feed back to the groups we've spoken to

### ISSUE THREAD

**Issue by ericlamarca** [nhsuk/nhsuk-service-manual#975]
## What
We need to share our work with the groups we've interviewed.

## Why
So they can input. And so we're working with them, rather than just extracting information and disappearing. 

## Must do
- [x] Send out Mural board for feedback

**Comment by amyj2110** [comment]
Send out an email sharing this [Mural board](https://app.mural.co/t/servicemanual9172/m/servicemanual9172/1614181421976/55b5c4eb78b60c5482cccbf94f5559ae281b5a03)
