### ISSUE TITLE
Care card - Draft new pattern guidance

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual#988]
## What

Write draft guidance for the new care card design pattern guidance.

## Why

We need to draft the guidance and have it reviewed before adding it to the service manual

## EPIC

https://github.com/nhsuk/nhsuk-service-manual/issues/880

## To do

- [x] Draft the guidance
- [x] Share with senior interaction designers for feedback 
- [x] Share with senior content designers for feedback 
- [ ] Share with wider community for feedback
- [ ] Iterate guidance based on feedback

**Comment by davidhunter08** [comment]
[Draft guidance](https://docs.google.com/document/d/1hvMFfFBS8kzgbZM207P0OzhtF19yAmFr1wIjGnFXCfA/edit)

**Comment by sarawilcox** [comment]
Meeting with content designers next Wednesday lunchtime.

**Comment by sarawilcox** [comment]
I met with senior content designers. I need to go through the page again, taking on board content designer feedback. I'll do this next week.

**Comment by sarawilcox** [comment]
Hi @davidhunter08, I've been through the guidance and have resolved a number of comments but wonder if we could go through it together next week and decide what to do with outstanding issues?

**Comment by davidhunter08** [comment]
Sara and I are meeting today (Tue 27 April) to plan the next steps.

**Comment by davidhunter08** [comment]
## Next steps

1. Finalise guidance with a small group of the community who have contributed to the guidance
- [ ] Create Slack channel to organise meetings / gather feedback - Sara
- [ ] Facilitate meeting to discuss last few remaining issues - Sara + Dave
- [ ] Prep final guidance to send to design system working group

2. Assemble a design system working group to trial the review process and review the guidance
- [ ] Draft a plan for how we could trial the review process - Dave
- [ ] Create a Slack channel and invite members (who previously volunteered) to join - Dave
- [ ] Prep review session - Dave + Sara
- [ ] Facilitate review session - Dave + Sara

**Comment by davidhunter08** [comment]
Closing issue. Broken down into smaller tasks: https://github.com/nhsuk/nhsuk-service-manual/issues/1175, https://github.com/nhsuk/nhsuk-service-manual/issues/1176
